Repository influxdata/telegraf, pull requests merged in 2018-03, with the labels that each got.

#3799 Add Solr 3 compatibility
  plugins/inputs/solr/README.md
  plugins/inputs/solr/solr.go
  plugins/inputs/solr/solr_test.go
  plugins/inputs/solr/testdata3_test.go
Labels: enhancement

#3797 Add sum stat to basicstats aggregator
  plugins/aggregators/basicstats/README.md
  plugins/aggregators/basicstats/basicstats.go
  plugins/aggregators/basicstats/basicstats_test.go
Labels: enhancement

#3855 Fixing snmp input doc
  plugins/inputs/snmp/README.md
Labels: documentation

#3853 Add host to ping timeout log message
  plugins/inputs/ping/ping.go
  plugins/inputs/ping/ping_test.go
Labels: enhancement

#3773 Add Tags Processor
  plugins/processors/all/all.go
  plugins/processors/override/README.md
  plugins/processors/override/override.go
  plugins/processors/override/override_test.go
Labels: new plugin

#3786 different collations fix
  plugins/inputs/sqlserver/sqlserver.go
Labels: bugfix

#3871 fix uptime metric in passenger input plugin
  plugins/inputs/passenger/passenger.go
  plugins/inputs/passenger/passenger_test.go
Labels: bugfix

#3880 added config flag to skip collection of network protocol metrics
  plugins/inputs/system/NET_README.md
  plugins/inputs/system/net.go
  plugins/inputs/system/net_test.go
Labels: enhancement

#3928 Add tag for target url to phpfpm input
  plugins/inputs/phpfpm/README.md
  plugins/inputs/phpfpm/phpfpm.go
  plugins/inputs/phpfpm/phpfpm_test.go
Labels: bugfix

#3927 Add TLS support to kapacitor input
  plugins/inputs/kapacitor/README.md
  plugins/inputs/kapacitor/kapacitor.go
Labels: enhancement

#3496 add HTTP basic auth support to the http_listener input plugin
  etc/telegraf.conf
  plugins/inputs/http_listener/README.md
  plugins/inputs/http_listener/http_listener.go
  plugins/inputs/http_listener/http_listener_test.go
Labels: area/influxdb, enhancement

#3932 Fix DC/OS URL creation race
  plugins/inputs/dcos/client.go
  plugins/inputs/dcos/client_test.go
Labels: bugfix

#3938 Update passenger input documentation
  plugins/inputs/passenger/README.md
Labels: documentation

#3931 Add TLS settings to consul README
  plugins/inputs/consul/README.md
  plugins/inputs/consul/consul.go
Labels: documentation

#3941 Add support for skipping database creation
  plugins/outputs/influxdb/README.md
  plugins/outputs/influxdb/influxdb.go
Labels: area/influxdb, enhancement

#3942 Add support for connecting to InfluxDB over a unix domain socket
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb/http_test.go
  plugins/outputs/influxdb/influxdb.go
Labels: enhancement

#3947 Reconnect AMQP consumer to broker
  plugins/inputs/amqp_consumer/amqp_consumer.go
Labels: bugfix

#3949 Add TLS support to zookeeper input
  CHANGELOG.md
  plugins/inputs/zookeeper/README.md
  plugins/inputs/zookeeper/zookeeper.go
Labels: enhancement

#3950 Add filters for container state to docker input
  plugins/inputs/docker/README.md
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
Labels: area/docker, enhancement
