Repository influxdata/telegraf, pull requests merged in 2018-06, with the labels that each got.

#4219 Handle uint64 on cloudwatch output
  plugins/outputs/cloudwatch/cloudwatch.go
Labels: bugfix

#3994 Add ability to specify routing_key in amqp output
  etc/telegraf.conf
  plugins/outputs/amqp/README.md
  plugins/outputs/amqp/amqp.go
Labels: area/rabbitmq, enhancement

#3995 AMQP Consumer - Allow turning on exchange passive mode
  etc/telegraf.conf
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
Labels: area/rabbitmq, enhancement

#4225 Change config to match toml parsing rule.
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
Labels: area/configuration

#4228 Add additional amqp output/consumer input options
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
  plugins/outputs/amqp/README.md
  plugins/outputs/amqp/amqp.go
  plugins/outputs/amqp/amqp_test.go
  plugins/outputs/amqp/client.go
Labels: area/rabbitmq, enhancement

#4216 Added capture of the Counter fields from pfctl output
  plugins/inputs/pf/README.md
  plugins/inputs/pf/pf.go
  plugins/inputs/pf/pf_test.go
Labels: enhancement

#4230 Don't skip metrics during startup in aggregate phase
  agent/agent.go
  internal/models/running_aggregator.go
Labels: bugfix

#4236 Add SSL/TLS support to Redis input
  Godeps
  plugins/inputs/redis/README.md
  plugins/inputs/redis/redis.go
Labels: area/redis, enhancement

#4244 Ignore more boring filesystems from disk plugin
  etc/telegraf.conf
  etc/telegraf_windows.conf
  plugins/inputs/system/DISK_README.md
  plugins/inputs/system/disk.go
Labels: area/system, enhancement

#4241 Use same flags for all bsd family ping varients
  plugins/inputs/ping/ping.go
Labels: bugfix, platform/bsd

#4247 Fix TLS and SSL config option parsing
  Godeps
  internal/tls/config.go
  plugins/inputs/openldap/README.md
  plugins/inputs/openldap/openldap.go
  plugins/inputs/openldap/openldap_test.go
Labels: bugfix

#4255 Fix #4243
  plugins/inputs/win_perf_counters/performance_query.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
Labels: area/win_perf_counters, bugfix

#4265 Fix#4257
  plugins/inputs/win_perf_counters/README.md
  plugins/inputs/win_perf_counters/pdh.go
  plugins/inputs/win_perf_counters/performance_query.go
  plugins/inputs/win_perf_counters/win_perf_counters.go
  plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
Labels: area/win_perf_counters

#4271 Fix solr plugin for Solr 7 (Fixes #3665)
  plugins/inputs/solr/README.md
  plugins/inputs/solr/solr.go
  plugins/inputs/solr/solr_test.go
  plugins/inputs/solr/testdata7_test.go
Labels: enhancement

#4261 Fixed typos in nvidia_smi plugin doc
  plugins/inputs/nvidia_smi/README.md
Labels: documentation

#4277 Treat sigterm as a clean shutdown signal
  cmd/telegraf/telegraf.go
Labels: bugfix

#4281 Burrow: add owner tag on partitions
  plugins/inputs/burrow/README.md
  plugins/inputs/burrow/burrow.go
  plugins/inputs/burrow/burrow_test.go
  plugins/inputs/burrow/testdata/v3_kafka_clustername1_consumer_group1_lag.json
Labels: enhancement

#4284 Allow for Tags on non base level JSON format
  plugins/parsers/json/parser.go
  plugins/parsers/json/parser_test.go
Labels: bugfix

#4309 Drop CI support for Go 1.8
  .circleci/config.yml
  README.md
Labels: area/packaging

#4259 Telegraph Docker Input Plugin : per docker running status support
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker/docker_testdata.go
Labels: area/docker, enhancement

#3523 Valuecounter aggregator plugin
  README.md
  plugins/aggregators/all/all.go
  plugins/aggregators/valuecounter/README.md
  plugins/aggregators/valuecounter/valuecounter.go
  plugins/aggregators/valuecounter/valuecounter_test.go
Labels: new plugin

#4307 Bugfix/procstat adds new procstat metric about pgrep search
  internal/internal.go
  plugins/inputs/procstat/pgrep.go
  plugins/inputs/procstat/procstat.go
  plugins/inputs/procstat/procstat_test.go
Labels: area/procstat, enhancement

#4311 Add support for comma in timestamp format
  plugins/inputs/logparser/README.md
  plugins/inputs/logparser/grok/grok.go
  plugins/inputs/logparser/grok/grok_test.go
Labels: area/logparser, enhancement

#4333 fix postfix input handling multi-level queues
  CHANGELOG.md
  plugins/inputs/postfix/postfix.go
  plugins/inputs/postfix/postfix_test.go
Labels: bugfix

#4292 Added filename tag to tail input plugin.
  plugins/inputs/tail/tail.go
Labels: enhancement

#4322 logparser: add a log when tail is added or removed from a file
  plugins/inputs/logparser/logparser.go
Labels: area/logparser, enhancement

#4334 Fix syslog timestamp parsing with single digit day of month
  plugins/inputs/logparser/grok/grok.go
  plugins/inputs/logparser/grok/grok_test.go
Labels: area/logparser, bugfix

#4306 Handle variations in the user_statistics collecting
  plugins/inputs/mysql/mysql.go
Labels: area/mysql, bugfix

#4267 Use counter time in win perf counters
  plugins/inputs/win_perf_counters/README.md
  plugins/inputs/win_perf_counters/kernel32.go
  plugins/inputs/win_perf_counters/pdh.go
  plugins/inputs/win_perf_counters/performance_query.go
  plugins/inputs/win_perf_counters/win_perf_counters.go
  plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
Labels: area/win_perf_counters, enhancement

#4294 Fix minmax and basicstats aggregators to use all number types
  plugins/aggregators/basicstats/basicstats.go
  plugins/aggregators/basicstats/basicstats_test.go
  plugins/aggregators/minmax/minmax.go
  plugins/aggregators/minmax/minmax_test.go
Labels: bugfix
