Repository influxdata/telegraf, pull requests merged in 2018-05, with the labels that each got.

#4036 Fix win_perf_counters to collect counters per instance
  plugins/inputs/win_perf_counters/win_perf_counters.go
Labels: area/win_perf_counters, bugfix

#4077 Add input plugin for McRouter
  plugins/inputs/all/all.go
  plugins/inputs/mcrouter/README.md
  plugins/inputs/mcrouter/mcrouter.go
  plugins/inputs/mcrouter/mcrouter_test.go
Labels: new plugin

#4091 Fix handling of uint64 in datadog output
  plugins/outputs/datadog/datadog.go
  plugins/outputs/datadog/datadog_test.go
Labels: bugfix

#4099 Fix JSON parsing with UTF8 BOM in JSON parser plugin
  plugins/parsers/json/parser.go
  plugins/parsers/json/parser_test.go
Labels: bugfix

#4102 Fix platform not supported error
  scripts/build.py
Labels: area/packaging, bugfix

#4106 Only lowercase mysql slave metrics with metric_version = 2
  plugins/inputs/mysql/mysql.go
Labels: area/mysql, bugfix

#4107 Add SerializeBatch method to the Serializer interface
  docs/DATA_FORMATS_OUTPUT.md
  plugins/outputs/influxdb/udp_test.go
  plugins/serializers/graphite/graphite.go
  plugins/serializers/graphite/graphite_test.go
  plugins/serializers/influx/influx.go
  plugins/serializers/influx/influx_test.go
  plugins/serializers/json/json.go
  plugins/serializers/json/json_test.go
  plugins/serializers/registry.go
Labels: enhancement

#4096 TopK processor: Add topk processor plugin code
  plugins/processors/all/all.go
  plugins/processors/topk/README.md
  plugins/processors/topk/test_sets.go
  plugins/processors/topk/topk.go
  plugins/processors/topk/topk_test.go
Labels: new plugin

#4114 MongoDB: Add cursor Metrics
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#4118 Don't report 0ms on timeout in dns_query
  plugins/inputs/dns_query/README.md
  plugins/inputs/dns_query/dns_query.go
Labels: enhancement

#4117 Add uint support to cratedb output
  docker-compose.yml
  plugins/outputs/cratedb/cratedb.go
  plugins/outputs/cratedb/cratedb_test.go
Labels: bugfix

#4123 Skip fields that report "not supported" in nvidia-smi
  plugins/inputs/nvidia_smi/nvidia_smi.go
  plugins/inputs/nvidia_smi/nvidia_smi_test.go
Labels: bugfix

#4128 Update aerospike-client-go version to latest. Fix #4127.
  Godeps
Labels: bugfix

#4136 Use internal.Duration for jolokia timeouts
  plugins/inputs/jolokia2/jolokia_agent.go
  plugins/inputs/jolokia2/jolokia_proxy.go
Labels: bugfix

#4137 Reuse transport on next interval in jolokia agent
  plugins/inputs/jolokia2/jolokia_agent.go
Labels: bugfix

#2292 Service input plugin for OpenConfig streaming telemetry
  Godeps
  plugins/inputs/all/all.go
  plugins/inputs/jti_openconfig_telemetry/README.md
  plugins/inputs/jti_openconfig_telemetry/auth/authentication_service.pb.go
  plugins/inputs/jti_openconfig_telemetry/auth/authentication_service.proto
  plugins/inputs/jti_openconfig_telemetry/collection.go
  plugins/inputs/jti_openconfig_telemetry/oc/oc.pb.go
  plugins/inputs/jti_openconfig_telemetry/oc/oc.proto
  plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go
  plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry_test.go
Labels: new plugin

#4142 Fix dropwizard parsing error for metrics that need escaped
  metric.go
  metric/metric.go
  plugins/parsers/dropwizard/parser.go
  plugins/parsers/dropwizard/parser_test.go
  plugins/parsers/influx/machine.go
  plugins/parsers/influx/machine.go.rl
  plugins/parsers/influx/machine_test.go
  plugins/parsers/influx/parser.go
  plugins/parsers/influx/parser_test.go
  plugins/parsers/registry.go
Labels: bugfix

#2491 HTTP output plugin
  plugins/outputs/all/all.go
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
  plugins/outputs/http/http_test.go
Labels: enhancement, new plugin

#4151 Fix librato output support for uint and bool
  plugins/outputs/librato/librato.go
Labels: bugfix

#4010 Microsoft Application Insights output plugin
  Godeps
  plugins/outputs/all/all.go
  plugins/outputs/application_insights/README.md
  plugins/outputs/application_insights/application_insights.go
  plugins/outputs/application_insights/application_insights_test.go
  plugins/outputs/application_insights/diagnostic_message_subscriber.go
  plugins/outputs/application_insights/mocks/diagnostics_message_listener.go
  plugins/outputs/application_insights/mocks/diagnostics_message_subscriber.go
  plugins/outputs/application_insights/mocks/transmitter.go
  plugins/outputs/application_insights/transmitter.go
Labels: new plugin

#4167 Added 3 important elasticsearch cluster health metrics
  plugins/inputs/elasticsearch/elasticsearch.go
  plugins/inputs/elasticsearch/testdata_test.go
Labels: enhancement

#4094 Emqtt batch output
  etc/telegraf.conf
  plugins/outputs/mqtt/README.md
  plugins/outputs/mqtt/mqtt.go
Labels: enhancement

#4176 fix potential waitgroup lock
  plugins/inputs/apache/apache.go
Labels: bugfix

#4158 Add aurora input plugin
  plugins/inputs/all/all.go
  plugins/inputs/aurora/README.md
  plugins/inputs/aurora/aurora.go
  plugins/inputs/aurora/aurora_test.go
  testutil/accumulator.go
Labels: new plugin

#3839 Add regex processor plugin
  plugins/processors/all/all.go
  plugins/processors/regex/README.md
  plugins/processors/regex/regex.go
  plugins/processors/regex/regex_test.go
Labels: new plugin

#4165 Add support for Graphite 1.1.x protocol
  docs/DATA_FORMATS_OUTPUT.md
  plugins/outputs/graphite/README.md
  plugins/outputs/graphite/graphite.go
  plugins/outputs/graphite/graphite_test.go
  plugins/outputs/instrumental/instrumental.go
  plugins/serializers/graphite/graphite.go
  plugins/serializers/graphite/graphite_test.go
  plugins/serializers/registry.go
Labels: enhancement

#4162 Add timeout option to sensors input
  plugins/inputs/sensors/README.md
  plugins/inputs/sensors/sensors.go
  plugins/inputs/sensors/sensors_test.go
Labels: enhancement

#3489 Burrow input plugin
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/burrow/README.md
  plugins/inputs/burrow/burrow.go
  plugins/inputs/burrow/burrow_test.go
  plugins/inputs/burrow/testdata/error.json
  plugins/inputs/burrow/testdata/v3_kafka.json
  plugins/inputs/burrow/testdata/v3_kafka_clustername1_consumer.json
  plugins/inputs/burrow/testdata/v3_kafka_clustername1_consumer_group1_lag.json
  plugins/inputs/burrow/testdata/v3_kafka_clustername1_topic.json
  plugins/inputs/burrow/testdata/v3_kafka_clustername1_topic_topicA.json
Labels: new plugin

#4160 Add tengine inputs
  plugins/inputs/all/all.go
  plugins/inputs/tengine/README.md
  plugins/inputs/tengine/tengine.go
  plugins/inputs/tengine/tengine_test.go
Labels: new plugin

#3969 FP 3959 add option to unbound module to use threads as tags
  plugins/inputs/unbound/README.md
  plugins/inputs/unbound/unbound.go
  plugins/inputs/unbound/unbound_test.go
Labels: enhancement

#4183 Add support for TLS and username/password auth to aerospike input
  plugins/inputs/aerospike/README.md
  plugins/inputs/aerospike/aerospike.go
Labels: enhancement

#4178 Add converter processor
  plugins/processors/all/all.go
  plugins/processors/converter/README.md
  plugins/processors/converter/converter.go
  plugins/processors/converter/converter_test.go
Labels: new plugin

#4190 Add special syslog timestamp parser that uses current year
  plugins/inputs/logparser/README.md
  plugins/inputs/logparser/grok/grok.go
  plugins/inputs/logparser/grok/grok_test.go
Labels: enhancement

#4191 new examples for jolokia2
  plugins/inputs/jolokia2/examples/activemq.conf
  plugins/inputs/jolokia2/examples/bitbucket.conf
  plugins/inputs/jolokia2/examples/hadooop-hdfs.conf
  plugins/inputs/jolokia2/examples/jboss.conf
  plugins/inputs/jolokia2/examples/tomcat.conf
  plugins/inputs/jolokia2/examples/weblogic.conf
Labels: documentation

#4181 Syslog input plugin
  Godeps
  plugins/inputs/all/all.go
  plugins/inputs/syslog/README.md
  plugins/inputs/syslog/rfc5425_test.go
  plugins/inputs/syslog/rfc5426_test.go
  plugins/inputs/syslog/syslog.go
  plugins/inputs/syslog/syslog_test.go
Labels: new plugin

#4206 Fix for Win 32bit support in performance counters
  plugins/inputs/win_perf_counters/pdh.go
  plugins/inputs/win_perf_counters/pdh_386.go
  plugins/inputs/win_perf_counters/pdh_amd64.go
Labels: area/win_perf_counters, bugfix

#4208 fix snmp overriding of auto-configured table fields
  CHANGELOG.md
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_mocks_generate.go
  plugins/inputs/snmp/snmp_mocks_test.go
  plugins/inputs/snmp/snmp_test.go
  plugins/inputs/snmp/testdata/test.mib
Labels: bugfix

#4212 Print the enabled aggregator and processor plugins on startup
  cmd/telegraf/telegraf.go
  internal/config/config.go
Labels: enhancement
