Repository influxdata/telegraf, pull requests merged in 2018-12, with the labels that each got.

#5118 Prevent panic when marking the offset
  plugins/inputs/kafka_consumer/kafka_consumer.go
Labels: area/kafka, bugfix

#5085 Aggregate early metrics, rather than ignore
  internal/models/running_aggregator.go
  internal/models/running_aggregator_test.go
Labels: bugfix

#5054 Improve docs to clarify common issues
  plugins/inputs/jolokia2/examples/java.conf
  plugins/inputs/logparser/README.md
  plugins/inputs/logparser/grok/patterns/influx-patterns
  plugins/inputs/logparser/logparser_test.go
  plugins/inputs/logparser/testdata/test-patterns
  plugins/inputs/logparser/testdata/test_a.log
  plugins/inputs/logparser/testdata/test_b.log
  plugins/inputs/redis/README.md
  plugins/inputs/win_perf_counters/README.md
  plugins/parsers/grok/README.md
  plugins/parsers/grok/influx_patterns.go
  plugins/parsers/json/README.md
  plugins/processors/enum/README.md
Labels: documentation

#5112 Fixed ping plugin under bsd variants.
  plugins/inputs/ping/ping.go
Labels: bugfix

#5115 stop Wavefront parser rejecting delta metrics
  plugins/parsers/wavefront/element.go
  plugins/parsers/wavefront/parser_test.go
  plugins/parsers/wavefront/scanner.go
  plugins/parsers/wavefront/token.go
Labels: area/wavefront, enhancement

#5069 Add running field to procstat_lookup
  agent/accumulator.go
  plugins/inputs/procstat/README.md
  plugins/inputs/procstat/procstat.go
Labels: enhancement

#5074 Add support for sending a request body to http input
  plugins/inputs/http/README.md
  plugins/inputs/http/http.go
  plugins/inputs/http/http_test.go
Labels: enhancement

#5135 Issue 5132 & 5067
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix, performance

#5116 Include DEVLINKS in available diskio udev properties
  plugins/inputs/diskio/README.md
  plugins/inputs/diskio/diskio_linux.go
  plugins/inputs/diskio/diskio_linux_test.go
Labels: enhancement

#5083 Fix translate empty tag values
  plugins/outputs/azure_monitor/azure_monitor.go
Labels: bugfix, platform/windows

#5146 Fix Converter Processor Example
  plugins/processors/converter/README.md
Labels: documentation

#5144 Run stop logic only if required
  plugins/inputs/prometheus/prometheus.go
Labels: bugfix

#5149 Add micro and nanosecond unix timestamp support to JSON parser
  plugins/parsers/json/README.md
  plugins/parsers/json/parser.go
Labels: enhancement

#5148 Non-transparent transport of syslog messages
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/syslog/README.md
  plugins/inputs/syslog/commons_test.go
  plugins/inputs/syslog/framing.go
  plugins/inputs/syslog/framing_test.go
  plugins/inputs/syslog/nontransparent_test.go
  plugins/inputs/syslog/octetcounting_test.go
  plugins/inputs/syslog/rfc5426_test.go
  plugins/inputs/syslog/syslog.go
Labels: area/syslog

#5158 Fix invalid JSON
  plugins/parsers/json/README.md
Labels: documentation

#5152 Apply global and plugin level metric modifications before filtering
  internal/models/running_input.go
  internal/models/running_input_test.go
Labels: bugfix

#5145 Optimization : globpath using godirwalk
  internal/globpath/globpath.go
  internal/globpath/globpath_test.go
  plugins/inputs/file/file.go
  plugins/inputs/filestat/filestat.go
  plugins/inputs/logparser/logparser.go
  plugins/inputs/tail/tail.go
Labels: enhancement

#5160 Add support for basic auth in couchdb input
  plugins/inputs/couchdb/README.md
  plugins/inputs/couchdb/couchdb.go
Labels: enhancement

#5167 Fix typos in ceph input plugin
  plugins/inputs/ceph/ceph.go
  plugins/inputs/ceph/ceph_test.go
Labels: bugfix

#5182 Add PDH_NO_DATA to known counter error codes
  plugins/inputs/win_perf_counters/win_perf_counters.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
Labels: bugfix

#5169 Signal telegraf process until it exits
  agent/agent.go
  scripts/init.sh
Labels: area/packaging, bugfix

#5176 Deliver empty metric tracking group immediately
  agent/accumulator_test.go
  metric/tracking.go
Labels: bugfix

#5168 Allow floats in valuecounter aggregator.
  plugins/aggregators/valuecounter/README.md
  plugins/aggregators/valuecounter/valuecounter.go
  plugins/aggregators/valuecounter/valuecounter_test.go
Labels: enhancement

#5195 Fix usage of loop variable in function closure
  plugins/processors/strings/strings.go
  plugins/processors/strings/strings_test.go
Labels: bugfix

#5200 Improve config file environment variable documentation
  docs/CONFIGURATION.md
Labels: documentation

#5177 Add forwarded records to sqlserver input
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, enhancement
