Repository influxdata/telegraf, pull requests merged in 2018-09, with the labels that each got.

#4572 Fix instance and object name in performance counters with backslashes
  plugins/inputs/win_perf_counters/win_perf_counters.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
Labels: area/win_perf_counters, bugfix

#4635 Corrected application insights example config
  plugins/outputs/application_insights/README.md
  plugins/outputs/application_insights/application_insights.go
Labels: documentation, enhancement

#4628 add queue_durability property to amqp_consumer input
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
Labels: area/rabbitmq, enhancement

#4089 Add Azure Monitor output plugin
  Gopkg.lock
  Gopkg.toml
  docs/LICENSE_OF_DEPENDENCIES.md
  internal/models/running_output.go
  output.go
  plugins/outputs/all/all.go
  plugins/outputs/azure_monitor/README.md
  plugins/outputs/azure_monitor/azure_monitor.go
  plugins/outputs/azure_monitor/azure_monitor_test.go
  plugins/parsers/logfmt/parser_test.go
  testutil/metric.go
  testutil/metric_test.go
Labels: new plugin

#4476 re-worked lowercase into a generic strings processor
  plugins/processors/all/all.go
  plugins/processors/strings/README.md
  plugins/processors/strings/strings.go
  plugins/processors/strings/strings_test.go
Labels: new plugin

#4536 Oauth2 support in HTTP output plugin
  Gopkg.lock
  Gopkg.toml
  docs/LICENSE_OF_DEPENDENCIES.md
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
  plugins/outputs/http/http_test.go
Labels: enhancement

#4272 Add Beanstalkd input plugin
  plugins/inputs/all/all.go
  plugins/inputs/beanstalkd/README.md
  plugins/inputs/beanstalkd/beanstalkd.go
  plugins/inputs/beanstalkd/beanstalkd_test.go
Labels: new plugin

#4411 Add temp inputs plugin for collect temperature
  plugins/inputs/all/all.go
  plugins/inputs/system/mock_PS.go
  plugins/inputs/system/ps.go
  plugins/inputs/temp/README.md
  plugins/inputs/temp/temp.go
  plugins/inputs/temp/temp_test.go
Labels: new plugin

#4656 Fix parsing and documentation for json_string_fields
  docs/DATA_FORMATS_INPUT.md
  internal/config/config.go
Labels: bugfix

#4657 Add options for basic auth to haproxy input
  plugins/inputs/haproxy/haproxy.go
Labels: enhancement

#4669 Add means to specify server password for redis input
  plugins/inputs/redis/redis.go
Labels: bugfix

#4659 Added Zookeeper Jolokia2 Config
  plugins/inputs/jolokia2/README.md
  plugins/inputs/jolokia2/examples/zookeeper.conf
Labels: documentation, enhancement

#4339 Splunk Metrics serializer
  docs/DATA_FORMATS_OUTPUT.md
  internal/config/config.go
  plugins/serializers/registry.go
  plugins/serializers/splunkmetric/README.md
  plugins/serializers/splunkmetric/splunkmetric.go
  plugins/serializers/splunkmetric/splunkmetric_test.go
Labels: new plugin

#4141 Added input plugin for VMware vSphere.
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/all/all.go
  plugins/inputs/vsphere/METRICS.MD
  plugins/inputs/vsphere/README.MD
  plugins/inputs/vsphere/client.go
  plugins/inputs/vsphere/endpoint.go
  plugins/inputs/vsphere/selfhealth.go
  plugins/inputs/vsphere/vsphere.go
  plugins/inputs/vsphere/vsphere_test.go
  plugins/inputs/vsphere/workerpool.go
Labels: new plugin

#4667 Align metrics windows to gather interval for cloudwatch input
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
Labels: enhancement

#4674 Log access denied opening a service at debug level
  plugins/inputs/win_services/README.md
  plugins/inputs/win_services/win_services.go
  plugins/inputs/win_services/win_services_integration_test.go
Labels: bugfix

#4642 Updates to SQL Server Plugin, better Azure Managed Instance support + more
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, enhancement

#4654 Add support for couchdb 2.0+ API
  plugins/inputs/couchdb/README.md
  plugins/inputs/couchdb/couchdb.go
  plugins/inputs/couchdb/couchdb_test.go
  plugins/inputs/couchdb/dev/telegraf.conf
Labels: bugfix

#4684 Fixed minor bug that caused error messages in vCenter log
  plugins/inputs/vsphere/client.go
Labels: bugfix

#4676 Bump sarama to version 1.18.0 to support Kafka 2.0
  Gopkg.lock
  Gopkg.toml
Labels: area/kafka, enhancement

#4682 Allow alternate binaries for "iptables" input plugin.
  etc/telegraf.conf
  plugins/inputs/iptables/README.md
  plugins/inputs/iptables/iptables.go
Labels: enhancement

#4645 Add influx2.0 output plugin
  plugins/outputs/all/all.go
  plugins/outputs/influxdb_v2/README.md
  plugins/outputs/influxdb_v2/http.go
  plugins/outputs/influxdb_v2/http_internal_test.go
  plugins/outputs/influxdb_v2/http_test.go
  plugins/outputs/influxdb_v2/influxdb.go
  plugins/outputs/influxdb_v2/influxdb_test.go
Labels: new plugin

#4690 Split parser/serializer docs
  README.md
  docs/DATA_FORMATS_INPUT.md
  docs/DATA_FORMATS_OUTPUT.md
  docs/METRICS.md
  docs/README.md
  docs/TEMPLATE_PATTERN.md
  plugins/inputs/statsd/README.md
  plugins/inputs/statsd/statsd.go
  plugins/parsers/EXAMPLE_README.md
  plugins/parsers/collectd/README.md
  plugins/parsers/csv/README.md
  plugins/parsers/dropwizard/README.md
  plugins/parsers/graphite/README.md
  plugins/parsers/grok/README.md
  plugins/parsers/influx/README.md
  plugins/parsers/json/README.md
  plugins/parsers/logfmt/README.md
  plugins/parsers/nagios/README.md
  plugins/parsers/value/README.md
  plugins/parsers/wavefront/README.md
  plugins/serializers/EXAMPLE_README.md
  plugins/serializers/graphite/README.md
  plugins/serializers/influx/README.md
  plugins/serializers/json/README.md
  plugins/serializers/splunkmetric/README.md
Labels: documentation

#2036 AWS Metadata Processor Plugins
  Godeps
  README.md
  plugins/processors/all/all.go
  plugins/processors/aws/README.md
  plugins/processors/aws/ec2/README.md
  plugins/processors/aws/ec2/ec2.go
  plugins/processors/aws/ec2/ec2_test.go
  plugins/processors/aws/elb/README.md
  plugins/processors/aws/elb/elb.go
  plugins/processors/aws/elb/elb_test.go
  plugins/processors/aws/rds/README.md
  plugins/processors/aws/rds/rds.go
  plugins/processors/aws/rds/rds_test.go
  plugins/processors/aws/sqs/README.md
  plugins/processors/aws/sqs/sqs.go
  plugins/processors/aws/sqs/sqs_test.go
  plugins/processors/aws/utils/utils.go
Labels: enhancement, new plugin

#4695 Remove the startup authentication check from the cloudwatch output.
  plugins/outputs/cloudwatch/cloudwatch.go
Labels: area/aws, bugfix

#4689 Fix null value crash in postgresql_extensible input
  plugins/inputs/postgresql_extensible/postgresql_extensible.go
  plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
Labels: bugfix

#4691 Enhance performance data for nagios parser
  plugins/parsers/nagios/parser.go
  plugins/parsers/nagios/parser_test.go
Labels: bugfix

#4721 Cleanup Ceph Input Plugin
  plugins/inputs/ceph/ceph.go
  plugins/inputs/ceph/ceph_test.go
Labels: area/ceph, enhancement

#4730 Forwarded Records and Offline
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix

#4728 Fix rune conversion in csv parser
  plugins/parsers/registry.go
Labels: bugfix

#4724 Add readme note about docker socket permissions
  plugins/inputs/docker/README.md
Labels: documentation, enhancement

#4735 Fix panic if JSONNameKey is not found
  plugins/parsers/json/README.md
  plugins/parsers/json/parser.go
Labels: bugfix

#4739 Clarify monitoring backend provenance
  plugins/inputs/openldap/README.md
Labels: documentation

#4750 String or Binary data will be truncated
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix

#4756 Clarify platform support for temp input
  plugins/inputs/temp/README.md
  plugins/inputs/temp/temp.go
Labels: documentation, enhancement

#4741 Use FieldList in basicstats to improve performance
  plugins/aggregators/basicstats/basicstats.go
Labels: performance

#4702 use less goroutine and memory while executing multiple cmds at once
  internal/internal.go
Labels: performance

#4747 Add hostname to TLS config for SNI support
  plugins/inputs/x509_cert/x509_cert.go
Labels: enhancement

#4686 String replacer function to strings plugin
  plugins/processors/strings/README.md
  plugins/processors/strings/strings.go
  plugins/processors/strings/strings_test.go
Labels: enhancement

#4765 Fixed #4764 (Panic when error during call to GetAvailableMetrics)
  plugins/inputs/vsphere/endpoint.go
Labels: bugfix

#4753 Define custom name/display name when installing telegraf as a windows service
  cmd/telegraf/telegraf.go
  docs/WINDOWS_SERVICE.md
  internal/usage_windows.go
Labels: enhancement
