Repository influxdata/telegraf, pull requests merged in 2018-04, with the labels that each got.

#3954 Add metric_version option to mysql input
  CHANGELOG.md
  plugins/inputs/mysql/README.md
  plugins/inputs/mysql/mysql.go
  plugins/inputs/mysql/v1/mysql.go
Labels: bugfix, documentation

#3960 Fix parsing of dos line endings in smart input
  plugins/inputs/smart/smart.go
Labels: bugfix

#3961 Fix precision truncation when no timestamp included
  metric/builder.go
  plugins/inputs/http_listener/http_listener.go
  plugins/inputs/http_listener/http_listener_test.go
  plugins/parsers/influx/handler.go
  plugins/parsers/influx/parser_test.go
Labels: bugfix

#3962 Fix bug preventing database from being recreated
  plugins/outputs/influxdb/influxdb.go
  plugins/outputs/influxdb/influxdb_test.go
Labels: bugfix

#3976 Fixing https urls in Influxdb Output Plugin
  plugins/outputs/influxdb/http.go
Labels: area/influxdb, bugfix

#3978 Fix conversion of unsigned ints in prometheus output
  plugins/outputs/prometheus_client/prometheus_client.go
  plugins/outputs/prometheus_client/prometheus_client_test.go
Labels: area/prometheus, bugfix, regression

#3981 Export all vars defined in /etc/default/telegraf
  scripts/init.sh
Labels: area/packaging

#3980 Use explicit casts to avoid datatype issues
  plugins/inputs/sqlserver/sqlserver.go
Labels: bugfix

#3964 Add repl_oplog_window_s metric to mongodb input
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongodb_server.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#3992 Fix newline escaping in line protocol
  plugins/parsers/influx/machine.go
  plugins/parsers/influx/machine.go.rl
  plugins/parsers/influx/machine_test.go
  plugins/serializers/influx/escape.go
  plugins/serializers/influx/influx_test.go
Labels: bugfix

#3819 Add per-host shard metrics if configured
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongodb_server.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#2741 Add Fibaro input plugin
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/fibaro/README.md
  plugins/inputs/fibaro/fibaro.go
  plugins/inputs/fibaro/fibaro_test.go
Labels: enhancement, new plugin, triage

#4005 Allow grok pattern to contain newlines
  plugins/inputs/logparser/grok/grok.go
  plugins/inputs/logparser/grok/grok_test.go
Labels: bugfix

#3993 Add --console and --service to usage message in Windows
  cmd/telegraf/telegraf.go
  cmd/telegraf/usage.go
  cmd/telegraf/usage_windows.go
Labels: documentation

#3999 Prevent loading config twice in K8S
  internal/config/config.go
  internal/config/testdata/subconfig/..4984_10_04_08_28_06.119/invalid-config.conf
Labels: area/configuration, enhancement

#4034 Update mem values to gauge
  plugins/inputs/system/memory.go
Labels: bugfix

#4021 Add TLS support to socket_writer and socket_listener plugins
  internal/internal.go
  plugins/inputs/socket_listener/README.md
  plugins/inputs/socket_listener/socket_listener.go
  plugins/inputs/socket_listener/socket_listener_test.go
  plugins/inputs/socket_listener/testdata/ca.pem
  plugins/inputs/socket_listener/testdata/client.key
  plugins/inputs/socket_listener/testdata/client.pem
  plugins/inputs/socket_listener/testdata/server.key
  plugins/inputs/socket_listener/testdata/server.pem
  plugins/outputs/socket_writer/README.md
  plugins/outputs/socket_writer/socket_writer.go
Labels: enhancement

#4025 Snmp strip components
  plugins/inputs/snmp/README.md
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
Labels: area/snmp, enhancement

#4033 Fix graphite serialization of unsigned ints
  plugins/serializers/graphite/graphite.go
  plugins/serializers/graphite/graphite_test.go
Labels: bugfix

#4042 Update github.com/gorilla/mux version
  Godeps
Labels: enhancement

#4043 Report available fields if utmp is unreadable
  plugins/inputs/system/SYSTEM_README.md
  plugins/inputs/system/system.go
Labels: bugfix

#4048 Add only valid field types in cassandra input
  plugins/inputs/cassandra/cassandra.go
Labels: bugfix

#4045 Update gopsutils to fix #4037
  Godeps
Labels: bugfix

#4054 Fix ints being capped at 32-bits on 32-bit archs
  plugins/parsers/influx/parser_test.go
  plugins/serializers/influx/influx.go
  plugins/serializers/influx/influx_test.go
Labels: bugfix

#4056 Fix duplicate tags when overriding tag
  metric/metric.go
  metric/metric_test.go
Labels: bugfix, regression

#4062 Since unbound 1.7 the `-s` argument must come first
  plugins/inputs/unbound/unbound.go
Labels: bugfix

#4066 Return errors in mongodb SSL/TLS configuration
  plugins/inputs/mongodb/mongodb.go
Labels: area/mongodb, bugfix

#4065 Fix handling of floats with multiple leading zeroes
  plugins/parsers/influx/machine.go
  plugins/parsers/influx/machine.go.rl
  plugins/parsers/influx/machine_test.go
Labels: bugfix

#4050 Deprecate the cassandra input plugin
  CHANGELOG.md
  README.md
  plugins/inputs/cassandra/README.md
  plugins/inputs/cassandra/cassandra.go
  plugins/inputs/jolokia2/README.md
  plugins/inputs/jolokia2/examples/cassandra.conf
  plugins/inputs/jolokia2/jolokia_proxy.go
Labels: documentation

#4055 Fix one writer failing others in file output
  plugins/outputs/file/file.go
Labels: bugfix

#4035 Add docker input server version
  plugins/inputs/docker/README.md
  plugins/inputs/docker/client.go
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker/docker_testdata.go
  testutil/accumulator.go
Labels: area/docker, enhancement

#4044 [plugin/input/leofs] Modified for LeoFS v1.4
  plugins/inputs/leofs/README.md
  plugins/inputs/leofs/leofs.go
  plugins/inputs/leofs/leofs_test.go
Labels: area/snmp, enhancement

#4068 New parameter to force the interval of gather for sysstat
  plugins/inputs/sysstat/sysstat.go
Labels: enhancement

#4078 agent/accumulator: expose GetTime to give input plugins a chance to r…
  plugins/inputs/system/system.go
Labels: bugfix
