Repository influxdata/telegraf, pull requests merged in 2018-10, with the labels that each got.

#4766 Unify http_listener error response with influxdb
  plugins/inputs/http_listener/http_listener.go
Labels: bugfix

#4785 Skip tags with empty values
  plugins/outputs/cloudwatch/cloudwatch.go
  plugins/outputs/cloudwatch/cloudwatch_test.go
Labels: area/aws, bugfix

#4791 Fixed issue 4783 (Non-realtime samples missing)
  plugins/inputs/vsphere/client.go
  plugins/inputs/vsphere/endpoint.go
Labels: area/vsphere, bugfix

#4799 Fix case of timezone/grok_timezone options.
  internal/config/config.go
  plugins/inputs/logparser/logparser.go
  plugins/parsers/registry.go
Labels: bugfix

#4806 Fix contributing guidelines
  CONTRIBUTING.md
Labels: documentation, hacktoberfest

#4811 Procstat plugin add win_service option to lookup the specified service process pid
  plugins/inputs/procstat/README.md
  plugins/inputs/procstat/procstat.go
  plugins/inputs/procstat/win_service_notwindows.go
  plugins/inputs/procstat/win_service_windows.go
Labels: area/procstat, enhancement

#4752 Per-directory file counts in the Filecount plugin
  plugins/inputs/filecount/filecount.go
  plugins/inputs/filecount/filecount_test.go
Labels: enhancement

#4803 #4699 Improve how the datadog plugin uses Metric.Fields and Metric.Tags
  plugins/outputs/datadog/datadog.go
  plugins/outputs/datadog/datadog_test.go
Labels: performance

#4807 Implement HTTP Output Compression
  internal/internal.go
  internal/internal_test.go
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
  plugins/outputs/http/http_test.go
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb_v2/http.go
Labels: enhancement, hacktoberfest

#4818 Fix formatting in net plugin docs
  plugins/inputs/net/NET_README.md
Labels: documentation

#4819 Windows bin_path
  plugins/inputs/nvidia_smi/README.md
Labels: documentation, enhancement

#4828 Issue #3911: Expose telegraf agent version in internal module
  cmd/telegraf/telegraf.go
  internal/internal.go
  internal/internal_test.go
Labels: enhancement

#4844 Update write path to match updated v2 API
  plugins/outputs/influxdb_v2/http.go
  plugins/outputs/influxdb_v2/http_internal_test.go
Labels: bugfix

#4847 Document that taginclude/tagexclude can remove ANY tag
  docs/CONFIGURATION.md
Labels: documentation

#4841 Fix hang in dns_query plugin
  plugins/inputs/dns_query/dns_query.go
Labels: bugfix

#4793 Add a Dockerfile that matches influxdata-docker to build images from source
  Dockerfile
  Dockerfile.alpine
  docker/entrypoint.sh
Labels: area/docker

#4842 Report timeout as error in dns_query plugin
  plugins/inputs/dns_query/dns_query_test.go
Labels: bugfix

#4840 Implemented timeouts
  plugins/inputs/vsphere/client.go
  plugins/inputs/vsphere/endpoint.go
  plugins/inputs/vsphere/vsphere_test.go
Labels: area/vsphere, enhancement

#4788 Enhancement of README.md for the vSphere input plugin.
  plugins/inputs/vsphere/README.md
Labels: documentation, enhancement

#4755 Add http_listener_v2 input plugin (supports multiple data formats)
  plugins/inputs/all/all.go
  plugins/inputs/http_listener_v2/README.md
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
  plugins/inputs/http_listener_v2/testdata/testmsgs.gz
Labels: new plugin

#4854 Use container name from list if no name in container stats
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
Labels: bugfix

#4851 Add support for uint fields in aerospike input
  plugins/inputs/aerospike/aerospike.go
  plugins/inputs/aerospike/aerospike_test.go
Labels: bugfix

#4850 Prevent panic if fileinfo is nil
  plugins/inputs/filecount/filecount.go
Labels: bugfix

#4836 Optimization for globpath (root elements for recursion)
  internal/globpath/globpath.go
  internal/globpath/globpath_test.go
Labels: enhancement

#4846 Rework mqtt_consumer connect/reconnect
  plugins/inputs/mqtt_consumer/mqtt_consumer.go
  plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
Labels: area/mqtt, bugfix

#4875 On host not available, set result_code accordingly
  plugins/inputs/ping/README.md
  plugins/inputs/ping/ping.go
Labels: bugfix

#4874 Fix segfault in x509_cert
  plugins/inputs/x509_cert/README.md
  plugins/inputs/x509_cert/dev/telegraf.conf
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: bugfix

#4763 Add more detailed description for swap fields
  plugins/inputs/swap/README.md
Labels: documentation

#4864 Improve AWS Kinesis IAM Security
  Gopkg.lock
  Gopkg.toml
  plugins/outputs/kinesis/kinesis.go
Labels: enhancement

#4873 Add certificate subject as a tag
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: enhancement

#4852 Feature : size options can come with units (KB, MiB, ...)
  internal/internal.go
  internal/internal_test.go
  plugins/inputs/filecount/README.md
  plugins/inputs/filecount/filecount.go
  plugins/inputs/filecount/filecount_test.go
  plugins/inputs/http_listener_v2/README.md
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
  plugins/inputs/influxdb_listener/http_listener.go
  plugins/inputs/influxdb_listener/http_listener_test.go
  plugins/inputs/socket_listener/README.md
  plugins/inputs/socket_listener/socket_listener.go
  plugins/inputs/socket_listener/socket_listener_test.go
  plugins/outputs/influxdb/README.md
  plugins/outputs/influxdb/influxdb.go
  plugins/outputs/influxdb/influxdb_test.go
Labels: enhancement

#4837 Nginx Plus API plugin
  plugins/inputs/all/all.go
  plugins/inputs/nginx_plus_api/README.md
  plugins/inputs/nginx_plus_api/nginx_plus_api.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics_test.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_types.go
Labels: new plugin

#3903 Add support for TLS configuration in NSQ input to reach HTTPS nsqd endpoints
  plugins/inputs/nsq/nsq.go
  plugins/inputs/nsq/nsq_test.go
Labels: enhancement

#4914 Memcached plugin addtional metrics to collect added
  plugins/inputs/memcached/README.md
  plugins/inputs/memcached/memcached.go
Labels: enhancement

#4890 IPVS input plugin
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/all/all.go
  plugins/inputs/ipvs/README.md
  plugins/inputs/ipvs/ipvs.go
  plugins/inputs/ipvs/ipvs_notlinux.go
Labels: area/k8s, new plugin

#4924 Prevent connection leak by closing unused connections in amqp output
  plugins/outputs/amqp/amqp.go
  plugins/outputs/amqp/client.go
Labels: bugfix

#4904 Set defaults on kinesis output partition key when tag does not exist.
  plugins/outputs/kinesis/README.md
  plugins/outputs/kinesis/kinesis.go
  plugins/outputs/kinesis/kinesis_test.go
Labels: bugfix

#3847 Add Wireless Input plugin
  plugins/inputs/all/all.go
  plugins/inputs/wireless/README.md
  plugins/inputs/wireless/wireless.go
  plugins/inputs/wireless/wireless_linux.go
  plugins/inputs/wireless/wireless_test.go
Labels: new plugin

#4937 Handle panic when ipmi_sensor input gets bad input
  plugins/inputs/ipmi_sensor/ipmi.go
  plugins/inputs/ipmi_sensor/ipmi_test.go
Labels: bugfix

#4930 Don't add unserializable fields
  plugins/inputs/jolokia2/examples/zookeeper.conf
  plugins/inputs/jolokia2/jolokia_test.go
  plugins/inputs/jolokia2/point_builder.go
Labels: bugfix

#4866 postgresql_extensible: fix DB version check for version 10+
  plugins/inputs/postgresql_extensible/postgresql_extensible.go
Labels: enhancement, hacktoberfest
