Repository influxdata/telegraf, pull requests merged in 2019-03, with the labels that each got.

#5509 Listen before returning from returning from Connect
  plugins/outputs/prometheus_client/prometheus_client.go
Labels: bugfix

#5508 Ignore tracking for metrics added to aggregator
  internal/models/running_aggregator.go
  metric/metric.go
Labels: bugfix

#5512 Handle errors better in prometheus output
  plugins/outputs/prometheus_client/prometheus_client.go
Labels: area/prometheus, bugfix

#5518 Fix conversion from string float to integer
  plugins/processors/converter/converter.go
  plugins/processors/converter/converter_test.go
Labels: bugfix

#5524 Fix panic when rejecting empty batch
  internal/models/buffer.go
  internal/models/buffer_test.go
Labels: bugfix

#5515 Add a link to x509_cert plugin in the README.
  README.md
Labels: documentation

#5525 Dereference pointer fields in metrics
  metric/metric.go
Labels: bugfix

#5533 Allow grok to produce metrics with no fields
  plugins/parsers/grok/parser.go
  plugins/parsers/grok/parser_test.go
  plugins/parsers/registry.go
Labels: enhancement

#5534 Sort metrics by timestamp in prometheus output
  plugins/outputs/prometheus_client/prometheus_client.go
Labels: bugfix

#5543 Base64-encoding/decoding parameters for Google Cloud PubSub plugins
  plugins/inputs/cloud_pubsub/README.md
  plugins/inputs/cloud_pubsub/pubsub.go
  plugins/inputs/cloud_pubsub/pubsub_test.go
  plugins/outputs/cloud_pubsub/README.md
  plugins/outputs/cloud_pubsub/pubsub.go
  plugins/outputs/cloud_pubsub/pubsub_test.go
  plugins/outputs/cloud_pubsub/topic_stubbed.go
Labels: enhancement

#5541 Return error creating tls config
  plugins/inputs/socket_listener/socket_listener.go
Labels: bugfix

#5552 Update gopsutil to v2.19.02
  Gopkg.lock
Labels: bugfix

#5558 Fix links and add config to webhook readme
  plugins/inputs/webhooks/README.md
  plugins/inputs/webhooks/filestack/README.md
  plugins/inputs/webhooks/mandrill/README.md
  plugins/inputs/webhooks/particle/README.md
  plugins/inputs/webhooks/rollbar/README.md
  plugins/inputs/webhooks/webhooks.go
Labels: documentation

#5556 Input Plugin: Adding TTL field for Ping plugin
  plugins/inputs/ping/README.md
  plugins/inputs/ping/ping.go
  plugins/inputs/ping/ping_test.go
Labels: enhancement

#5555 Use random available port in prometheus output tests
  plugins/outputs/prometheus_client/prometheus_client.go
  plugins/outputs/prometheus_client/prometheus_client_tls_test.go
Labels: bugfix

#5557 Removed calls to destroy on ViewManager
  plugins/inputs/vsphere/finder.go
Labels: area/vsphere

#5569 Add conversion between a string hexadecimal value and integer
  plugins/processors/converter/converter.go
  plugins/processors/converter/converter_test.go
Labels: enhancement

#5577 Use valid measurement names in csv parser
  plugins/parsers/csv/parser.go
Labels: bugfix

#5592 Decrease CPU usage in system input
  plugins/inputs/system/system.go
Labels: area/system, bugfix

#5575 Don't add empty healthcheck tags to consul input
  plugins/inputs/consul/consul.go
Labels: bugfix

#5612 Fix deadlock when Telegraf is aligning aggregators
  agent/agent.go
Labels: bugfix

#5540 Fix open error handling in file output
  agent/agent.go
  internal/models/running_output.go
  plugins/outputs/file/file.go
Labels: bugfix

#5608 Remove string trimming from grok parser
  plugins/parsers/grok/influx_patterns.go
  plugins/parsers/grok/parser.go
  plugins/parsers/grok/parser_test.go
Labels: area/grok, bugfix

#5607 Add owned directories to rpm package
  scripts/build.py
Labels: area/packaging, bugfix

#5566 [inputs/diskio] Fix how major and minor identifiers of block devices are read.
  plugins/inputs/diskio/diskio_linux.go
Labels: bugfix

#5601 Fix nagios parser to parse all perfdata and report info message.
  plugins/inputs/exec/exec.go
  plugins/inputs/exec/exec_test.go
  plugins/parsers/nagios/parser.go
  plugins/parsers/nagios/parser_test.go
Labels: enhancement

#5632 Fix aggregator metric drop
  agent/agent.go
  docker-compose.yml
Labels: bugfix

#5627 Fix plugin name in influxdb_v2 output
  plugins/outputs/influxdb_v2/influxdb.go
Labels: bugfix

#5628 Listen before leaving start in statsd
  plugins/inputs/statsd/statsd.go
Labels: area/statsd, bugfix

#5630 Fix basedir check and parent dir extraction in filecount input
  plugins/inputs/filecount/filecount.go
Labels: bugfix

#5631 Exit after running --test without requiring --console
  cmd/telegraf/telegraf.go
Labels: area/agent, platform/windows

#5644 Fix aggregator window and shutdown of multiple aggregators
  accumulator.go
  agent/accumulator.go
  agent/accumulator_test.go
  agent/agent.go
  agent/agent_test.go
  internal/internal.go
  internal/internal_test.go
  internal/models/running_aggregator.go
  internal/models/running_aggregator_test.go
  testutil/accumulator.go
Labels: area/agent, bugfix

#5648 Add support for ${} env vars in configuration file
  docs/CONFIGURATION.md
  internal/config/config.go
  internal/config/config_test.go
  internal/config/testdata/single_plugin_env_vars.toml
Labels: area/configuration, enhancement
