Repository influxdata/telegraf, pull requests merged in 2019-05, with the labels that each got.

#5770 Add --service-display-name option for use with Windows service
  cmd/telegraf/telegraf.go
  internal/usage_windows.go
Labels: enhancement, platform/windows

#5759 syslog output plugin
  internal/syslog/framing.go
  internal/syslog/framing_test.go
  plugins/inputs/syslog/commons_test.go
  plugins/inputs/syslog/nontransparent_test.go
  plugins/inputs/syslog/octetcounting_test.go
  plugins/inputs/syslog/syslog.go
  plugins/outputs/syslog/README.md
  plugins/outputs/syslog/framing.go
  plugins/outputs/syslog/framing_test.go
  plugins/outputs/syslog/syslog.go
  plugins/outputs/syslog/syslog_mapper.go
  plugins/outputs/syslog/syslog_mapper_test.go
  plugins/outputs/syslog/syslog_test.go
Labels: new plugin

#5786 Update cloudwatch input readme with getMetricData command
  plugins/inputs/cloudwatch/README.md
Labels: area/aws, documentation

#5792 Buffer metrics from failed writes in influxdb2 output if token is invalid
  plugins/outputs/influxdb_v2/http.go
  plugins/outputs/influxdb_v2/influxdb.go
Labels: area/influxdb, bugfix

#5797 Add missing quote
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch.go
Labels: bugfix

#5778 Log rotation
  cmd/telegraf/telegraf.go
  docs/CONFIGURATION.md
  internal/config/config.go
  internal/rotate/file_writer.go
  internal/rotate/file_writer_test.go
  logger/logger.go
  logger/logger_test.go
Labels: area/agent, enhancement

#5810 Set host header if configured on http output
  plugins/outputs/http/http.go
Labels: bugfix

#5800 Add iso6990 to telegraf disk ignore_fs
  plugins/inputs/disk/README.md
  plugins/inputs/disk/disk.go
Labels: enhancement

#5771 Fixed an issue in the lustre input polgin with the jobstats only being reporeted for one job per storage target
  plugins/inputs/lustre2/lustre2.go
  plugins/inputs/lustre2/lustre2_test.go
Labels: bugfix

#5726 Fixed interval estimation issues
  plugins/inputs/vsphere/endpoint.go
Labels: area/vsphere, bugfix

#5814 Require github.com/jackc/pgx v3.4.0
  Gopkg.lock
  Gopkg.toml
Labels: bugfix

#5813 Set default timeout of 5s in fibaro input
  plugins/inputs/fibaro/fibaro.go
Labels: bugfix

#5782 Skip lines with missing refid and other fields
  plugins/inputs/ntpq/ntpq.go
  plugins/inputs/ntpq/ntpq_test.go
Labels: bugfix

#5765 Update smart input plugin to support more drive types
  plugins/inputs/smart/README.md
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: area/smart, bugfix

#5816 Fix/ipmi status codes
  plugins/inputs/ipmi_sensor/ipmi.go
  plugins/inputs/ipmi_sensor/ipmi_test.go
Labels: bugfix

#5802 Javicrespo syslog output
  internal/syslog/framing.go
  internal/syslog/framing_test.go
  plugins/inputs/syslog/commons_test.go
  plugins/inputs/syslog/nontransparent_test.go
  plugins/inputs/syslog/octetcounting_test.go
  plugins/inputs/syslog/syslog.go
  plugins/outputs/all/all.go
  plugins/outputs/syslog/README.md
  plugins/outputs/syslog/syslog.go
  plugins/outputs/syslog/syslog_mapper.go
  plugins/outputs/syslog/syslog_mapper_test.go
  plugins/outputs/syslog/syslog_test.go
Labels: new plugin

#5832 fr5829 solr auth
  plugins/inputs/solr/README.md
  plugins/inputs/solr/solr.go
Labels: enhancement

#5826 Fix parse of unix timestamp with more than ns precision
  internal/internal.go
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
Labels: bugfix

#5850 Revert field name case in interrupts input
  plugins/inputs/interrupts/interrupts.go
  plugins/inputs/interrupts/interrupts_test.go
Labels: bugfix

#5791 Statsd datadog
  docs/LICENSE_OF_DEPENDENCIES.md
  plugins/inputs/statsd/README.md
  plugins/inputs/statsd/datadog.go
  plugins/inputs/statsd/datadog_test.go
  plugins/inputs/statsd/running_stats.go
  plugins/inputs/statsd/statsd.go
  plugins/inputs/statsd/statsd_test.go
Labels: area/statsd, enhancement

#5817 Diskio plugin: make devices glob also match devlinks
  plugins/inputs/diskio/diskio.go
  plugins/inputs/diskio/diskio_linux_test.go
Labels: enhancement

#5820 Add final aggregator; emits final metric in a series after quiet period
  Gopkg.lock
  plugins/aggregators/all/all.go
  plugins/aggregators/final/README.md
  plugins/aggregators/final/final.go
  plugins/aggregators/final/final_test.go
  testutil/metric.go
  testutil/metric_test.go
Labels: new plugin

#5840 templating: fix templateSpecs.Less()
  internal/templating/template.go
  internal/templating/template_test.go
Labels: enhancement

#5855 Support tags in enum processor
  plugins/processors/enum/README.md
  plugins/processors/enum/enum.go
  plugins/processors/enum/enum_test.go
Labels: enhancement

#5838 Improve Docker image identifier parsing
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
Labels: area/docker, bugfix

#5869 Update postgres/pgbouncer docs about #4872 questions
  plugins/inputs/pgbouncer/README.md
  plugins/inputs/postgresql/README.md
Labels: area/postgresql, documentation

#5868 Fix publishing direct exchange routing key
  plugins/outputs/amqp/amqp.go
Labels: area/rabbitmq, bugfix

#5811 Log actual url on wrong status code
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
Labels: bugfix

#5821 Fix resource id in virtual machine scale sets with azure_monitor output
  plugins/outputs/azure_monitor/azure_monitor.go
Labels: bugfix

#5830 Add support for gzip compression to amqp input and output
  internal/content_coding.go
  internal/content_coding_test.go
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
  plugins/outputs/amqp/README.md
  plugins/outputs/amqp/amqp.go
  plugins/outputs/amqp/client.go
Labels: area/rabbitmq, enhancement

#5831 Support passive queue declaration in amqp_consumer
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
  plugins/outputs/amqp/README.md
  plugins/outputs/amqp/amqp.go
  plugins/outputs/amqp/client.go
Labels: area/rabbitmq, enhancement

#5896 Fixes #5883 Omits power_failed and power_restored when the Apex provides invalid timestamps. Eg: "none"
  plugins/inputs/neptune_apex/README.md
  plugins/inputs/neptune_apex/neptune_apex.go
  plugins/inputs/neptune_apex/neptune_apex_test.go
Labels: bugfix

#5897 Move defered closing of connection
  plugins/inputs/sqlserver/sqlserver.go
Labels: bugfix

#5901 Set user agent in all Stackdriver requests
  plugins/outputs/stackdriver/stackdriver.go
Labels: area/gcp, enhancement

#5875 Adjust Postfix docs to have proper setfacl command
  plugins/inputs/postfix/README.md
Labels: documentation

#5885 Extend metrics collected from Nvidia GPUs
  plugins/inputs/nvidia_smi/README.md
  plugins/inputs/nvidia_smi/nvidia_smi.go
  plugins/inputs/nvidia_smi/nvidia_smi_test.go
Labels: enhancement

#5121 ecs/fargate input plugin
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/stats_helpers.go
  plugins/inputs/ecs/README.md
  plugins/inputs/ecs/client.go
  plugins/inputs/ecs/client_test.go
  plugins/inputs/ecs/ecs.go
  plugins/inputs/ecs/ecs_test.go
  plugins/inputs/ecs/stats.go
  plugins/inputs/ecs/stats_test.go
  plugins/inputs/ecs/testdata/metadata.golden
  plugins/inputs/ecs/testdata/stats.golden
  plugins/inputs/ecs/types.go
  plugins/inputs/ecs/types_test.go
Labels: area/k8s, new plugin

#5917 Fix typo in nginx_upstream_check
  plugins/inputs/nginx_upstream_check/nginx_upstream_check.go
Labels: bugfix

#5920 Fixed datastore name mapping issue
  plugins/inputs/vsphere/endpoint.go
Labels: area/vsphere, bugfix

#5882 Add health output plugin
  internal/http.go
  internal/internal.go
  plugins/outputs/all/all.go
  plugins/outputs/health/README.md
  plugins/outputs/health/compares.go
  plugins/outputs/health/compares_test.go
  plugins/outputs/health/contains.go
  plugins/outputs/health/contains_test.go
  plugins/outputs/health/health.go
  plugins/outputs/health/health_test.go
Labels: new plugin

#5125 Open weather map input plugin
  plugins/inputs/all/all.go
  plugins/inputs/openweathermap/README.md
  plugins/inputs/openweathermap/openweathermap.go
  plugins/inputs/openweathermap/openweathermap_test.go
  testutil/accumulator.go
Labels: new plugin

#5912 Close idle connections in influxdb outputs when reloading
  internal/http_go1.11.go
  internal/http_go1.12.go
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb/influxdb.go
  plugins/outputs/influxdb/influxdb_test.go
  plugins/outputs/influxdb/udp.go
  plugins/outputs/influxdb_v2/http.go
  plugins/outputs/influxdb_v2/influxdb.go
Labels: bugfix
