Repository influxdata/telegraf, pull requests merged in 2019-04, with the labels that each got.

#5641 [aggregators/histogram] Add option to reset buckets on flush
  plugins/aggregators/histogram/README.md
  plugins/aggregators/histogram/histogram.go
  plugins/aggregators/histogram/histogram_test.go
Labels: enhancement

#5643 Use github.com/ghodss/yaml to parse k8s config (#5642)
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/prometheus/kubernetes.go
Labels: bugfix

#5664 Allow Wavefront output to accept / and ,
  plugins/outputs/wavefront/README.md
  plugins/outputs/wavefront/wavefront.go
  plugins/outputs/wavefront/wavefront_test.go
Labels: enhancement

#5660 Fix Makefile Target Name in Contributing Docs
  CONTRIBUTING.md
Labels: documentation

#5663 Validate tag names for consul input
  plugins/outputs/prometheus_client/prometheus_client.go
Labels: area/prometheus, bugfix

#5587 Input Plugin: GitHub
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/all/all.go
  plugins/inputs/github/README.md
  plugins/inputs/github/github.go
  plugins/inputs/github/github_test.go
Labels: new plugin

#5653 Bind input plugin
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/bind/README.md
  plugins/inputs/bind/bind.go
  plugins/inputs/bind/bind_test.go
  plugins/inputs/bind/json_stats.go
  plugins/inputs/bind/testdata/json/v1/mem
  plugins/inputs/bind/testdata/json/v1/net
  plugins/inputs/bind/testdata/json/v1/server
  plugins/inputs/bind/testdata/xml/v2
  plugins/inputs/bind/testdata/xml/v3/mem
  plugins/inputs/bind/testdata/xml/v3/net
  plugins/inputs/bind/testdata/xml/v3/server
  plugins/inputs/bind/xml_stats_v2.go
  plugins/inputs/bind/xml_stats_v3.go
Labels: new plugin

#5680 Allow colons in metric names in prometheus_client output
  plugins/outputs/prometheus_client/prometheus_client.go
  plugins/outputs/prometheus_client/prometheus_client_test.go
Labels: area/prometheus, bugfix

#5670 add wavefront serializer plugin
  docs/DATA_FORMATS_OUTPUT.md
  internal/config/config.go
  plugins/serializers/registry.go
  plugins/serializers/wavefront/README.md
  plugins/serializers/wavefront/wavefront.go
  plugins/serializers/wavefront/wavefront_test.go
Labels: area/wavefront, new plugin

#5697 Add optional namespace restriction to prometheus input plugin
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/kubernetes.go
  plugins/inputs/prometheus/prometheus.go
Labels: area/prometheus, enhancement

#5708 Deprecate uptime_format field in system input
  plugins/inputs/system/README.md
  plugins/inputs/system/system.go
Labels: enhancement

#5681 adding cmdline procstat
  plugins/inputs/procstat/README.md
  plugins/inputs/procstat/process.go
  plugins/inputs/procstat/procstat.go
  plugins/inputs/procstat/procstat_test.go
Labels: area/procstat, enhancement

#5704 Change ping endpoint to match influxdb
  plugins/inputs/influxdb_listener/http_listener.go
Labels: area/influxdb, enhancement

#5716 fix(package): make rpm verify pass after installation
  scripts/build.py
  scripts/post-install.sh
Labels: enhancement

#5713 Enhance HTTP connection options for phpfpm input plugin
  plugins/inputs/phpfpm/README.md
  plugins/inputs/phpfpm/phpfpm.go
Labels: enhancement

#5741 Fix docs for metric buffer limit to reflect current behavior
  docs/CONFIGURATION.md
  etc/telegraf.conf
  etc/telegraf_windows.conf
  internal/config/config.go
  plugins/inputs/vsphere/vsphere_test.go
Labels: bugfix, documentation

#5731 Don't start telegraf when stale pidfile found
  scripts/init.sh
Labels: bugfix

#5544 Collect cloudwatch stats in a more efficient and cost effective manner
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
Labels: area/aws, enhancement

#5745 Update README: add link to Telegraf playground to try it in browser
  README.md
Labels: documentation

#5757 Speed up getting interfaces stats
  plugins/inputs/net/net.go
Labels: enhancement, performance

#5733 Support Minecraft server 1.13 and newer
  plugins/inputs/minecraft/README.md
  plugins/inputs/minecraft/client.go
  plugins/inputs/minecraft/client_test.go
  plugins/inputs/minecraft/minecraft.go
  plugins/inputs/minecraft/minecraft_test.go
  plugins/inputs/minecraft/rcon.go
  plugins/inputs/minecraft/rcon_disconnect_error_test.go
  plugins/inputs/minecraft/rcon_test.go
  testutil/accumulator.go
Labels: bugfix

#4545 Add PowerDNS Recursor input plugin
  README.md
  etc/telegraf.conf
  plugins/inputs/all/all.go
  plugins/inputs/powerdns_recursor/README.md
  plugins/inputs/powerdns_recursor/powerdns_recursor.go
  plugins/inputs/powerdns_recursor/powerdns_recursor_test.go
Labels: new plugin

#5764 Fixed race condition in the Wavefront parser
  plugins/parsers/wavefront/parser.go
Labels: bugfix

#5769 Add pagefault data to procstat input plugin
  plugins/inputs/procstat/README.md
  plugins/inputs/procstat/process.go
  plugins/inputs/procstat/procstat.go
  plugins/inputs/procstat/procstat_test.go
Labels: area/procstat, enhancement

#5760 Set socket permissions for unix domain sockets
  plugins/inputs/socket_listener/README.md
  plugins/inputs/socket_listener/socket_listener.go
Labels: enhancement

#5513 Update toml library used for improved configuration ingestion
  Gopkg.lock
  Gopkg.toml
  internal/config/config_test.go
  internal/config/testdata/inline_table.toml
  internal/config/testdata/invalid_field.toml
  internal/config/testdata/non_slice_slice.toml
  internal/config/testdata/slice_comment.toml
  internal/config/testdata/special_types.toml
  internal/config/testdata/wrong_field_type.toml
  internal/config/testdata/wrong_field_type2.toml
Labels: area/configuration, bugfix

#5585 Add ability to filter printed headers in `telegraf config`
  cmd/telegraf/telegraf.go
  internal/config/config.go
Labels: area/agent, area/configuration

#5763 No longer requires dep to be in $GOPATH/bin
  scripts/build.py
Labels: bugfix

#5768 Check if a process is running using it's name
  plugins/inputs/procstat/procstat.go
Labels: bugfix

#5783 fix(package): create telegraf user before install
  scripts/post-install.sh
  scripts/pre-install.sh
Labels: bugfix

#5772 Use non-release revision of pgx for pgbouncer fix
  Gopkg.lock
  Gopkg.toml
Labels: bugfix
