Repository influxdata/telegraf, pull requests merged in 2019-09, with the labels that each got.

#6349 Switch to fork of sarama without zstd dependency
  Gopkg.lock
  Gopkg.toml
Labels: area/packaging, bugfix

#6363 Fix could not mark message delivered error in kafka_consumer
  plugins/inputs/kafka_consumer/kafka_consumer.go
Labels: bugfix

#6333 Convert check state to an integer
  plugins/inputs/icinga2/icinga2.go
  plugins/inputs/icinga2/icinga2_test.go
Labels: bugfix

#6332 Fix filecount for paths with trailing slash
  plugins/inputs/filecount/filecount.go
  plugins/inputs/filecount/filecount_test.go
Labels: bugfix

#6364 Skip collection stats when disabled
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb.go
  plugins/inputs/mongodb/mongodb_server.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, bugfix

#6372 Fix error reading closed response body on redirect
  plugins/inputs/http_response/http_response.go
  plugins/inputs/http_response/http_response_test.go
Labels: bugfix

#6377 Fix apcupsd documentation to reflect actual plugin
  plugins/inputs/apcupsd/README.md
Labels: bugfix, documentation

#6400 Allow booleans as json string fields again
  plugins/parsers/json/parser.go
Labels: bugfix

#6401 Update apcupsd library
  Gopkg.lock
  Gopkg.toml
Labels: bugfix

#6390 Fix detection of layout timestamps
  internal/internal.go
  internal/internal_test.go
  plugins/parsers/csv/parser.go
  plugins/parsers/json/parser.go
Labels: bugfix

#6389 Use gopsutil fork with backported disk lvm fix
  Gopkg.lock
  Gopkg.toml
Labels: bugfix

#6177 Cisco MDT input: minor improvements and support for NX-OS telemetry extensions
  Gopkg.lock
  plugins/inputs/cisco_telemetry_mdt/README.md
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
Labels: enhancement

#6404 Recommend Installing TICK Stack with Helm Stable Charts
  plugins/inputs/kube_inventory/README.md
  plugins/inputs/kubernetes/README.md
Labels: documentation

#6409 updated doc for tls connections
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, documentation

#6420 Allow graphite parser to create Inf and NaN values.
  plugins/parsers/graphite/errors.go
  plugins/parsers/graphite/parser.go
  plugins/parsers/graphite/parser_test.go
  testutil/metric.go
Labels: enhancement

#6411 Update cpu docs
  plugins/inputs/cpu/README.md
Labels: documentation

#3145 add Suricata plugin
  plugins/inputs/all/all.go
  plugins/inputs/suricata/README.md
  plugins/inputs/suricata/suricata.go
  plugins/inputs/suricata/suricata_test.go
  plugins/inputs/suricata/suricata_testutil.go
  plugins/inputs/suricata/testdata/test1.json
Labels: enhancement, new plugin

#6393 Require goplugin build flag to enable go plugin support
  cmd/telegraf/telegraf.go
  internal/goplugin/noplugin.go
  internal/goplugin/plugin.go
Labels: breaking change

#6434 Allow alternate base when grok parsing ints.
  plugins/parsers/grok/parser.go
  plugins/parsers/grok/parser_test.go
Labels: enhancement

#6403 GNMI: Improve platform compatibility and corner case handling
  plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go
Labels: bugfix

#6446 Change the Exec output to use BatchSerialize()
  plugins/outputs/exec/exec.go
Labels: bugfix

#6410 Add merge aggregator
  plugins/aggregators/all/all.go
  plugins/aggregators/merge/README.md
  plugins/aggregators/merge/merge.go
  plugins/aggregators/merge/merge_test.go
Labels: new plugin

#6455 Use Go 1.12.10 for builds
  .circleci/config.yml
  Makefile
  scripts/ci-1.12.docker
Labels: area/packaging, bugfix

#6464 Add case insensitivity to serial numer matching
  plugins/inputs/smart/smart.go
Labels: bugfix

#6465 More metrics for SQL Server plugin
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, enhancement

#6469 fix(config): allow remote config with no auth
  internal/config/config.go
Labels: bugfix
