Repository influxdata/telegraf, pull requests merged in 2019-10, with the labels that each got.

#6479 Install and configure CLAsee
  .github/workflows/main.yml
Labels: enhancement

#6468 Remove shared package level vars from sqlserver and mysql input plugins
  plugins/inputs/mysql/mysql.go
  plugins/inputs/mysql/mysql_test.go
  plugins/inputs/sqlserver/sqlserver.go
  plugins/inputs/sqlserver/sqlserver_test.go
Labels: area/mysql, area/sqlserver, bugfix

#6476 grok: Implement support for ts-epochmilli
  plugins/inputs/logparser/README.md
  plugins/inputs/logparser/logparser_test.go
  plugins/inputs/logparser/testdata/test-patterns
  plugins/inputs/logparser/testdata/test_c.log
  plugins/parsers/grok/README.md
  plugins/parsers/grok/parser.go
  plugins/parsers/grok/parser_test.go
Labels: area/tail, enhancement

#6486 Fix database routing on retry with exclude_database_tag
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb/http_test.go
  plugins/outputs/influxdb_v2/http.go
  plugins/outputs/influxdb_v2/http_test.go
Labels: area/influxdb, bugfix

#6492 Fix logger initialization in exec input
  internal/config/config_test.go
  plugins/inputs/exec/exec.go
  plugins/inputs/exec/exec_test.go
Labels: bugfix

#6473 Containers can now be identified by the container ID
  plugins/inputs/docker/README.md
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker_log/README.md
  plugins/inputs/docker_log/docker_log.go
  plugins/inputs/docker_log/docker_log_test.go
Labels: area/docker, enhancement

#6301 Clarify behaviour of enum processor without default or defined mapping
  plugins/processors/enum/README.md
  plugins/processors/enum/enum_test.go
Labels: documentation, enhancement

#6462 Build official packages with Go 1.13.1
  .circleci/config.yml
  Makefile
  README.md
  appveyor.yml
  plugins/outputs/application_insights/application_insights_test.go
  plugins/outputs/prometheus_client/prometheus_client_tls_test.go
  scripts/ci-1.11.docker
  scripts/ci-1.13.docker
Labels: area/packaging

#6526 Document specifying csv data types in column order
  plugins/parsers/csv/README.md
Labels: documentation

#6504 Add lang parameter to OpenWeathermap input plugin
  plugins/inputs/openweathermap/README.md
  plugins/inputs/openweathermap/openweathermap.go
  plugins/inputs/openweathermap/openweathermap_test.go
Labels: enhancement

#6529 Clone processor
  plugins/processors/clone/README.md
  plugins/processors/clone/clone.go
  plugins/processors/clone/clone_test.go
Labels: new plugin

#6551 Fix doc-link
  plugins/inputs/zookeeper/README.md
Labels: documentation

#6540 feat(tail): supress error to debug when file doesn't exist
  plugins/inputs/tail/tail.go
Labels: enhancement

#6553 Add timeout to cloudwatch input
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch.go
Labels: area/aws, enhancement

#6549 HTTP input plugin: Supporting custom success codes
  etc/telegraf.conf
  plugins/inputs/http/README.md
  plugins/inputs/http/http.go
  plugins/inputs/http/http_test.go
Labels: enhancement

#6484 Show default settings in mysql sample config
  plugins/inputs/mysql/README.md
  plugins/inputs/mysql/mysql.go
Labels: area/mysql, bugfix, documentation

#6530 Improve ipvs input error strings
  Gopkg.lock
  plugins/common/logrus/hook.go
  plugins/inputs/ipvs/ipvs.go
Labels: enhancement

#6565 Build with Go 1.13.3 and 1.12.12
  .circleci/config.yml
  Makefile
  appveyor.yml
  scripts/ci-1.12.docker
  scripts/ci-1.13.docker
Labels: area/packaging

#6555 Default logtarget to file for backwards compatibility
  docs/CONFIGURATION.md
  internal/config/config.go
Labels: area/configuration, area/logging, bugfix

#6557 Update godirwalk version
  Gopkg.lock
  Gopkg.toml
Labels: area/packaging

#6563 Ensure metrics generated are correct in ping plugin using "native"
  Gopkg.lock
  plugins/inputs/ping/ping.go
Labels: bugfix

#6571 Exclude alias tag if unset from plugin internal stats
  internal/models/running_aggregator.go
  internal/models/running_input.go
  internal/models/running_output.go
  internal/models/running_processor.go
  selfstat/selfstat.go
  selfstat/selfstat_test.go
  selfstat/stat.go
  selfstat/timingStat.go
Labels: bugfix

#6572 Fix powerdns_recursor socket_mode option
  plugins/inputs/powerdns/README.md
  plugins/inputs/powerdns_recursor/powerdns_recursor.go
  plugins/inputs/powerdns_recursor/powerdns_recursor_test.go
Labels: bugfix

#6536 feat(parser/json): continue parsing JSON after invalid object in array, with an option of strict to enforce validity of all objects
  plugins/parsers/json/README.md
  plugins/parsers/json/parser.go
  plugins/parsers/json/parser_test.go
  plugins/parsers/registry.go
Labels: enhancement

#6543 fix(kubernetes): remove usage of deprecated API endpoints, v1beta
  Gopkg.lock
  plugins/inputs/kube_inventory/README.md
  plugins/inputs/kube_inventory/client.go
  plugins/inputs/kube_inventory/daemonset.go
  plugins/inputs/kube_inventory/daemonset_test.go
  plugins/inputs/kube_inventory/deployment.go
  plugins/inputs/kube_inventory/deployment_test.go
  plugins/inputs/kube_inventory/ingress_test.go
  plugins/inputs/kube_inventory/statefulset.go
  plugins/inputs/kube_inventory/statefulset_test.go
  plugins/inputs/kubernetes/README.md
Labels: area/k8s, enhancement

#6283 Add gathering of RabbitMQ federation link metrics.
  plugins/inputs/rabbitmq/README.md
  plugins/inputs/rabbitmq/rabbitmq.go
  plugins/inputs/rabbitmq/rabbitmq_test.go
  plugins/inputs/rabbitmq/testdata/federation-links.json
Labels: area/rabbitmq, enhancement

#6505 Added descriptions for kapacitor input metrics
  plugins/inputs/kapacitor/README.md
Labels: documentation
