Repository influxdata/telegraf, pull requests merged in 2019-11, with the labels that each got.

#6581 Fix incorrect results in ping plugin
  plugins/inputs/ping/ping.go
  plugins/inputs/ping/ping_test.go
Labels: bugfix

#6610 Fixed an inconsistency in the value of the tag sql_instance
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/azure, area/sqlserver, bugfix

#6600 Update CONFIGURATION.md
  docs/CONFIGURATION.md
Labels: documentation

#6356 Add BearerToken Defaults for Kubernetes Plugins
  plugins/inputs/kube_inventory/README.md
  plugins/inputs/kube_inventory/kube_state.go
  plugins/inputs/kubernetes/README.md
  plugins/inputs/kubernetes/kubernetes.go
Labels: enhancement

#6630 Change plugin error message to debug message
  agent/accumulator.go
Labels: bugfix

#5870 Support for SNMP over TCP
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/snmp/README.md
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
Labels: area/snmp, enhancement

#6632 Use github.com/miekg/dns 1.0.10
  Gopkg.lock
  Gopkg.toml
Labels: bugfix

#6625 Add missing ServerProperties query to sqlserver input docs
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
Labels: bugfix, documentation

#5865 Ethtool Input Plugin (#5864)
  Gopkg.lock
  Gopkg.toml
  plugins/inputs/all/all.go
  plugins/inputs/ethtool/README.md
  plugins/inputs/ethtool/ethtool.go
  plugins/inputs/ethtool/ethtool_linux.go
  plugins/inputs/ethtool/ethtool_nonlinux.go
  plugins/inputs/ethtool/ethtool_test.go
Labels: new plugin

#6593 Use 1h or 3h rain values as appropriate
  plugins/inputs/openweathermap/README.md
  plugins/inputs/openweathermap/openweathermap.go
  plugins/inputs/openweathermap/openweathermap_test.go
Labels: enhancement

#6648 Skip logging when logfile is unset
  logger/logger.go
Labels: bugfix

#6643 Fix mongodb field name: total_created -> totalCreated
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, bugfix

#6647 Fix known mysql type conversion issues
  plugins/inputs/mysql/mysql.go
  plugins/inputs/mysql/v2/convert.go
  plugins/inputs/mysql/v2/convert_test.go
Labels: area/mysql, bugfix

#6649 Fix uptime_ns calculation when container has been restarted
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
Labels: area/docker, bugfix

#6627 Fix metric creation when node is offline in jenkins input
  plugins/inputs/jenkins/README.md
  plugins/inputs/jenkins/jenkins.go
  plugins/inputs/jenkins/jenkins_test.go
Labels: bugfix

#6639 Update nvidia-smi input to use xml
  plugins/inputs/nvidia_smi/nvidia_smi.go
  plugins/inputs/nvidia_smi/nvidia_smi_test.go
Labels: bugfix

#6603 Handle per-plugin flush jitter, fixes #6569
  agent/agent.go
  docs/CONFIGURATION.md
  internal/config/config.go
  internal/models/running_output.go
Labels: enhancement

#6621 Fix influxdb output serialization on connection closed
  internal/internal.go
  internal/internal_test.go
  plugins/inputs/http/http.go
  plugins/outputs/http/http.go
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb/influxdb.go
  plugins/outputs/influxdb_v2/http.go
  plugins/outputs/influxdb_v2/influxdb.go
Labels: bugfix

#6650 Add a nameable file tag to file input plugin
  plugins/inputs/file/README.md
  plugins/inputs/file/file.go
  plugins/inputs/file/file_test.go
Labels: enhancement

#6656 Upgrading Azure/go-autorest version to ^13.0.0
  Gopkg.lock
  Gopkg.toml
Labels: bugfix

#6641 Add source and port tags to jenkins plugin
  plugins/inputs/jenkins/README.md
  plugins/inputs/jenkins/jenkins.go
  plugins/inputs/jenkins/jenkins_test.go
Labels: enhancement

#6658 Build the nats input on freebsd when cgo is enabled
  plugins/inputs/nats/nats.go
  plugins/inputs/nats/nats_freebsd.go
  plugins/inputs/nats/nats_test.go
Labels: bugfix, enhancement, platform/bsd

#6665 Log no metrics found at debug level in cloudwatch input
  agent/accumulator.go
  plugins/inputs/cloudwatch/cloudwatch.go
Labels: bugfix

#6663 Use nanosecond precision in docker_log input
  plugins/inputs/docker_log/docker_log.go
Labels: area/docker, bugfix

#6667 Fix interface option with method = native in ping input
  plugins/inputs/ping/ping.go
Labels: bugfix

#6640 Add Splunk MultiMetric support
  internal/config/config.go
  plugins/serializers/registry.go
  plugins/serializers/splunkmetric/README.md
  plugins/serializers/splunkmetric/splunkmetric.go
  plugins/serializers/splunkmetric/splunkmetric_test.go
Labels: enhancement

#6680 fix panic issue that causes by nil ShardStats.
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, bugfix

#6668 Add support for sending HTTP Basic Auth in influxdb input
  plugins/inputs/influxdb/README.md
  plugins/inputs/influxdb/influxdb.go
  plugins/inputs/influxdb/influxdb_test.go
Labels: area/influxdb, enhancement

#5767 prometheus metric_version = 2 & make scrape url as a configurable tag
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/parser.go
  plugins/inputs/prometheus/prometheus.go
  plugins/inputs/prometheus/prometheus_test.go
  testutil/accumulator.go
Labels: area/prometheus, enhancement

#5683 Synproxy input plugin
  plugins/inputs/all/all.go
  plugins/inputs/synproxy/README.md
  plugins/inputs/synproxy/synproxy.go
  plugins/inputs/synproxy/synproxy_notlinux.go
  plugins/inputs/synproxy/synproxy_test.go
Labels: new plugin

#6660 Add compression support to socket_listener
  plugins/inputs/socket_listener/README.md
  plugins/inputs/socket_listener/socket_listener.go
  plugins/inputs/socket_listener/socket_listener_test.go
Labels: enhancement

#6689 Add StorageResolution config to CloudWatch output
  plugins/outputs/cloudwatch/README.md
  plugins/outputs/cloudwatch/cloudwatch.go
  plugins/outputs/cloudwatch/cloudwatch_test.go
Labels: area/aws, enhancement

#6629 Add snmp_trap input plugin
  Gopkg.lock
  plugins/inputs/all/all.go
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
  plugins/inputs/snmp_trap/README.md
  plugins/inputs/snmp_trap/snmp_trap.go
  plugins/inputs/snmp_trap/snmp_trap_test.go
Labels: new plugin

#6716 Add SReclaimable and SUnreclaim to mem input
  Gopkg.toml
  plugins/inputs/mem/README.md
  plugins/inputs/mem/memory.go
  plugins/inputs/mem/memory_test.go
Labels: enhancement

#6695 Allow multiple certificates on same file for x509 input
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: enhancement

#6686 Add additional tags for x509 Input Plugin
  plugins/inputs/x509_cert/README.md
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: enhancement

#6719 Added link to VMWare vCenter Converter API Reference
  plugins/inputs/vsphere/METRICS.md
Labels: area/vsphere, documentation

#6703 Add prometheus serializer and use it in prometheus output
  Gopkg.lock
  docs/DATA_FORMATS_OUTPUT.md
  internal/http.go
  plugins/inputs/file/file.go
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/prometheus.go
  plugins/outputs/file/README.md
  plugins/outputs/file/file.go
  plugins/outputs/prometheus_client/README.md
  plugins/outputs/prometheus_client/prometheus_client.go
  plugins/outputs/prometheus_client/prometheus_client_test.go
  plugins/outputs/prometheus_client/v1/collector.go
  plugins/outputs/prometheus_client/v2/collector.go
  plugins/serializers/prometheus/README.md
  plugins/serializers/prometheus/collection.go
  plugins/serializers/prometheus/collection_test.go
  plugins/serializers/prometheus/convert.go
  plugins/serializers/prometheus/prometheus.go
  plugins/serializers/prometheus/prometheus_test.go
  plugins/serializers/registry.go
Labels: area/prometheus, enhancement, new plugin

#6688 kafka_consumer: expose partition assignment strategy configuration (#6687)
  Gopkg.lock
  Gopkg.toml
  etc/telegraf.conf
  plugins/inputs/kafka_consumer/README.md
  plugins/inputs/kafka_consumer/kafka_consumer.go
Labels: area/kafka, enhancement

#6718 Update Telegraf README.md
  README.md
Labels: documentation
