Repository influxdata/telegraf, pull requests merged in 2019-08, with the labels that each got.

#6192 updating smart input docs for attributes clarity
  plugins/inputs/smart/README.md
  plugins/inputs/smart/smart.go
Labels: area/smart, documentation, enhancement

#6060 ElasticSearch: Add Indice stats to the output
  etc/telegraf.conf
  plugins/inputs/elasticsearch/README.md
  plugins/inputs/elasticsearch/elasticsearch.go
  plugins/inputs/elasticsearch/elasticsearch_test.go
  plugins/inputs/elasticsearch/testdata_test.go
Labels: area/elasticsearch, enhancement

#6194 Add support for Enterprise repos in Github plugin
  plugins/inputs/github/README.md
  plugins/inputs/github/github.go
  plugins/inputs/github/github_test.go
Labels: enhancement

#6195 Added TLS & credentials configuration for NATS_consumer input plugin
  plugins/inputs/nats_consumer/README.md
  plugins/inputs/nats_consumer/nats_consumer.go
Labels: enhancement

#6206 cleaning up cassandra input readme
  plugins/inputs/cassandra/README.md
Labels: documentation

#6208 Added README to disque input
  plugins/inputs/disque/README.md
Labels: documentation

#6200 logsfs available bytes fix
  plugins/inputs/kubernetes/kubernetes.go
  plugins/inputs/kubernetes/kubernetes_test.go
Labels: bugfix

#6198 Skip floats that are NaN or Inf in Datadog output.
  plugins/outputs/datadog/datadog.go
  plugins/outputs/datadog/datadog_test.go
Labels: bugfix

#6201 Added tags to smart_attributes
  plugins/inputs/smart/README.md
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: area/smart, enhancement

#6218 Fix possible panic in socket_listener input plugin (resolves #6209)
  plugins/inputs/socket_listener/socket_listener.go
Labels: bugfix

#6214 Get the number of logcal CPUs dynamically
  plugins/inputs/system/README.md
  plugins/inputs/system/system.go
Labels: area/system, enhancement

#6221 Ignore context cancelled error in docker_log
  plugins/inputs/docker_log/docker_log.go
Labels: area/docker, bugfix

#6231 Document permission setup for powerdns_recursor
  plugins/inputs/powerdns_recursor/README.md
  plugins/inputs/powerdns_recursor/powerdns_recursor.go
Labels: bugfix, documentation

#6224 Update Elaticsearch Output Plugin README.md
  plugins/outputs/elasticsearch/README.md
Labels: area/elasticsearch, documentation

#5719 mesos input: Collect framework_offers and allocator metrics
  plugins/inputs/mesos/README.md
  plugins/inputs/mesos/mesos.go
  plugins/inputs/mesos/mesos_test.go
Labels: enhancement

#6241 Made the SMART timeout a parameter, and set the default to 30s
  plugins/inputs/smart/README.md
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: area/smart, enhancement

#6249 Add memory_usage (percent) field to procstat input plugin
  plugins/inputs/procstat/process.go
  plugins/inputs/procstat/procstat.go
  plugins/inputs/procstat/procstat_test.go
Labels: area/procstat, enhancement

#6230 Mongodb refactor collection stat errors
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_server.go
Labels: area/mongodb

#5971 Added support for custom attributes
  plugins/inputs/vsphere/README.md
  plugins/inputs/vsphere/client.go
  plugins/inputs/vsphere/endpoint.go
  plugins/inputs/vsphere/finder.go
  plugins/inputs/vsphere/vsphere.go
  plugins/inputs/vsphere/vsphere_test.go
Labels: area/vsphere, enhancement

#6250 Update github.com/go-sql-driver/mysql to 1.4.1
  Gopkg.lock
Labels: bugfix

#6236 Fix persistent session in mqtt_consumer.
  plugins/inputs/mqtt_consumer/README.md
  plugins/inputs/mqtt_consumer/mqtt_consumer.go
  plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
Labels: area/mqtt, bugfix

#6268 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#6279 Fix issue #6278
  agent/agent.go
Labels: bugfix

#6257 Allow influxdb_listener to keep the database name from the query string if supplied
  plugins/inputs/influxdb_listener/README.md
  plugins/inputs/influxdb_listener/http_listener.go
  plugins/inputs/influxdb_listener/http_listener_test.go
Labels: enhancement

#6261 Add content_length metric to http_response input plugin (#6037)
  plugins/inputs/http_response/README.md
  plugins/inputs/http_response/http_response.go
  plugins/inputs/http_response/http_response_test.go
Labels: enhancement

#5926 Capture and parse the cmdstat timings from `INFO ALL` command
  plugins/inputs/redis/README.md
  plugins/inputs/redis/redis.go
  plugins/inputs/redis/redis_test.go
Labels: area/redis, enhancement

#6246 Add possibility to setting up tls security levels
  docs/TLS.md
  internal/tls/common.go
  internal/tls/common_go112.go
  internal/tls/config.go
  internal/tls/config_test.go
  internal/tls/utils.go
  plugins/outputs/prometheus_client/README.md
  plugins/outputs/prometheus_client/prometheus_client.go
  plugins/outputs/prometheus_client/prometheus_client_tls_test.go
  testutil/tls.go
Labels: enhancement

#6210 Create readme for mailchimp input
  plugins/inputs/mailchimp/README.md
Labels: documentation

#6211 adding readme to rethinkdb input
  plugins/inputs/rethinkdb/README.md
Labels: documentation

#6245 Fixed finder inconsistencies
  Gopkg.lock
  plugins/inputs/vsphere/finder.go
  plugins/inputs/vsphere/vsphere_test.go
Labels: area/vsphere, bugfix

#6266 Add topic_tag option to mqtt_consumer
  plugins/inputs/mqtt_consumer/README.md
  plugins/inputs/mqtt_consumer/mqtt_consumer.go
  plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
Labels: enhancement

#6086 Tag limit processor
  plugins/processors/all/all.go
  plugins/processors/tag_limit/README.md
  plugins/processors/tag_limit/tag_limit.go
  plugins/processors/tag_limit/tag_limit_test.go
Labels: new plugin

#6288 Updated logparser readme
  plugins/inputs/logparser/README.md
Labels: area/tail, documentation

#3627 Input plugin for openntpd
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/openntpd/README.md
  plugins/inputs/openntpd/openntpd.go
  plugins/inputs/openntpd/openntpd_test.go
Labels: new plugin

#6267 Add exec output plugin
  README.md
  internal/internal.go
  plugins/outputs/all/all.go
  plugins/outputs/exec/README.md
  plugins/outputs/exec/exec.go
  plugins/outputs/exec/exec_test.go
Labels: new plugin

#6226 Add apcupsd input plugin
  Gopkg.lock
  Gopkg.toml
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/apcupsd/README.md
  plugins/inputs/apcupsd/apcupsd.go
  plugins/inputs/apcupsd/apcupsd_test.go
Labels: new plugin

#6286 Update win_perf_counters sample config
  etc/telegraf_windows.conf
  plugins/inputs/win_perf_counters/win_perf_counters.go
Labels: area/win_perf_counters, documentation

#6296 Stop timer when command exits in WaitTimeout
  internal/internal.go
  internal/internal_test.go
Labels: bugfix

#6289 Fix parsing multiple metrics on the first line of tailed file
  plugins/inputs/tail/tail.go
  plugins/inputs/tail/tail_test.go
Labels: area/tail, bugfix

#4910 Add Logstash input plugin (both version 5 and 6 support)
  .gitignore
  plugins/inputs/all/all.go
  plugins/inputs/logstash/README.md
  plugins/inputs/logstash/logstash.go
  plugins/inputs/logstash/logstash_test.go
  plugins/inputs/logstash/samples_logstash5.go
  plugins/inputs/logstash/samples_logstash6.go
Labels: area/logging, new plugin

#6297 Document additional collected Kubernetes resources
  plugins/inputs/kube_inventory/README.md
  plugins/inputs/kube_inventory/kube_state.go
Labels: documentation

#6300 Add TLS support to nginx_plus, nginx_plus_api and nginx_vts
  plugins/inputs/nginx_plus/nginx_plus.go
  plugins/inputs/nginx_plus_api/nginx_plus_api.go
  plugins/inputs/nginx_vts/nginx_vts.go
Labels: enhancement

#6193 Marklogic Input Plugin
  plugins/inputs/all/all.go
  plugins/inputs/marklogic/README.md
  plugins/inputs/marklogic/marklogic.go
  plugins/inputs/marklogic/marklogic_test.go
Labels: new plugin

#6302 Send TERM to exec processes before sending KILL signal
  internal/exec.go
  internal/exec_unix.go
  internal/exec_windows.go
  internal/internal.go
Labels: bugfix

#6304 Split out -w argument in iptables input
  plugins/inputs/iptables/iptables.go
Labels: bugfix

#6312 Added supported versions to README
  plugins/inputs/vsphere/README.md
Labels: area/vsphere, documentation

#4291 Telegraf startup error reporting improvement
  cmd/telegraf/telegraf.go
  docs/CONFIGURATION.md
  docs/WINDOWS_SERVICE.md
  internal/config/config.go
  logger/event_logger.go
  logger/event_logger_test.go
  logger/logger.go
  logger/logger_test.go
Labels: area/agent, enhancement

#5323 Add azure_storage_queue input plugin
  Gopkg.lock
  Gopkg.toml
  docs/LICENSE_OF_DEPENDENCIES.md
  plugins/inputs/all/all.go
  plugins/inputs/azure_storage_queue/README.md
  plugins/inputs/azure_storage_queue/azure_storage_queue.go
Labels: area/azure, new plugin

#6326 add in extra rabbitmq memory stats - issue #6325
  plugins/inputs/rabbitmq/README.md
  plugins/inputs/rabbitmq/rabbitmq.go
  plugins/inputs/rabbitmq/rabbitmq_test.go
  plugins/inputs/rabbitmq/testdata/memory.json
Labels: area/rabbitmq, enhancement
