Repository influxdata/telegraf, pull requests merged in 2019-07, with the labels that each got.

#6056 inputs.ping Wrong ping flag on BSD
  plugins/inputs/ping/ping.go
Labels: bugfix, platform/bsd

#6053 Elasticsearch output - Add support up to ES 7.x
  docker-compose.yml
  plugins/outputs/elasticsearch/README.md
  plugins/outputs/elasticsearch/elasticsearch.go
Labels: area/elasticsearch, enhancement

#6062 Add basic auth to prometheus input plugin
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/prometheus.go
Labels: area/prometheus, enhancement

#6064 Elasticsearch: add node_roles tag
  plugins/inputs/elasticsearch/elasticsearch.go
  plugins/inputs/elasticsearch/elasticsearch_test.go
  plugins/inputs/elasticsearch/testdata_test.go
Labels: area/elasticsearch, enhancement

#6063 Use int64 for fields in bind plugin
  plugins/inputs/bind/bind_test.go
  plugins/inputs/bind/json_stats.go
  plugins/inputs/bind/xml_stats_v2.go
  plugins/inputs/bind/xml_stats_v3.go
Labels: bugfix

#6070 Burrow topic filter applied to partitions metrics
  plugins/inputs/burrow/burrow.go
  plugins/inputs/burrow/burrow_test.go
Labels: bugfix

#6088 Fix panic with empty datadog tag string
  plugins/inputs/statsd/datadog.go
  plugins/inputs/statsd/statsd_test.go
Labels: bugfix

#6077 Fix path separator matching in filecount input
  internal/globpath/globpath.go
  internal/globpath/globpath_test.go
Labels: bugfix

#6089 Remove tail cleanup call to avoid double decrement
  plugins/inputs/logparser/logparser.go
  plugins/inputs/tail/tail.go
Labels: bugfix

#6092 Fix https support in activemq input.
  plugins/inputs/activemq/README.md
  plugins/inputs/activemq/activemq.go
  plugins/inputs/activemq/activemq_test.go
Labels: bugfix

#6085 Fixed reconnection issue when vCenter is rebooted (issue 6054)
  plugins/inputs/vsphere/client.go
Labels: area/vsphere, bugfix

#6073 Handle edge case where we're unable to get data due to limitations of nvidia-smi
  plugins/inputs/nvidia_smi/README.md
  plugins/inputs/nvidia_smi/nvidia_smi.go
  plugins/inputs/nvidia_smi/nvidia_smi_test.go
Labels: bugfix

#5572 Floats in statsd percentiles (rebased with master)
  internal/internal.go
  plugins/inputs/statsd/README.md
  plugins/inputs/statsd/running_stats.go
  plugins/inputs/statsd/running_stats_test.go
  plugins/inputs/statsd/statsd.go
  plugins/inputs/statsd/statsd_test.go
Labels: area/statsd, enhancement

#6091 Emit sarama library log messages at debug level
  plugins/outputs/kafka/kafka.go
Labels: area/kafka, enhancement

#6050 Remove dependency on system binary from ping input plugin
  Gopkg.lock
  plugins/inputs/ping/README.md
  plugins/inputs/ping/ping.go
  plugins/inputs/ping/ping_notwindows.go
  plugins/inputs/ping/ping_test.go
  plugins/inputs/ping/ping_windows.go
Labels: enhancement

#6074 [tail/logparser] resume from last known offset when reloading
  plugins/inputs/logparser/logparser.go
  plugins/inputs/tail/tail.go
  plugins/inputs/tail/tail_test.go
Labels: enhancement

#6111 Adding/fixing support for Azure SQL Database (singleton database)
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, enhancement

#6079 Smart Input Plugin Extra Attributes
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: area/smart, enhancement

#6100 Update go-mssqldb version to latest release
  Gopkg.lock
Labels: area/sqlserver, bugfix

#6084 Docker Input Plugin Measure Thin Pool Minimum Free Space
  plugins/inputs/docker/README.md
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker/docker_testdata.go
Labels: area/docker, enhancement

#6116 @@servername change otherwise breaks MI with public endpoint
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver

#6122 Add basic auth support to elasticsearch input
  plugins/inputs/elasticsearch/README.md
  plugins/inputs/elasticsearch/elasticsearch.go
Labels: area/elasticsearch, enhancement, pm/enterprise readiness

#6101 Compile with gjson 1.3.0
  Gopkg.lock
Labels: enhancement

#6102 Support string field glob matching in json parser
  plugins/parsers/json/README.md
  plugins/parsers/json/parser.go
  plugins/parsers/json/parser_test.go
  plugins/parsers/registry.go
Labels: enhancement

#6099 example in docker config and readme.md
  plugins/inputs/docker/README.md
  plugins/inputs/docker/docker.go
Labels: documentation, enhancement

#6121 Fix Statsd input panic when processing DataDog events
  plugins/inputs/statsd/datadog_test.go
  plugins/inputs/statsd/statsd.go
Labels: bugfix

#6130 Treat empty array as successful parse
  plugins/parsers/json/parser.go
  plugins/parsers/json/parser_test.go
Labels: bugfix

#6114 Fix lustre2 input plugin config parse regression
  plugins/inputs/lustre2/lustre2.go
  plugins/inputs/lustre2/lustre2_test.go
Labels: bugfix, regression

#6135 Fix templating patterns wildcard matching
  internal/templating/engine_test.go
  internal/templating/node.go
Labels: bugfix

#6129 Add support for field/tag keys to strings processor
  plugins/processors/strings/README.md
  plugins/processors/strings/strings.go
  plugins/processors/strings/strings_test.go
Labels: enhancement

#6105 Collect k8s endpoints, ingress, and services in kube_inventory plugin
  Gopkg.lock
  plugins/inputs/kube_inventory/client.go
  plugins/inputs/kube_inventory/client_test.go
  plugins/inputs/kube_inventory/endpoint.go
  plugins/inputs/kube_inventory/endpoint_test.go
  plugins/inputs/kube_inventory/ingress.go
  plugins/inputs/kube_inventory/ingress_test.go
  plugins/inputs/kube_inventory/kube_state.go
  plugins/inputs/kube_inventory/service.go
  plugins/inputs/kube_inventory/service_test.go
Labels: area/k8s, enhancement

#6144 Adding support for collecting SQL Requests to identify blocking
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, enhancement

#6052 Fireboard Input Plugin
  plugins/inputs/all/all.go
  plugins/inputs/fireboard/README.md
  plugins/inputs/fireboard/fireboard.go
  plugins/inputs/fireboard/fireboard_test.go
Labels: new plugin

#6143 Add certificate verification status to x509_cert input
  plugins/inputs/x509_cert/README.md
  plugins/inputs/x509_cert/dev/telegraf.conf
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: enhancement

#6152 Avoid panic in github input
  plugins/inputs/github/github.go
Labels: bugfix

#6153 Add Linux mips build
  scripts/build.py
Labels: area/packaging

#6157 Add Start() function to DockerLogs input plugin
  plugins/inputs/docker_log/docker_log.go
Labels: area/docker, bugfix

#6161 Add networks, subscribers, and watchers to github input
  plugins/inputs/github/README.md
  plugins/inputs/github/github.go
  plugins/inputs/github/github_test.go
Labels: enhancement

#6163 redis input: fix percentage value parsing
  plugins/inputs/redis/redis.go
  plugins/inputs/redis/redis_test.go
Labels: area/redis, bugfix

#6175 Update links in fluentd input readme
  plugins/inputs/fluentd/README.md
Labels: documentation

#6172 Use sarama built in support for consumer groups
  Gopkg.lock
  Gopkg.toml
  Makefile
  docs/LICENSE_OF_DEPENDENCIES.md
  plugins/inputs/kafka_consumer/README.md
  plugins/inputs/kafka_consumer/kafka_consumer.go
  plugins/inputs/kafka_consumer/kafka_consumer_integration_test.go
  plugins/inputs/kafka_consumer/kafka_consumer_test.go
Labels: area/kafka, bugfix

#6024 Load external .so plugins, fixes #1717
  cmd/telegraf/telegraf.go
  internal/usage.go
Labels: enhancement

#6184 Add ability to exclude db/bucket tag from influxdb outputs
  plugins/outputs/influxdb/README.md
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb/influxdb.go
  plugins/outputs/influxdb_v2/README.md
  plugins/outputs/influxdb_v2/http.go
  plugins/outputs/influxdb_v2/influxdb.go
Labels: enhancement

#6179 Add uWSGI input plugin
  plugins/inputs/all/all.go
  plugins/inputs/uwsgi/README.md
  plugins/inputs/uwsgi/uwsgi.go
  plugins/inputs/uwsgi/uwsgi_test.go
Labels: new plugin

#6181 Require Kafka 0.10.2.0 or later in kafka_consumer
  plugins/inputs/kafka_consumer/README.md
  plugins/inputs/kafka_consumer/kafka_consumer.go
Labels: area/kafka, breaking change

#6137 Gather per collections stats in mongodb input plugin
  etc/telegraf.conf
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb.go
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_server.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#4435 feature: introduces `diff` and `non_negative_diff` into BasicStats Aggregator plugin
  plugins/aggregators/basicstats/README.md
  plugins/aggregators/basicstats/basicstats.go
  plugins/aggregators/basicstats/basicstats_test.go
Labels: enhancement

#6049 Grace period for metrics late for aggregation
  docs/CONFIGURATION.md
  internal/config/config.go
  internal/models/running_aggregator.go
  internal/models/running_aggregator_test.go
Labels: area/agent, bugfix

#6189 adding left string function
  plugins/processors/strings/README.md
  plugins/processors/strings/strings.go
  plugins/processors/strings/strings_test.go
Labels: enhancement

#6159 Add intermediates when verifying cert in x509 input
  plugins/inputs/x509_cert/x509_cert.go
Labels: bugfix
