Repository influxdata/telegraf, pull requests merged in 2019-06, with the labels that each got.

#5547 Add file rotation based on file age to file output plugin
  plugins/outputs/file/README.md
  plugins/outputs/file/file.go
Labels: enhancement

#5943 Ignore errors serializing metrics
  plugins/outputs/amqp/amqp.go
  plugins/outputs/cloud_pubsub/pubsub.go
  plugins/outputs/file/file.go
  plugins/outputs/instrumental/instrumental.go
  plugins/outputs/kafka/kafka.go
  plugins/outputs/kinesis/kinesis.go
  plugins/outputs/mqtt/mqtt.go
  plugins/outputs/nats/nats.go
  plugins/outputs/nsq/nsq.go
  plugins/outputs/socket_writer/socket_writer.go
  plugins/serializers/influx/influx.go
  plugins/serializers/influx/reader.go
  plugins/serializers/registry.go
Labels: bugfix

#5944 Add support for remaining file rotation options
  internal/config/config.go
  plugins/outputs/file/README.md
  plugins/outputs/file/file.go
Labels: enhancement

#5852 Add Cisco model-driven telemetry & GNMI inputs
  Gopkg.lock
  Gopkg.toml
  README.md
  docs/LICENSE_OF_DEPENDENCIES.md
  plugins/inputs/all/all.go
  plugins/inputs/cisco_telemetry_gnmi/README.md
  plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go
  plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi_test.go
  plugins/inputs/cisco_telemetry_mdt/README.md
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
Labels: new plugin

#5953 Fix race conditions in gnmi telemetry tests
  plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go
  plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi_test.go
Labels: bugfix

#5954 Make case insensitive container status comparison
  plugins/inputs/ecs/README.md
  plugins/inputs/ecs/ecs.go
Labels: bugfix, documentation

#5959 Log a warning on write if the metric buffer has overflowed
  internal/models/buffer.go
  internal/models/running_output.go
Labels: enhancement

#5955 Add source tag to hddtemp plugin
  plugins/inputs/hddtemp/README.md
  plugins/inputs/hddtemp/hddtemp.go
  plugins/inputs/hddtemp/hddtemp_test.go
Labels: enhancement

#5960 Fix double close error with log rotation
  internal/rotate/file_writer.go
Labels: bugfix

#5979 Fix race condition in cisco telemetry tests
  plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi_test.go
Labels: bugfix

#5982 Fix setting mount_points option in disk input
  plugins/inputs/disk/disk.go
Labels: bugfix

#5842 wavefront/serializer: improve performance by ~30%
  plugins/serializers/wavefront/wavefront.go
  plugins/serializers/wavefront/wavefront_test.go
Labels: enhancement, performance

#5941 Fix for #5692
  CHANGELOG.md
  Gopkg.lock
  plugins/inputs/procstat/README.md
  plugins/inputs/procstat/procstat.go
  plugins/inputs/system/ps.go
  plugins/parsers/influx/machine_test.go
  plugins/parsers/influx/parser_test.go
  plugins/serializers/influx/influx_test.go
Labels: enhancement

#5986 Omit keys when creating measurement names for GNMI telemetry
  plugins/inputs/cisco_telemetry_gnmi/cisco_telemetry_gnmi.go
Labels: bugfix

#5976 Add default url for http output
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
Labels: enhancement

#5972 Fix pid_count with systemd_unit in procstat_lookup
  plugins/inputs/procstat/procstat.go
Labels: bugfix

#5975 Support array of addressses in http_response input
  plugins/inputs/http_response/README.md
  plugins/inputs/http_response/http_response.go
Labels: enhancement

#5911 Run ServiceInputs during test mode; add --test-wait option
  agent/agent.go
  cmd/telegraf/telegraf.go
  internal/usage.go
  internal/usage_windows.go
Labels: area/agent, enhancement

#5895 Adds Date Processor Plugin
  plugins/processors/all/all.go
  plugins/processors/date/README.md
  plugins/processors/date/date.go
  plugins/processors/date/date_test.go
Labels: new plugin

#5841 graphite: reduce the memory used by GraphiteParser.Parse() by ~80%
  plugins/parsers/graphite/parser.go
Labels: enhancement

#5899 Add call to optional Init function for all plugins
  agent/agent.go
  docs/AGGREGATORS.md
  docs/INPUTS.md
  docs/OUTPUTS.md
  docs/PROCESSORS.md
  input.go
  internal/models/running_aggregator.go
  internal/models/running_input.go
  internal/models/running_output.go
  internal/models/running_processor.go
  plugins/inputs/http/http.go
  plugins/inputs/http/http_test.go
Labels: area/agent, enhancement

#5863 Allow regexp processor to mix different tags
  plugins/processors/regex/README.md
  plugins/processors/regex/regex.go
  plugins/processors/regex/regex_test.go
Labels: enhancement

#5991 Add pivot and unpivot processors
  metric/metric.go
  plugins/processors/all/all.go
  plugins/processors/pivot/README.md
  plugins/processors/pivot/pivot.go
  plugins/processors/pivot/pivot_test.go
  plugins/processors/unpivot/README.md
  plugins/processors/unpivot/unpivot.go
  plugins/processors/unpivot/unpivot_test.go
Labels: new plugin

#5997 Add starttime to php-fpm metrics
  plugins/inputs/phpfpm/phpfpm.go
  plugins/inputs/phpfpm/phpfpm_test.go
Labels: enhancement

#5998 Add missing metric in ElasticSearch
  plugins/inputs/elasticsearch/elasticsearch.go
  plugins/inputs/elasticsearch/elasticsearch_test.go
  plugins/inputs/elasticsearch/testdata_test.go
Labels: area/elasticsearch, enhancement

#5749 Collect query params in HTTP listener input plugin
  internal/config/config.go
  plugins/inputs/http_listener_v2/README.md
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
  plugins/parsers/formdata/README.md
  plugins/parsers/formdata/parser.go
  plugins/parsers/formdata/parser_test.go
  plugins/parsers/registry.go
Labels: enhancement

#4773 Docker log plugin
  plugins/inputs/all/all.go
  plugins/inputs/docker_log/README.md
  plugins/inputs/docker_log/client.go
  plugins/inputs/docker_log/docker_logs.go
Labels: area/docker, new plugin

#6006 Add support for interface field in http_response input plugin
  plugins/inputs/http_response/README.md
  plugins/inputs/http_response/http_response.go
  plugins/inputs/http_response/http_response_test.go
Labels: enhancement

#6015 fix(inputs/nginx_plus_api): swallow 404 error reporting
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics_test.go
Labels: bugfix

#5996 Container Uptime in Docker Input Plugin
  plugins/inputs/docker/README.md
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker/docker_testdata.go
Labels: enhancement

#6016 feat(inputs/docker): add better user-facing errors for API timeouts
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/errors.go
Labels: enhancement

#6000 Fix panic if pool_mode column does not exist
  plugins/inputs/pgbouncer/pgbouncer.go
Labels: bugfix

#6001 Fix double pct replacement in sysstat input
  plugins/inputs/sysstat/sysstat.go
  plugins/inputs/sysstat/sysstat_test.go
Labels: bugfix

#6008 Follow up work on docker_log input
  Gopkg.lock
  internal/docker/docker.go
  internal/docker/docker_test.go
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker_log/README.md
  plugins/inputs/docker_log/docker_log.go
  plugins/inputs/docker_log/docker_log_test.go
  plugins/inputs/docker_log/docker_logs.go
  testutil/metric.go
Labels: enhancement

#6019 Add container_id field to docker_container_status metrics
  plugins/inputs/docker/README.md
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
Labels: area/docker, bugfix

#6027 Adding TLS mutual auth supoort to jti_openconfig_telemetry plugin
  etc/telegraf.conf
  plugins/inputs/jti_openconfig_telemetry/README.md
  plugins/inputs/jti_openconfig_telemetry/openconfig_telemetry.go
Labels: enhancement

#5742 skip when utmp is missing
  plugins/inputs/system/README.md
  plugins/inputs/system/system.go
Labels: bugfix

#6040 Add device, serial_no, and wwn tags to synthetic attributes
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: bugfix

#6031 Fix parsing of remote tcp address in statsd input
  plugins/inputs/statsd/datadog.go
  plugins/inputs/statsd/statsd.go
  plugins/inputs/statsd/statsd_test.go
  testutil/metric.go
Labels: bugfix

#6044 fix typo
  plugins/inputs/jolokia2/examples/cassandra.conf
Labels: bugfix

#6004 Elasticsearch Input changes
  plugins/inputs/elasticsearch/elasticsearch.go
  plugins/inputs/elasticsearch/elasticsearch_test.go
  plugins/inputs/elasticsearch/testdata_test.go
Labels: area/elasticsearch, bugfix
