Repository influxdata/telegraf, pull requests merged in 2020-05, with the labels that each got.

#7418 Add filepath processor plugin
  README.md
  plugins/processors/all/all.go
  plugins/processors/filepath/README.md
  plugins/processors/filepath/filepath.go
  plugins/processors/filepath/filepath_test.go
  plugins/processors/filepath/filepath_test_helpers.go
  plugins/processors/filepath/filepath_windows_test.go
Labels: new plugin

#7455 Remove debug fields from spunkmetric serializer
  plugins/serializers/splunkmetric/README.md
  plugins/serializers/splunkmetric/splunkmetric.go
  plugins/serializers/splunkmetric/splunkmetric_test.go
Labels: bugfix

#7446 Fix gzip support in socket_listener with tcp sockets
  internal/content_coding.go
  internal/content_coding_test.go
  plugins/inputs/socket_listener/socket_listener.go
  plugins/inputs/socket_listener/socket_listener_test.go
Labels: bugfix

#7459 Add information about HEC JSON format limitations
  plugins/serializers/splunkmetric/README.md
Labels: documentation

#7434 Docker time stamps as metric time stamps
  plugins/inputs/docker_log/docker_log.go
  plugins/inputs/docker_log/docker_log_test.go
Labels: enhancement

#7467 Update datadog output documentation
  plugins/outputs/datadog/README.md
  plugins/outputs/datadog/datadog.go
Labels: documentation

#7390 Rework plugin tickers to prevent drift and spread write ticks
  agent/agent.go
  agent/tick.go
  agent/tick_test.go
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  internal/internal.go
Labels: area/agent, bugfix, enhancement

#7359 Sql server - ring buffer cpu v2
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
  plugins/inputs/sqlserver/sqlserver_test.go
Labels: enhancement

#7464 Add field output to date processor and integer output formats
  plugins/processors/date/README.md
  plugins/processors/date/date.go
  plugins/processors/date/date_test.go
Labels: enhancement

#7483 [processors] Add integer support to `processors.enum`
  plugins/processors/enum/README.md
  plugins/processors/enum/enum.go
  plugins/processors/enum/enum_test.go
Labels: enhancement

#7321 Mongodb: add additional metrics
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#7439 Handle multiple metrics with the same timestamp in dedup plugin
  plugins/processors/dedup/dedup.go
  plugins/processors/dedup/dedup_test.go
Labels: bugfix

#7491 Added basic authentication support to the http_response input plugin
  plugins/inputs/http_response/http_response.go
  plugins/inputs/http_response/http_response_test.go
Labels: enhancement

#7503 [output.wavefront] Added truncate_tags setting
  plugins/outputs/wavefront/README.md
  plugins/outputs/wavefront/wavefront.go
  plugins/outputs/wavefront/wavefront_test.go
Labels: area/wavefront

#7465 Update docs for execd plugins
  CONTRIBUTING.md
  README.md
Labels: documentation

#7507 Spelling
  internal/tls/config.go
  internal/tls/config_test.go
  metric/metric_test.go
  models/filter_test.go
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/eventhub_consumer/eventhub_consumer.go
  plugins/inputs/fireboard/fireboard.go
  plugins/inputs/github/github.go
  plugins/inputs/kinesis_consumer/kinesis_consumer.go
  plugins/inputs/mailchimp/chimp_api.go
  plugins/inputs/mailchimp/mailchimp_test.go
  plugins/inputs/marklogic/marklogic.go
  plugins/inputs/minecraft/internal/rcon/rcon.go
  plugins/inputs/monit/monit_test.go
  plugins/inputs/mqtt_consumer/mqtt_consumer.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics_test.go
  plugins/inputs/openntpd/openntpd_test.go
  plugins/inputs/puppetagent/puppetagent.go
  plugins/inputs/riak/riak.go
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
  plugins/inputs/solr/solr.go
  plugins/inputs/stackdriver/stackdriver.go
  plugins/inputs/tengine/tengine.go
  plugins/inputs/varnish/varnish_test.go
  plugins/inputs/vsphere/vsphere_test.go
  plugins/inputs/win_perf_counters/performance_query.go
  plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/zipkin/cmd/stress_test_write/stress_test_write.go
  plugins/outputs/kinesis/kinesis.go
  plugins/outputs/mqtt/mqtt.go
  plugins/outputs/opentsdb/opentsdb.go
  plugins/parsers/csv/parser_test.go
  plugins/parsers/wavefront/element.go
  plugins/parsers/wavefront/parser.go
  plugins/serializers/graphite/graphite.go
  scripts/build.py
  selfstat/selfstat.go
  selfstat/selfstat_test.go
Labels: bugfix

#7541 Fix negative value parsing in impi_sensor input
  plugins/inputs/ipmi_sensor/ipmi.go
  plugins/inputs/ipmi_sensor/ipmi_test.go
Labels: bugfix

#7517 Close HTTP2 connections on timeout in influxdb outputs
  internal/http.go
  internal/http_go1.11.go
  internal/http_go1.12.go
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb_v2/http.go
Labels: area/influxdb, bugfix

#7526 Fix for perfmon instance_name for #7325
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix

#7545 add character selection to separating the metric name and field for graphite tag
  config/config.go
  etc/telegraf.conf
  plugins/outputs/graphite/README.md
  plugins/outputs/graphite/graphite.go
  plugins/outputs/graphite/graphite_test.go
  plugins/outputs/instrumental/instrumental.go
  plugins/serializers/graphite/README.md
  plugins/serializers/graphite/graphite.go
  plugins/serializers/graphite/graphite_test.go
  plugins/serializers/registry.go
Labels: enhancement

#7489 Add cluster state as integer
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#7516 Use updated clock package to resolve test failures
  go.mod
  go.sum
Labels: bugfix

#7524 Spelling - sqlserver
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver

#7515 Optionally gather mongodb cluster status
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb.go
  plugins/inputs/mongodb/mongodb_server.go
Labels: area/mongodb, enhancement, performance

#7370 Set default value for fields: add defaulter processor
  plugins/processors/all/all.go
  plugins/processors/defaults/README.md
  plugins/processors/defaults/defaults.go
  plugins/processors/defaults/defaults_test.go
Labels: new plugin

#7579 Fix numeric to bool conversion in converter
  plugins/processors/converter/converter.go
  plugins/processors/converter/converter_test.go
Labels: bugfix

#7573 Fix the typo in `gcc_pu_fraction` to `gc_cpu_fraction`.
  plugins/inputs/influxdb/README.md
  plugins/inputs/influxdb/influxdb.go
  plugins/inputs/influxdb/influxdb_test.go
  plugins/inputs/kapacitor/README.md
Labels: area/influxdb, bugfix

#7572 Exclude `csv_timestamp_column` and `csv_measurement_column` from fields.
  plugins/inputs/tail/tail_test.go
  plugins/parsers/csv/README.md
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
Labels: enhancement

#7564 Update to Go 1.14.3 with testing using 1.13.11
  .circleci/config.yml
  README.md
  appveyor.yml
  docs/TLS.md
  internal/tls/common.go
  internal/tls/common_go112.go
  plugins/inputs/apcupsd/apcupsd_test.go
  plugins/inputs/clickhouse/clickhouse.go
  plugins/inputs/clickhouse/clickhouse_go1.11.go
  plugins/inputs/clickhouse/clickhouse_go1.12.go
  scripts/ci-1.12.docker
  scripts/ci-1.13.docker
  scripts/ci-1.14.docker
Labels: area/packaging

#7405 7403 - Allow to collect HTTP Headers thanks to http_response
  plugins/inputs/http_response/README.md
  plugins/inputs/http_response/http_response.go
  plugins/inputs/http_response/http_response_test.go
Labels: enhancement

#7019 NewRelic output plugin
  README.md
  go.mod
  go.sum
  plugins/outputs/all/all.go
  plugins/outputs/newrelic/README.md
  plugins/outputs/newrelic/newrelic.go
  plugins/outputs/newrelic/newrelic_test.go
Labels: new plugin

#7561 make sure parse error includes offending text
  plugins/parsers/influx/parser.go
  plugins/parsers/influx/parser_test.go
Labels: enhancement

#7540 Add processor to look up service name by port
  Makefile
  plugins/processors/all/all.go
  plugins/processors/port_name/README.md
  plugins/processors/port_name/port_name.go
  plugins/processors/port_name/port_name_test.go
  plugins/processors/port_name/services_path.go
  plugins/processors/port_name/services_path_notwindows.go
Labels: new plugin

#7593 7592 - Segmentation violation on connection failed
  plugins/inputs/http_response/http_response.go
  plugins/inputs/http_response/http_response_test.go
Labels: bugfix

#7599 Update AGGREGATORS_AND_PROCESSORS.md
  docs/AGGREGATORS_AND_PROCESSORS.md
Labels: documentation
