Repository influxdata/telegraf, pull requests merged in 2020-11, with the labels that each got.

#7938 Support for bytes encoding for "gnmi" input plugin
  plugins/inputs/gnmi/README.md
  plugins/inputs/gnmi/gnmi.go
Labels: area/gnmi

#7583 shorten config
  config/config.go
  config/config_test.go
Labels: area/configuration, wip

#8374 Fix SMART plugin to recognize all devices from config
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: area/smart, bugfix

#8370 fix: minor typos in readmes
  plugins/inputs/redis/README.md
  plugins/inputs/sqlserver/README.md
  plugins/inputs/win_perf_counters/README.md
  plugins/parsers/collectd/README.md
Labels: documentation

#8307 fix link in external plugins readme
  docs/EXTERNAL_PLUGINS.md
Labels: documentation

#7991 systemd_units: add --plain to command invocation (#7990)
  plugins/inputs/systemd_units/README.md
  plugins/inputs/systemd_units/systemd_units_linux.go
Labels: bugfix

#8400 Fix parsing of multiple files with different headers (#6318).
  plugins/parsers/csv/parser.go
Labels: bugfix

#8401 Allow to manage errors that occur in the apply function
  plugins/processors/starlark/README.md
  plugins/processors/starlark/builtins.go
  plugins/processors/starlark/starlark.go
  plugins/processors/starlark/starlark_test.go
Labels: area/starlark

#8404 Wavefront output should distinguish between retryable and non-retryable errors
  plugins/outputs/wavefront/wavefront.go
Labels: area/wavefront, bug

#8315 add kinesis output to external plugins list
  EXTERNAL_PLUGINS.md
Labels: documentation

#8436 Add DriverVersion and CUDA Version to output
  plugins/inputs/nvidia_smi/README.md
  plugins/inputs/nvidia_smi/nvidia_smi.go
  plugins/inputs/nvidia_smi/nvidia_smi_test.go
Labels: ready to merge

#8439 Show how to return a custom error with the Starlark processor
  plugins/processors/starlark/README.md
  plugins/processors/starlark/starlark_test.go
  plugins/processors/starlark/testdata/fail.star
Labels: area/starlark

#8056 Add response_time to monit plugin
  plugins/inputs/monit/README.md
  plugins/inputs/monit/monit.go
  plugins/inputs/monit/monit_test.go
Labels: enhancement

#8414 Fix tests for Windows - part 1
  .gitattributes
  Makefile
  appveyor.yml
  config/config_test.go
  config/testdata/telegraf-agent.toml
  internal/globpath/globpath_test.go
  plugins/inputs/bcache/README.md
  plugins/inputs/bcache/bcache.go
  plugins/inputs/bcache/bcache_test.go
  plugins/inputs/bcache/bcache_windows.go
  plugins/inputs/ceph/ceph_test.go
  plugins/inputs/disk/disk_test.go
  plugins/inputs/exec/exec_test.go
  plugins/inputs/execd/execd_test.go
  plugins/inputs/execd/shim/shim_posix_test.go
  plugins/inputs/file/file_test.go
  plugins/inputs/filecount/filecount_test.go
  plugins/inputs/filecount/filesystem_helpers_test.go
  plugins/inputs/filestat/filestat_test.go
  plugins/inputs/haproxy/haproxy_test.go
  plugins/inputs/http_response/http_response_test.go
  plugins/inputs/leofs/leofs_test.go
  plugins/inputs/logparser/logparser_test.go
  plugins/inputs/lustre2/lustre2.go
  plugins/inputs/lustre2/lustre2_test.go
  plugins/inputs/lustre2/lustre2_windows.go
  plugins/inputs/monit/monit_test.go
  plugins/inputs/net_response/net_response_test.go
  plugins/inputs/passenger/passenger_test.go
  plugins/inputs/phpfpm/phpfpm_test.go
  plugins/inputs/postfix/postfix.go
  plugins/inputs/postfix/postfix_test.go
  plugins/inputs/postfix/postfix_windows.go
  plugins/inputs/powerdns/powerdns_test.go
  plugins/inputs/powerdns_recursor/powerdns_recursor_test.go
  plugins/inputs/redfish/redfish_test.go
  plugins/inputs/snmp/snmp_test.go
  plugins/inputs/socket_listener/socket_listener_test.go
  plugins/inputs/syslog/nontransparent_test.go
  plugins/inputs/syslog/octetcounting_test.go
  plugins/inputs/syslog/rfc5426_test.go
  plugins/inputs/syslog/syslog.go
  plugins/inputs/syslog/syslog_test.go
  plugins/inputs/tail/tail_test.go
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
  plugins/outputs/socket_writer/socket_writer_test.go
  plugins/processors/ifname/ifname_test.go
  plugins/processors/ifname/ttl_cache.go
  plugins/processors/reverse_dns/rdnscache.go
  plugins/processors/reverse_dns/reversedns_test.go
Labels: platform/windows

#8435 Enable kafka zstd compression and idempotent writes
  plugins/common/kafka/config.go
  plugins/inputs/kafka_consumer/README.md
  plugins/inputs/kafka_consumer/kafka_consumer.go
  plugins/inputs/kafka_consumer/kafka_consumer_test.go
  plugins/outputs/kafka/README.md
  plugins/outputs/kafka/kafka.go
  plugins/outputs/kafka/kafka_test.go
Labels: area/kafka

#8461 [php-fpm] Fix possible "index out of range"
  plugins/inputs/phpfpm/phpfpm.go
Labels: bugfix

#8466 Translate snmp field values
  plugins/inputs/snmp/README.md
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_mocks_generate.go
  plugins/inputs/snmp/snmp_mocks_test.go
  plugins/inputs/snmp/snmp_test.go
Labels: area/snmp, enhancement, ready to merge

#8429 Added "name" parameter to NATS output plugin
  plugins/outputs/nats/README.md
  plugins/outputs/nats/nats.go
  plugins/outputs/nats/nats_test.go
Labels: enhancement, ready to merge

#8438 Starlark example dropbytype
  plugins/processors/starlark/README.md
  plugins/processors/starlark/starlark_test.go
  plugins/processors/starlark/testdata/drop_fields_with_unexpected_type.star
  plugins/processors/starlark/testdata/drop_string_fields.star
Labels: area/starlark

#8163 Support Riemann-Protobuff Listener
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/riemann_listener/README.md
  plugins/inputs/riemann_listener/riemann_listener.go
  plugins/inputs/riemann_listener/riemann_listener_test.go
Labels: new plugin

#7987 update godirwalk to v1.16.1 (dragonfly support)
  go.mod
  go.sum
Labels: enhancement

#8383 Add dataset metrics to zfs input
  plugins/inputs/zfs/README.md
  plugins/inputs/zfs/zfs.go
  plugins/inputs/zfs/zfs_freebsd.go
  plugins/inputs/zfs/zfs_freebsd_test.go
Labels: enhancement, ready to merge

#7971 Removed outdated information about Windows support
  plugins/inputs/procstat/README.md
Labels: platform/windows

#8447 Add the shared state to the global scope to get previous data
  plugins/processors/starlark/README.md
  plugins/processors/starlark/starlark.go
  plugins/processors/starlark/testdata/compare_metrics.star
Labels: area/starlark, enhancement

#8474 Add FLOAT64-IEEE support to inputs.modbus (#8361) (by @Nemecsek)
  plugins/inputs/modbus/README.md
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/modbus_test.go
Labels: area/iot, area/modbus, enhancement

#8432 add support for linux/ppc64le
  Makefile
  README.md
  scripts/release.sh
Labels: enhancement, ready to merge
