Repository influxdata/telegraf, pull requests merged in 2020-07, with the labels that each got.

#7762 Allow overriding the collection_jitter and precision per input
  agent/agent.go
  config/config.go
  docs/CONFIGURATION.md
  models/running_input.go
  models/running_output.go
Labels: area/agent, documentation, enhancement

#7205 Add nginx sts input plugin support
  plugins/inputs/all/all.go
  plugins/inputs/nginx_sts/README.md
  plugins/inputs/nginx_sts/nginx_sts.go
  plugins/inputs/nginx_sts/nginx_sts_test.go
Labels: new plugin

#7768 kibana: Change int64 to float64 in uptime fields
  plugins/inputs/kibana/kibana.go
  plugins/inputs/kibana/testdata_test6_5.go
Labels: bugfix

#7752 Set user agent when requesting http config
  config/config.go
Labels: enhancement

#7761 execd output
  README.md
  internal/process/process.go
  internal/process/process_posix.go
  internal/process/process_test.go
  internal/process/process_windows.go
  plugins/inputs/execd/execd_test.go
  plugins/outputs/all/all.go
  plugins/outputs/execd/README.md
  plugins/outputs/execd/examples/file/file.sh
  plugins/outputs/execd/examples/file/telegraf.conf
  plugins/outputs/execd/examples/redis/redis_influx.rb
  plugins/outputs/execd/examples/redis/redis_json.rb
  plugins/outputs/execd/examples/redis/telegraf.conf
  plugins/outputs/execd/execd.go
  plugins/outputs/execd/execd_test.go
Labels: area/exec, new plugin

#7780 Fix data race in plugins/inputs/tail/tail_test.go
  plugins/inputs/tail/tail_test.go
Labels: area/tail, bugfix

#7786 streaming processors docs update
  docs/PROCESSORS.md
Labels: documentation

#7154 inputs.ecs: add v3 metadata support.
  plugins/inputs/ecs/README.md
  plugins/inputs/ecs/client.go
  plugins/inputs/ecs/client_test.go
  plugins/inputs/ecs/ecs.go
  plugins/inputs/ecs/ecs_test.go
Labels: area/aws, enhancement

#7792 Support utf-16 in file and tail inputs
  go.mod
  go.sum
  plugins/common/encoding/decoder.go
  plugins/common/encoding/decoder_test.go
  plugins/inputs/file/file.go
  plugins/inputs/file/file_test.go
  plugins/inputs/file/testdata/mtr-utf-16be.csv
  plugins/inputs/file/testdata/mtr-utf-16le.csv
  plugins/inputs/file/testdata/mtr-utf-8.csv
  plugins/inputs/tail/README.md
  plugins/inputs/tail/tail.go
  plugins/inputs/tail/tail_test.go
  plugins/inputs/tail/testdata/cpu-utf-16be.influx
  plugins/inputs/tail/testdata/cpu-utf-16le.influx
  plugins/inputs/tail/testdata/cpu-utf-8.influx
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
  plugins/parsers/registry.go
Labels: enhancement

#7722 Traverse redfish api using resource links
  plugins/inputs/redfish/README.md
  plugins/inputs/redfish/redfish.go
  plugins/inputs/redfish/redfish_test.go
  plugins/inputs/redfish/testdata/hp_chassis.json
Labels: bugfix

#7763 Add ifname processor plugin
  internal/snmp/config.go
  internal/snmp/wrapper.go
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
  plugins/processors/all/all.go
  plugins/processors/ifname/README.md
  plugins/processors/ifname/cache.go
  plugins/processors/ifname/cache_test.go
  plugins/processors/ifname/ifname.go
  plugins/processors/ifname/ifname_test.go
Labels: new plugin

#7806 Fix markdown syntax
  plugins/inputs/execd/shim/README.md
Labels: documentation

#7810 Add minimum version for new plugins
  plugins/inputs/nginx_sts/README.md
  plugins/inputs/redfish/README.md
  plugins/outputs/execd/README.md
  plugins/outputs/newrelic/README.md
  plugins/processors/defaults/README.md
  plugins/processors/execd/README.md
  plugins/processors/filepath/README.md
  plugins/processors/ifname/README.md
  plugins/processors/port_name/README.md
  plugins/processors/reverse_dns/README.md
  plugins/processors/starlark/README.md
Labels: documentation

#7818 Fix darwin package build flags
  Makefile
Labels: area/packaging, bugfix, platform/darwin

#7816 fix bug with loading plugins in shim with no config
  plugins/common/shim/config.go
  plugins/common/shim/config_test.go
  plugins/common/shim/input_test.go
Labels: area/exec, bugfix

#7832 Edit Starlark README
  plugins/processors/starlark/README.md
Labels: documentation

#7846 update redfish docs with link
  plugins/inputs/redfish/README.md
Labels: documentation

#7853 Initialize aggregation processors
  agent/agent.go
Labels: bugfix

#7854 Log after interval has elapsed; skip short intervals
  agent/agent.go
  agent/tick.go
Labels: bugfix

#7864 add logic starlark example
  plugins/processors/starlark/README.md
  plugins/processors/starlark/testdata/number_logic.star
Labels: documentation

#7872 Recv next message after send returns EOF in gnmi input
  plugins/inputs/gnmi/gnmi.go
Labels: bugfix
