Repository influxdata/telegraf, pull requests merged in 2020-03, with the labels that each got.

#7071 Histogram aggregator: Enable non-cumulative stats
  plugins/aggregators/histogram/README.md
  plugins/aggregators/histogram/histogram.go
  plugins/aggregators/histogram/histogram_test.go
Labels: enhancement

#6969 add functionality to scrape pods per kubernetes node
  go.mod
  go.sum
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/kubernetes.go
  plugins/inputs/prometheus/kubernetes_test.go
  plugins/inputs/prometheus/prometheus.go
Labels: area/k8s, area/prometheus, enhancement

#6922 Adding a threaded parsing option for statsD input plugin
  plugins/inputs/statsd/statsd.go
  plugins/inputs/statsd/statsd_test.go
Labels: area/statsd, enhancement

#6974 Influxdb listener refactor
  internal/http.go
  metric/builder.go
  metric/metric.go
  plugins/inputs/influxdb_listener/README.md
  plugins/inputs/influxdb_listener/bufferpool.go
  plugins/inputs/influxdb_listener/http_listener.go
  plugins/inputs/influxdb_listener/http_listener_test.go
  plugins/inputs/influxdb_listener/influxdb_listener.go
  plugins/inputs/influxdb_listener/influxdb_listener_benchmark_test.go
  plugins/inputs/influxdb_listener/influxdb_listener_test.go
  plugins/outputs/health/health.go
  plugins/outputs/prometheus_client/prometheus_client.go
  plugins/parsers/csv/parser.go
  plugins/parsers/dropwizard/parser.go
  plugins/parsers/dropwizard/parser_test.go
  plugins/parsers/influx/handler.go
  plugins/parsers/influx/machine.go
  plugins/parsers/influx/machine.go.rl
  plugins/parsers/influx/machine_test.go
  plugins/parsers/influx/parser.go
  plugins/parsers/influx/parser_test.go
Labels: bugfix, enhancement

#6441 Add ClickHouse input plugin (instead of #3894)
  .gitignore
  plugins/inputs/all/all.go
  plugins/inputs/clickhouse/README.md
  plugins/inputs/clickhouse/clickhouse.go
  plugins/inputs/clickhouse/clickhouse_go1.11.go
  plugins/inputs/clickhouse/clickhouse_go1.12.go
  plugins/inputs/clickhouse/clickhouse_test.go
  plugins/inputs/clickhouse/dev/dhparam.pem
  plugins/inputs/clickhouse/dev/docker-compose.yml
  plugins/inputs/clickhouse/dev/telegraf.conf
  plugins/inputs/clickhouse/dev/telegraf_ssl.conf
  plugins/inputs/clickhouse/dev/tls_settings.xml
Labels: new plugin

#7118 Fixed a spelling error in the SNMP field example
  plugins/inputs/snmp/README.md
Labels: area/snmp, documentation

#7098 Update stackdriver plugins to reflect new product naming
  README.md
  plugins/inputs/stackdriver/README.md
  plugins/outputs/stackdriver/README.md
Labels: documentation

#7120 fix(salesforce): fix typo in readme
  plugins/inputs/salesforce/README.md
Labels: documentation

#7049 Add support for converting tag or field to measurement in converter processor
  plugins/processors/converter/README.md
  plugins/processors/converter/converter.go
  plugins/processors/converter/converter_test.go
Labels: enhancement

#7108 Check license of dependencies file for changes
  .circleci/config.yml
  Makefile
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  scripts/check-deps.sh
Labels: area/packaging

#6367 plugins/inputs: New input for Wireguard server
  README.md
  etc/telegraf.conf
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/wireguard/README.md
  plugins/inputs/wireguard/wireguard.go
  plugins/inputs/wireguard/wireguard_test.go
Labels: new plugin

#7132 Document port specification in postgres input plugins.
  etc/telegraf.conf
  plugins/inputs/pgbouncer/README.md
  plugins/inputs/postgresql/README.md
  plugins/inputs/postgresql_extensible/README.md
Labels: area/postgresql, documentation

#7133 logging: Fix file rotation mechanism.
  internal/rotate/file_writer.go
  internal/rotate/file_writer_test.go
Labels: area/logging, bugfix

#7103 Database io additional tags & fields
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, enhancement

#7142 Add topic tag options to kafka output
  plugins/inputs/kafka_consumer/kafka_consumer.go
  plugins/outputs/kafka/README.md
  plugins/outputs/kafka/kafka.go
  plugins/outputs/kafka/kafka_test.go
Labels: area/kafka, enhancement

#7148 modbus to support scaling int32 and float32-ieee
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/modbus_test.go
Labels: bugfix

#7143 fix concurrency panic in ntpq input. Closes #7101
  plugins/inputs/ntpq/ntpq.go
  plugins/inputs/ntpq/ntpq_test.go
Labels: bugfix

#7119 Fix internal metrics for output split into multiple lines
  internal/models/buffer.go
  internal/models/running_output_test.go
Labels: bugfix

#7141 Add support for setting retention policy using tag
  plugins/outputs/influxdb/README.md
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb/http_test.go
  plugins/outputs/influxdb/influxdb.go
Labels: area/influxdb, enhancement

#7152 Add versioning to example readme
  plugins/inputs/EXAMPLE_README.md
Labels: documentation

#7087 feat: geo processor plugin
  go.mod
  go.sum
  plugins/processors/all/all.go
  plugins/processors/geo/README.md
  plugins/processors/geo/geo.go
  plugins/processors/geo/geo_test.go
Labels: new plugin

#4112 Arista LANZ consumer multi server. Production tested.
  README.md
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/lanz/README.md
  plugins/inputs/lanz/lanz.go
  plugins/inputs/lanz/lanz_test.go
Labels: new plugin, vert/network

#7174 Allow using name_* modificators for output plugins
  docs/CONFIGURATION.md
  internal/config/config.go
  internal/models/running_output.go
  internal/models/running_output_test.go
Labels: enhancement

#6928 Azure IoT Hub / Azure Event Hub input plugin (with go modules)
  README.md
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/eventhub/README.md
  plugins/inputs/eventhub/eventhub.go
Labels: area/azure, new plugin, vert/iot

#7163 Adding Database IO Tempdb per Azure DB collection, Fixing PerfmonV2 collection for on-prem
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix

#7144 SqlServer Schedulers - Dynamic SQL for compatibility pre SQL-2016
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix

#7150 Add option for explicitly including queries in sqlserver input plugin.
  etc/telegraf.conf
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
  plugins/inputs/sqlserver/sqlserver_test.go
Labels: area/sqlserver, enhancement

#6792 Add dedup processor
  plugins/processors/all/all.go
  plugins/processors/dedup/README.md
  plugins/processors/dedup/dedup.go
  plugins/processors/dedup/dedup_test.go
Labels: new plugin

#7188 Add sFlow input plugin
  plugins/inputs/EXAMPLE_README.md
  plugins/inputs/all/all.go
  plugins/inputs/sflow/README.md
  plugins/inputs/sflow/decoder.go
  plugins/inputs/sflow/decoder/directives.go
  plugins/inputs/sflow/decoder/directives_test.go
  plugins/inputs/sflow/decoder/funcs.go
  plugins/inputs/sflow/decoder/ops.go
  plugins/inputs/sflow/decoder/ops_test.go
  plugins/inputs/sflow/decoder_test.go
  plugins/inputs/sflow/sflow.go
  plugins/inputs/sflow/sflow_test.go
Labels: new plugin

#7198 Remove init checks for valid label and field selectors
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  plugins/inputs/prometheus/prometheus.go
Labels: bugfix

#7199 Update google.cloud.go to latest
  .circleci/config.yml
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  scripts/check-deps.sh
Labels: bugfix

#7200 Update github.com/prometheus/client_golang to latest
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
Labels: bugfix

#7211 Fix encoding of job names in jenkins input plugin.
  plugins/inputs/jenkins/jenkins.go
  plugins/inputs/jenkins/jenkins_test.go
Labels: bugfix

#6905 Add commands stats to mongodb plugin.
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#7193 Add additional concurrent transactions information
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement

#7224 Fix 'nil' file created by Makefile on Windows
  Makefile
Labels: bugfix, platform/windows

#7223 Add ability to specify HTTP Headers in http_listener_v2 which will be…
  plugins/inputs/http_listener_v2/README.md
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
Labels: enhancement

#7140 Apply ping deadline to dns lookup
  plugins/inputs/ping/ping.go
  plugins/inputs/ping/ping_test.go
Labels: enhancement

#7225 [inputs/modbus] Add support for 64-bit values
  plugins/inputs/modbus/README.md
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/modbus_test.go
Labels: area/modbus, enhancement

#7210 Add limit to number of undelivered lines to read ahead in tail
  plugins/inputs/tail/README.md
  plugins/inputs/tail/tail.go
  plugins/inputs/tail/tail_test.go
Labels: enhancement

#7231 [inputs/modbus] Add possibility to specify measurement per register
  plugins/inputs/modbus/README.md
  plugins/inputs/modbus/modbus.go
Labels: enhancement

#7136 Support multiple templates for graphite serializers
  internal/config/config.go
  plugins/outputs/graphite/README.md
  plugins/outputs/graphite/graphite.go
  plugins/outputs/graphite/graphite_test.go
  plugins/outputs/instrumental/instrumental.go
  plugins/serializers/graphite/README.md
  plugins/serializers/graphite/graphite.go
  plugins/serializers/graphite/graphite_test.go
  plugins/serializers/registry.go
Labels: enhancement

#7242 FIX: Perfmon collector adding OPTION RECOMPILE for perf reasons
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix
