Repository influxdata/telegraf, pull requests merged in 2020-02, with the labels that each got.

#6981 Expire metrics on query in addition to on add.
  plugins/outputs/prometheus_client/v2/collector.go
Labels: area/prometheus, bugfix

#6983 Document the behavior of an unset routing key
  plugins/outputs/kafka/README.md
  plugins/outputs/kafka/kafka.go
Labels: area/kafka, documentation

#6982 processor/strings: add support for `title` convertor
  plugins/processors/strings/README.md
  plugins/processors/strings/strings.go
  plugins/processors/strings/strings_test.go
Labels: enhancement

#6494 Support multiple tags for RabbitMQ routing tag topic
  plugins/processors/template/README.md
  plugins/processors/template/template.go
  plugins/processors/template/template_metric.go
  plugins/processors/template/template_test.go
Labels: area/rabbitmq, enhancement

#6984 Use require in cisco mdt tests to avoid follow on errors
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
Labels: bugfix

#6997 Parse NaN values from summary types in prometheus input
  plugins/inputs/prometheus/parser.go
  plugins/inputs/prometheus/prometheus_test.go
Labels: bugfix

#7005 Search for chronyc only when chrony input plugin is enabled
  plugins/inputs/chrony/chrony.go
Labels: bugfix

#7002 Fix float conversion and Connection issue
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/modbus_test.go
Labels: bugfix

#6993 issue#6992 - Add support for MDB database information
  plugins/inputs/openldap/openldap.go
Labels: enhancement

#6820 Fixes for two pgbouncer issues.
  plugins/inputs/pgbouncer/pgbouncer.go
  plugins/inputs/postgresql/service.go
Labels: bugfix

#6957 Added new fields for Jenkins Total and Busy executors
  plugins/inputs/jenkins/README.md
  plugins/inputs/jenkins/jenkins.go
  plugins/inputs/jenkins/jenkins_test.go
Labels: enhancement

#7036 fix typo
  plugins/inputs/http_response/README.md
Labels: documentation

#7035 Fix dash to underscore replacement when handling embedded tags in Cisco MDT
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
Labels: bugfix

#7031 Add support for freebsd/arm64
  go.mod
  go.sum
Labels: enhancement

#7039 add process created time to procstat
  plugins/inputs/procstat/README.md
  plugins/inputs/procstat/process.go
  plugins/inputs/procstat/procstat.go
  plugins/inputs/procstat/procstat_test.go
Labels: area/procstat, enhancement

#7052 Update github.com/safchain/ethtool
  go.mod
  go.sum
Labels: bugfix

#7022 update nats dependencies to modern versions
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/nats/nats.go
  plugins/inputs/nats_consumer/README.md
  plugins/inputs/nats_consumer/nats_consumer.go
  plugins/outputs/nats/README.md
  plugins/outputs/nats/nats.go
Labels: enhancement

#7060 Missing perf counters fix
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, bugfix

#7056 Use add time for prometheus expiration calculation
  plugins/outputs/prometheus_client/v2/collector.go
  plugins/serializers/prometheus/collection.go
  plugins/serializers/prometheus/collection_test.go
  plugins/serializers/prometheus/prometheus.go
Labels: area/prometheus, bugfix

#7065 Add: apcupsd metrics
  plugins/inputs/apcupsd/README.md
  plugins/inputs/apcupsd/apcupsd.go
  plugins/inputs/apcupsd/apcupsd_test.go
Labels: enhancement

#7077 Fixes inconsistency with input error counting
  agent/accumulator.go
  agent/accumulator_test.go
  agent/agent.go
  internal/models/log.go
  internal/models/log_test.go
  internal/models/running_aggregator.go
  internal/models/running_input.go
  internal/models/running_input_test.go
  internal/models/running_output.go
  internal/models/running_processor.go
  plugins/inputs/cloud_pubsub_push/pubsub_push_test.go
Labels: area/agent, bugfix

#7079 Use Go 1.13.8 to build official packages
  .circleci/config.yml
  Makefile
  appveyor.yml
  scripts/ci-1.12.docker
  scripts/ci-1.13.docker
Labels: area/packaging, bugfix

#7063 Input prometheus, use the same timestamp per call if no time is provided
  plugins/inputs/prometheus/parser.go
Labels: area/prometheus, bugfix

#7084 Add RabbitMQ slave_nodes and synchronized_slave_nodes metrics.
  plugins/inputs/rabbitmq/README.md
  plugins/inputs/rabbitmq/rabbitmq.go
  plugins/inputs/rabbitmq/rabbitmq_test.go
  plugins/inputs/rabbitmq/testdata/queues.json
Labels: area/rabbitmq, enhancement

#7086 fix injest typo
  etc/telegraf.conf
  plugins/outputs/exec/README.md
  plugins/outputs/exec/exec.go
Labels: area/exec

#4424 Add an exec daemon plugin
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/execd/README.md
  plugins/inputs/execd/examples/count.go
  plugins/inputs/execd/examples/count.rb
  plugins/inputs/execd/examples/count.sh
  plugins/inputs/execd/execd.go
  plugins/inputs/execd/execd_unix.go
  plugins/inputs/execd/execd_win.go
Labels: new plugin

#7089 Allow globs in FPM unix socket paths
  plugins/inputs/phpfpm/README.md
  plugins/inputs/phpfpm/phpfpm.go
  plugins/inputs/phpfpm/phpfpm_test.go
Labels: enhancement
