Repository influxdata/telegraf, pull requests merged in 2021-12, with the labels that each got.

#10165 fix: sysstat use CreateTemp versus hard-coded filename
  plugins/inputs/sysstat/sysstat.go
Labels: fix, ready for final review

#10112 fix #10027
  plugins/inputs/cloudwatch/cloudwatch.go
Labels: fix

#10199 fix: sync on init to run it once for safety
  internal/snmp/translate.go
Labels: area/snmp, fix, plugin/input

#10200 feat: Implement deprecation infrastructure
  .markdownlint.yml
  Makefile
  cmd/telegraf/telegraf.go
  config/config.go
  config/deprecation.go
  docs/COMMANDS_AND_FLAGS.md
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  internal/internal.go
  internal/usage.go
  plugin.go
  plugins/aggregators/deprecations.go
  plugins/inputs/deprecations.go
  plugins/inputs/http_response/http_response.go
  plugins/outputs/deprecations.go
  plugins/processors/deprecations.go
Labels: feat

#10195 chore: remove triggering update-config bot in CI
  .circleci/config.yml
  scripts/update_config.sh
Labels: ready for final review, chore

#10203 fix: Revert unintented corruption of the Makefile from #10200.
  Makefile
Labels: fix

#9616 fix: windows service - graceful shutdown of telegraf
  cmd/telegraf/telegraf_windows.go
Labels: fix, ready for final review

#10208 fix: mqtt topic extracting no longer requires all three fields
  plugins/inputs/mqtt_consumer/mqtt_consumer.go
  plugins/inputs/mqtt_consumer/mqtt_consumer_test.go
Labels: fix, ready for final review

#10215 docs: address documentation gap when running telegraf in k8s
  plugins/inputs/prometheus/README.md
Labels: docs

#10191 chore: Forbids "log" package only for aggregators, inputs, outputs, parsers and processors
  .golangci.yml
  plugins/common/logrus/hook.go
  plugins/common/shim/config.go
  plugins/common/shim/logger.go
Labels: needs design review

#10007 fix: parallelism fix for ifname processor
  plugins/processors/ifname/ifname.go
Labels: area/snmp, fix, ready for final review, plugin/processor

#10099 fix: pool detection and metrics gathering for ZFS >= 2.1.x
  plugins/inputs/zfs/README.md
  plugins/inputs/zfs/zfs_linux.go
  plugins/inputs/zfs/zfs_linux_test.go
Labels: fix, ready for final review, plugin/input

#10209 fix: ensure graylog spec fields not prefixed with '_'
  plugins/outputs/graylog/graylog.go
  plugins/outputs/graylog/graylog_test.go
Labels: fix

#10221 fix: json_v2 parser timestamp setting
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/testdata/multiple_arrays_in_object/expected.out
  plugins/parsers/json_v2/testdata/object_timestamp/expected.out
  plugins/parsers/json_v2/testdata/object_timestamp/input.json
  plugins/parsers/json_v2/testdata/object_timestamp/telegraf.conf
Labels: fix

#10230 fix: Sudden close of Telegraf caused by OPC UA input plugin
  go.mod
  go.sum
Labels: fix, ready for final review

#10150 feat: Add SMART plugin concurrency configuration option, nvme-cli v1.14+ support and lint fixes.
  plugins/inputs/smart/README.md
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: fix, area/smart

#10206 feat: Optimize locking for SNMP MIBs loading.
  internal/snmp/translate.go
  plugins/inputs/snmp/snmp_test.go
Labels: feat, area/snmp, ready for final review, plugin/input

#10214 fix: eliminate MIB dependency for ifname processor
  plugins/processors/ifname/ifname.go
  plugins/processors/ifname/ifname_test.go
Labels: area/snmp, fix, ready for final review, plugin/processor

#10205 fix: Print loaded plugins and deprecations for once and test
  cmd/telegraf/telegraf.go
  docs/COMMANDS_AND_FLAGS.md
  internal/usage.go
Labels: fix, area/agent, ready for final review

#10106 feat: add nomad input plugin
  plugins/inputs/all/all.go
  plugins/inputs/nomad/README.md
  plugins/inputs/nomad/nomad.go
  plugins/inputs/nomad/nomad_metrics.go
  plugins/inputs/nomad/nomad_test.go
  plugins/inputs/nomad/testdata/response_key_metrics.json
Labels: new plugin, ready for final review, plugin/input

#10196 fix: Implement NaN and inf handling for elasticsearch output
  plugins/outputs/elasticsearch/README.md
  plugins/outputs/elasticsearch/elasticsearch.go
  plugins/outputs/elasticsearch/elasticsearch_test.go
Labels: area/elasticsearch, fix, ready for final review, plugin/output

#10231 feat: Modbus add per-request tags
  plugins/inputs/modbus/README.md
  plugins/inputs/modbus/configuration_register.go
  plugins/inputs/modbus/configuration_request.go
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/modbus_test.go
  plugins/inputs/modbus/request.go
Labels: feat

#10246 fix: Make telegraf compile on Windows with golang 1.16.2
  plugins/inputs/modbus/configuration.go
  plugins/inputs/modbus/configuration_register.go
  plugins/inputs/modbus/configuration_request.go
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/modbus_openbsd.go
  plugins/inputs/modbus/modbus_test.go
  plugins/inputs/modbus/request.go
  plugins/inputs/modbus/type_conversions.go
  plugins/inputs/modbus/type_conversions16.go
  plugins/inputs/modbus/type_conversions32.go
  plugins/inputs/modbus/type_conversions64.go
Labels: fix

#10202 feat(http): support aws prometheus
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
  plugins/outputs/http/http_test.go
Labels: ready for final review

#10198 feat: add Vault input plugin
  plugins/inputs/all/all.go
  plugins/inputs/vault/README.md
  plugins/inputs/vault/testdata/response_key_metrics.json
  plugins/inputs/vault/vault.go
  plugins/inputs/vault/vault_metrics.go
  plugins/inputs/vault/vault_test.go
Labels: feat, ready for final review, plugin/input

#10132 fix(http_listener_v2): fix panic on close
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
Labels: fix, ready for final review

#10188 fix: Handle duplicate registration of protocol-buffer files gracefully.
  plugins/parsers/xpath/protocolbuffer_document.go
Labels: fix

#9970 Restart service if it is already running and upgraded via RPM
  scripts/rpm/post-remove.sh
Labels: fix

#10263 feat: Update underlying KNX library to support new types.
  go.mod
  go.sum
Labels: feat, area/iot, plugin/input

#10272 fix: use sha256 for RPM digest
  Makefile
Labels: fix

#10243 feat(input.kibana): add heap_size_limit field
  plugins/inputs/kibana/README.md
  plugins/inputs/kibana/kibana.go
  plugins/inputs/kibana/testdata_test6_5.go
Labels: feat, ready for final review

#10252 feat: Add option to disable Wavefront prefix conversion
  config/config.go
  plugins/serializers/registry.go
  plugins/serializers/wavefront/README.md
  plugins/serializers/wavefront/wavefront.go
Labels: feat, area/wavefront, ready for final review, plugin/output

#10225 fix: Flush wavefront output sender on error to clean up broken connections
  go.mod
  go.sum
  plugins/outputs/wavefront/wavefront.go
Labels: fix, area/wavefront, ready for final review

#10042 feat: Add Redis Sentinel input plugin
  plugins/inputs/all/all.go
  plugins/inputs/redis_sentinel/README.md
  plugins/inputs/redis_sentinel/redis_sentinel.go
  plugins/inputs/redis_sentinel/redis_sentinel_test.go
  plugins/inputs/redis_sentinel/redis_sentinel_types.go
  plugins/inputs/redis_sentinel/testdata/sentinel.info.response
Labels: fix, new plugin, ready for final review, plugin/input

#10268 fix: inputs.snmp to respect number of retries configured
  internal/snmp/wrapper.go
Labels: area/snmp, fix, plugin/input

#10273 fix: run go mod tidy
  go.sum
Labels: fix

#10274 fix: run gofmt
  plugins/outputs/wavefront/wavefront.go
Labels: fix

#10239 feat: support darwin arm64
  .circleci/config.yml
  Makefile
  docs/NIGHTLIES.md
  scripts/mac-signing.sh
Labels: ready for final review

#10279 fix: mark TestGatherUDPCert as an integration test
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: fix

#10288 fix: Fix panic in parsers due to missing Log
  config/config.go
Labels: fix, plugin/parser

#10293 fix: mac signing issue with arm64
  scripts/mac-signing.sh
Labels: fix

#10301 fix: panic is no mibs folder is found
  internal/snmp/translate.go
Labels: fix

#10299 fix: check index before assignment
  internal/snmp/translate.go
  plugins/inputs/snmp/snmp_test.go
Labels: area/snmp, fix, ready for final review

#10295 fix: grab table columns more accurately
  internal/snmp/translate.go
Labels: fix

#10303 fix: panic due to no module
  internal/snmp/translate.go
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
Labels: fix

#10296 fix: Fix panic in logparser due to missing Log.
  plugins/inputs/logparser/logparser.go
Labels: fix

#10307 feat: Improve error logging on plugin initialization
  agent/agent.go
Labels: feat, area/agent, ready for final review

#10220 feat: Add timeout-setting to Graylog-plugin
  plugins/inputs/graylog/README.md
  plugins/inputs/graylog/graylog.go
Labels: feat, ready for final review, plugin/input

#10313 chore: cleanup go.mod
  go.mod
Labels: ready for final review, chore

#10310 chore: update Go version to 1.17.5
  .circleci/config.yml
  Makefile
  scripts/ci-1.17.docker
  scripts/installgo_mac.sh
  scripts/installgo_windows.sh
Labels: ready for final review, chore

#10311 chore: update mac signing job to use latest xcode
  .circleci/config.yml
Labels: ready for final review, chore

#10321 fix: do not require networking during tests
  plugins/inputs/snmp/snmp_test.go
  plugins/processors/reverse_dns/reversedns_test.go
Labels: fix, ready for final review

#10323 chore: add logs section for bug reports
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: chore

#10314 chore: release packaging run in parallel
  .circleci/config.yml
Labels: chore

#9432 feat: reworked varnish_cache plugin
  plugins/inputs/varnish/README.md
  plugins/inputs/varnish/test_data/varnish4_4.json
  plugins/inputs/varnish/test_data/varnish6.2.1_reload.json
  plugins/inputs/varnish/test_data/varnish6.6.json
  plugins/inputs/varnish/test_data/varnish_types.json
  plugins/inputs/varnish/test_data/varnish_v1_reload.txt
  plugins/inputs/varnish/test_data/varnishadm-200.json
  plugins/inputs/varnish/test_data/varnishadm-reload.json
  plugins/inputs/varnish/varnish.go
  plugins/inputs/varnish/varnish_test.go
Labels: feat, ready for final review, plugin/input

#10324 docs: add note about dpdk and socket availability
  plugins/inputs/dpdk/README.md
Labels: docs

#10329 fix: Fix warning output when running with --test
  cmd/telegraf/telegraf.go
Labels: fix, ready for final review

#10332 fix: update djherbis/times and fix dependabot
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/directory_monitor/directory_monitor.go
Labels: fix, ready for final review

#3649 feat: socketstat input plugin
  plugins/inputs/all/all.go
  plugins/inputs/socketstat/README.md
  plugins/inputs/socketstat/socketstat.go
  plugins/inputs/socketstat/socketstat_test.go
  plugins/inputs/socketstat/socketstat_windows.go
  plugins/inputs/socketstat/testdata/tcp_no_sockets.txt
  plugins/inputs/socketstat/testdata/tcp_traffic.txt
  plugins/inputs/socketstat/testdata/udp_no_sockets.txt
  plugins/inputs/socketstat/testdata/udp_traffic.txt
Labels: new plugin, ready for final review, plugin/input

#10267 feat: Add option to skip errors during CSV parsing
  config/config.go
  plugins/parsers/csv/README.md
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
  plugins/parsers/registry.go
Labels: feat, ready for final review, plugin/parser

#10097 fix(outputs/stackdriver): cumulative interval start times
  plugins/outputs/stackdriver/README.md
  plugins/outputs/stackdriver/counter_cache.go
  plugins/outputs/stackdriver/counter_cache_test.go
  plugins/outputs/stackdriver/stackdriver.go
  plugins/outputs/stackdriver/stackdriver_test.go
Labels: fix, ready for final review, plugin/output

#9710 feat: add option to disable prepared statements for PostgreSQL
  plugins/inputs/postgresql/README.md
  plugins/inputs/postgresql/postgresql.go
  plugins/inputs/postgresql/service.go
  plugins/inputs/postgresql_extensible/README.md
  plugins/inputs/postgresql_extensible/postgresql_extensible.go
Labels: feat, area/postgresql, ready for final review

#9822 feat: add exclude_root_certs option to x509_cert plugin
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: feat, ready for final review

#10322 fix: snmp marshal error
  internal/snmp/translate.go
Labels: area/snmp, fix

#10258 feat: add consul metrics input plugin
  plugins/inputs/all/all.go
  plugins/inputs/consul_metrics/README.md
  plugins/inputs/consul_metrics/consul_metrics.go
  plugins/inputs/consul_metrics/consul_metrics_test.go
  plugins/inputs/consul_metrics/consul_structs.go
  plugins/inputs/consul_metrics/testdata/response_key_metrics.json
Labels: feat, area/consul, ready for final review, plugin/input

#10262 feat: add builds for riscv64
  .circleci/config.yml
  Makefile
  docs/NIGHTLIES.md
Labels: feat

#10333 chore: run release signing jobs at the same time
  .circleci/config.yml
  scripts/mac-signing.sh
Labels: chore

#10316 feat: Add more functionality to template processor
  plugins/processors/template/README.md
  plugins/processors/template/template_metric.go
  plugins/processors/template/template_test.go
Labels: feat, ready for final review, plugin/processor

#10255 fix: Update GroundWork SDK and improve logging
  go.mod
  go.sum
  plugins/outputs/groundwork/README.md
  plugins/outputs/groundwork/groundwork.go
  plugins/outputs/groundwork/groundwork_test.go
Labels: fix, ready for final review, plugin/output

#10344 chore: remove "i386" test job
  .circleci/config.yml
Labels: chore

#10343 fix: update go-ldap to v3.4.1
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/openldap/openldap.go
  plugins/inputs/openldap/openldap_test.go
Labels: fix

#10342 chore: use 4 cores on linux systems
  .circleci/config.yml
Labels: chore

#9782 feat: add mock input plugin
  plugins/inputs/all/all.go
  plugins/inputs/mock/README.md
  plugins/inputs/mock/mock.go
  plugins/inputs/mock/mock_test.go
Labels: feat, new plugin, ready for final review, plugin/input
