Repository influxdata/telegraf, pull requests merged in 2021-03, with the labels that each got.

#8902 Fix max_repetitions signedness issues
  go.mod
  go.sum
  internal/snmp/config.go
Labels: area/snmp, bugfix, ready to merge

#8703 Use consistent container name in docker input plugin
  plugins/inputs/docker/docker.go
Labels: area/docker, enhancement, ready to merge

#8828 Add MessagePack output data format
  README.md
  docs/DATA_FORMATS_OUTPUT.md
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/serializers/msgpack/README.md
  plugins/serializers/msgpack/metric.go
  plugins/serializers/msgpack/metric_gen.go
  plugins/serializers/msgpack/metric_gen_test.go
  plugins/serializers/msgpack/metric_test.go
  plugins/serializers/msgpack/msgpack.go
  plugins/serializers/msgpack/msgpack_test.go
  plugins/serializers/registry.go
Labels: enhancement, new plugin, plugin/serializer, ready to merge

#8655 SqlServer - Modified how default server list is set
  plugins/inputs/sqlserver/sqlserver.go
Labels: area/sqlserver, enhancement, ready to merge

#8450 plugin: output loki
  plugins/outputs/all/all.go
  plugins/outputs/loki/README.md
  plugins/outputs/loki/loki.go
  plugins/outputs/loki/loki_test.go
  plugins/outputs/loki/stream.go
  plugins/outputs/loki/stream_test.go
Labels: new plugin, plugin/output, ready to merge

#8397 Dynatrace Plugin: Make conversion to counters possible / Changed large bulk handling
  plugins/outputs/dynatrace/README.md
  plugins/outputs/dynatrace/dynatrace.go
Labels: enhancement, ready to merge

#8852 Add Starlark script for outputting Line Protocol shape...for sizing
  plugins/processors/starlark/testdata/schema_sizing.star
Labels: enhancement, ready to merge

#8751 Adding a new directory monitor input plugin.
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/directory_monitor/README.md
  plugins/inputs/directory_monitor/directory_monitor.go
  plugins/inputs/directory_monitor/directory_monitor_test.go
Labels: new plugin, plugin/input

#8887 Add PPID field to procstat input plugin
  plugins/inputs/procstat/process.go
  plugins/inputs/procstat/procstat.go
  plugins/inputs/procstat/procstat_test.go
Labels: enhancement

#8929 Switching kinesis output plugin to use telegraf.Logger
  plugins/outputs/kinesis/kinesis.go
  plugins/outputs/kinesis/kinesis_test.go
Labels: enhancement, plugin/output, ready to merge

#8398 Sensu Go Output Plugin for Telegraf
  README.md
  go.mod
  go.sum
  plugins/outputs/all/all.go
  plugins/outputs/sensu/README.md
  plugins/outputs/sensu/sensu.go
  plugins/outputs/sensu/sensu_test.go
Labels: new plugin, plugin/output, ready to merge

#7312 [plugins/input/docker] Make perdevice affect also cpu and add class granularity through perdevice_include/total_include
  plugins/inputs/docker/README.md
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  testutil/accumulator.go
  testutil/testutil.go
Labels: area/docker, enhancement, ready to merge

#8525 Add CSGO SRCDS input plugin
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/csgo/README.md
  plugins/inputs/csgo/csgo.go
  plugins/inputs/csgo/csgo_test.go
Labels: new plugin, plugin/input, ready to merge

#3762 Add Derivative Aggregator Plugin
  plugins/aggregators/all/all.go
  plugins/aggregators/derivative/README.md
  plugins/aggregators/derivative/derivative.go
  plugins/aggregators/derivative/derivative_test.go
Labels: new plugin, plugin/aggregator, ready to merge

#8834 Input plugin for RavenDB
  README.md
  etc/telegraf.conf
  plugins/inputs/all/all.go
  plugins/inputs/ravendb/README.md
  plugins/inputs/ravendb/ravendb.go
  plugins/inputs/ravendb/ravendb_dto.go
  plugins/inputs/ravendb/ravendb_test.go
  plugins/inputs/ravendb/testdata/collections_full.json
  plugins/inputs/ravendb/testdata/collections_min.json
  plugins/inputs/ravendb/testdata/databases_full.json
  plugins/inputs/ravendb/testdata/databases_min.json
  plugins/inputs/ravendb/testdata/indexes_full.json
  plugins/inputs/ravendb/testdata/indexes_min.json
  plugins/inputs/ravendb/testdata/server_full.json
  plugins/inputs/ravendb/testdata/server_min.json
Labels: new plugin, plugin/input

#8923 Clearing LGTM alerts and warnings
  .lgtm.yml
  README.md
  plugins/inputs/github/github.go
  plugins/inputs/jolokia2/client.go
  plugins/inputs/riemann_listener/riemann_listener.go
  plugins/outputs/http/http.go
  plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
  plugins/parsers/prometheus/parser.go
Labels: enhancement, ready to merge

#8931 Add XML parser using XPath queries
  config/config.go
  docs/DATA_FORMATS_INPUT.md
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/parsers/registry.go
  plugins/parsers/xml/README.md
  plugins/parsers/xml/parser.go
  plugins/parsers/xml/parser_test.go
  plugins/parsers/xml/testcases/multisensor.xml
  plugins/parsers/xml/testcases/multisensor_explicit_basic.conf
  plugins/parsers/xml/testcases/multisensor_explicit_batch.conf
  plugins/parsers/xml/testcases/multisensor_selection_batch.conf
  plugins/parsers/xml/testcases/openweathermap.conf
  plugins/parsers/xml/testcases/openweathermap_5d.xml
  testutil/file.go
Labels: enhancement, new plugin, plugin/parser

#8938 fix: Beat readme title
  plugins/inputs/beat/README.md
Labels: bugfix, ready to merge

#8939 chore: update docs link in influxdbv2listener
  plugins/inputs/influxdb_v2_listener/README.md
Labels: documentation

#4615 Nfsclient input: (Reopen of PR 1491 and 1684)
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/nfsclient/README.md
  plugins/inputs/nfsclient/nfsclient.go
  plugins/inputs/nfsclient/nfsclient_test.go
  plugins/inputs/nfsclient/testdata/mountstats
Labels: new plugin, plugin/input, ready to merge

#8934 Add field key length output by field type in schema_sizing Starlark script
  plugins/processors/starlark/testdata/schema_sizing.star
Labels: enhancement

#8918 Correct Q+A about state
  plugins/processors/starlark/README.md
Labels: area/starlark, ready to merge

#8954 Fix max open requests to one if idempotent writes is set to true
  plugins/common/kafka/config.go
Labels: bugfix

#8943 NFS Client input plugin README cleanup
  plugins/inputs/nfsclient/README.md
Labels: documentation

#8675 Add Starlark parsing example of nested JSON
  plugins/processors/starlark/testdata/json_nested.star
Labels: area/starlark, documentation, ready to merge

#8960 Fix output name to match directory name for sensu output plugin
  README.md
  etc/telegraf.conf
  plugins/outputs/sensu/README.md
  plugins/outputs/sensu/sensu.go
Labels: bugfix

#8930 Writing unit tests for Kinesis output plugin Write method
  plugins/outputs/kinesis/kinesis.go
  plugins/outputs/kinesis/kinesis_test.go
Labels: area/aws, enhancement, ready to merge

#8976 Mac entry script: Add space before calling path so that zsh doesn't remove first character of path when prompting for update.
  scripts/telegraf_entry_mac
Labels: enhancement

#8975 Move golangci-lint from circle-ci to github actions
  .circleci/config.yml
  .github/workflows/golangci-lint.yml
Labels: enhancement

#8849 Filter data out from system databases for Azure SQL DB only
  plugins/inputs/sqlserver/azuresqlqueries.go
Labels: area/azure, area/sqlserver, enhancement, ready to merge

#8544 Add an optional health metric for the sqlserver input plugin
  etc/telegraf.conf
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/connectionstring.go
  plugins/inputs/sqlserver/sqlserver.go
  plugins/inputs/sqlserver/sqlserver_test.go
Labels: area/sqlserver, enhancement, ready to merge

#8977 Mute linting errors when running against master branch
  .github/workflows/golangci-lint.yml
Labels: bugfix

#8898 feat: Adding Plex Webhooks external plugin
  EXTERNAL_PLUGINS.md
Labels: enhancement, external plugin

#8979 Add value_field_name config option to customize field name when using Value parser.
  config/config.go
  plugins/inputs/exec/exec_test.go
  plugins/inputs/kafka_consumer/kafka_consumer_test.go
  plugins/parsers/registry.go
  plugins/parsers/value/parser.go
  plugins/parsers/value/parser_test.go
Labels: enhancement, new plugin, plugin/parser

#8634 Bigquery output Plugin
  README.md
  go.mod
  go.sum
  plugins/outputs/bigquery/README.md
  plugins/outputs/bigquery/bigquery.go
  plugins/outputs/bigquery/bigquery_test.go
Labels: area/gcp, plugin/output, ready to merge

#8951 Proposal of enabled linters and their settings.
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
Labels: enhancement

#8989 Update to Go 1.16.2
  .circleci/config.yml
  Makefile
  scripts/alpine.docker
  scripts/buster.docker
  scripts/ci-1.16.docker
  scripts/mac_installgo.sh
Labels: bugfix

#8769 Close running outputs when reloading
  agent/agent.go
Labels: enhancement, ready to merge

#8754 chore: remove references to outdated InfluxDB settings.
  docs/FAQ.md
  plugins/inputs/dcos/README.md
  plugins/inputs/kube_inventory/README.md
  plugins/inputs/kubernetes/README.md
  plugins/inputs/passenger/README.md
  plugins/inputs/sflow/README.md
Labels: documentation, ready to merge

#8971 Improve xml parser's handling of missing values
  plugins/parsers/xml/parser.go
  plugins/parsers/xml/parser_test.go
  plugins/parsers/xml/testcases/earthquakes.conf
  plugins/parsers/xml/testcases/earthquakes.quakeml
Labels: enhancement

#8950 Teamspeak input plugin query clients
  plugins/inputs/teamspeak/README.md
  plugins/inputs/teamspeak/teamspeak.go
  plugins/inputs/teamspeak/teamspeak_test.go
Labels: enhancement, ready to merge

#8861 Add top stat info to mongodb plugin
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb.go
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongodb_server.go
  plugins/inputs/mongodb/mongodb_server_test.go
  plugins/inputs/mongodb/mongostat.go
Labels: area/mongodb, enhancement, ready to merge

#8661 cisco_telemetry_mdt enhancement
  plugins/inputs/cisco_telemetry_mdt/README.md
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_util.go
Labels: area/cisco, enhancement, waiting for response

#8995 fix segfaults in sflow plugin by checking if protocol headers are set
  plugins/inputs/sflow/types.go
  plugins/inputs/sflow/types_test.go
Labels: bugfix

#7048 Input-plugin for KNX home-automation bus
  README.md
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/knx_listener/README.md
  plugins/inputs/knx_listener/knx_dummy_interface.go
  plugins/inputs/knx_listener/knx_listener.go
  plugins/inputs/knx_listener/knx_listener_test.go
Labels: new plugin, plugin/input, ready to merge

#8966 Adds snappy support for http_listener_v2
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
Labels: enhancement, ready to merge

#8967 New prometheus remote write parser
  docs/DATA_FORMATS_INPUT.md
  plugins/parsers/prometheusremotewrite/README.md
  plugins/parsers/prometheusremotewrite/parser.go
  plugins/parsers/prometheusremotewrite/parser_test.go
  plugins/parsers/registry.go
  plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
Labels: new plugin, plugin/parser

#8996 Add a starlark example showing how to obtain IOPS
  plugins/processors/starlark/README.md
  plugins/processors/starlark/testdata/iops.star
Labels: enhancement, ready to merge

#9017 update bigquery readme
  plugins/outputs/bigquery/README.md
Labels: documentation

#8891 Decompress option on kinesis-consumer
  plugins/inputs/kinesis_consumer/README.md
  plugins/inputs/kinesis_consumer/kinesis_consumer.go
  plugins/inputs/kinesis_consumer/kinesis_consumer_test.go
Labels: enhancement, ready to merge

#8333 add the ability to configure inputs.exec error truncation
  cmd/telegraf/telegraf.go
  plugin.go
  plugins/inputs/exec/exec.go
  plugins/inputs/exec/exec_test.go
  plugins/outputs/exec/README.md
  plugins/outputs/exec/exec.go
  plugins/outputs/exec/exec_test.go
Labels: area/exec, enhancement

#8991 update new plugins in changelog
  CHANGELOG.md
Labels: documentation, ready to merge

#9009 Check for length of perusage array and removed unused function from code
  plugins/inputs/docker/docker.go
Labels: bugfix

#9035 Fix ipmi panic
  plugins/inputs/ipmi_sensor/connection.go
  plugins/inputs/ipmi_sensor/connection_test.go
Labels: enhancement

#9004 Add support of the time module in Starlark Processor
  go.mod
  go.sum
  plugins/processors/starlark/README.md
  plugins/processors/starlark/starlark.go
  plugins/processors/starlark/testdata/time_date.star
  plugins/processors/starlark/testdata/time_duration.star
  plugins/processors/starlark/testdata/time_timestamp.star
Labels: enhancement

#6952 Wildcard support for x509_cert files
  plugins/inputs/x509_cert/README.md
  plugins/inputs/x509_cert/x509_cert.go
Labels: enhancement

#8549 SQLServer - Fixes sqlserver_process_cpu calculation
  plugins/inputs/sqlserver/sqlqueriesV2.go
  plugins/inputs/sqlserver/sqlserverqueries.go
Labels: area/sqlserver, bugfix

#9039 Replace github.com/kubernetes import with k8s.io and update protobuf to v1.5.1
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/kube_inventory/kube_state.go
  plugins/inputs/prometheus/kubernetes.go
  plugins/inputs/prometheus/kubernetes_test.go
  plugins/inputs/prometheus/prometheus.go
  plugins/inputs/prometheus/prometheus_test.go
Labels: bugfix

#8970 Simplifying the kinesis output tests
  plugins/outputs/kinesis/kinesis_test.go
Labels: area/aws, enhancement, ready to merge

#9042 Add the math module to the Starlark Processor
  plugins/processors/starlark/README.md
  plugins/processors/starlark/starlark.go
  plugins/processors/starlark/testdata/math.star
Labels: enhancement

#9049 add xpath testers to xml readme
  plugins/parsers/xml/README.md
Labels: documentation, enhancement

#9051 Moved samara config out of init into connect
  plugins/outputs/kafka/kafka.go
Labels: bugfix

#8639 AWS Cloudwatch log output
  plugins/outputs/all/all.go
  plugins/outputs/cloudwatch_logs/README.md
  plugins/outputs/cloudwatch_logs/cloudwatch_logs.go
  plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go
Labels: area/aws, plugin/output

#9056 use correct compute metadata url to get folder-id
  plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go
Labels: enhancement

#9064 readme fix
  plugins/processors/execd/README.md
Labels: bugfix

#8596 input/sqlserver: Add service and save connection pools
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/sqlserver/sqlserver.go
  plugins/inputs/sqlserver/sqlserver_test.go
Labels: area/sqlserver, feature request

#9043 Improve processor.ifname startup performance
  plugins/processors/ifname/ifname.go
Labels: area/snmp, enhancement, plugin/processor

#9032 Add ~200 more Couchbase metrics via Buckets endpoint
  plugins/inputs/couchbase/README.md
  plugins/inputs/couchbase/couchbase.go
  plugins/inputs/couchbase/couchbase_data.go
  plugins/inputs/couchbase/couchbase_test.go
Labels: enhancement

#9020 new linter commands
  .golangci.yml
  Makefile
Labels: enhancement

#9067 inputs.nfsclient: use uint64, also update error handling
  plugins/inputs/nfsclient/nfsclient.go
  plugins/inputs/nfsclient/nfsclient_test.go
Labels: enhancement

#9069 Add configurable option for the 'path' tag override in the Tail plugin.
  plugins/inputs/tail/README.md
  plugins/inputs/tail/tail.go
  plugins/inputs/tail/tail_test.go
Labels: enhancement

#9074 Starlark script for renaming prometheus remote write metrics
  plugins/parsers/prometheusremotewrite/README.md
  plugins/processors/starlark/README.md
  plugins/processors/starlark/testdata/rename_prometheus_remote_write.star
Labels: enhancement
