Repository influxdata/telegraf, pull requests merged in 2021-04, with the labels that each got.

#9090 feat: Add external Big blue button plugin
  EXTERNAL_PLUGINS.md
Labels: enhancement

#8994 Remove deprecated and unused SetAggregate() and IsAggregate() functions.
  metric.go
  metric/metric.go
  metric/metric_test.go
  models/running_aggregator.go
Labels: ready to merge

#9080 Add support for Logstash 7 'queue' stats from the Pipelines API
  plugins/inputs/logstash/logstash.go
  plugins/inputs/logstash/logstash_test.go
  plugins/inputs/logstash/samples_logstash7.go
Labels: enhancement

#9082 Add ability to handle 'binary logs' mySQL query with 3 columns, in case 3 columns are sent (MySQL 8 and greater)
  plugins/inputs/mysql/mysql.go
Labels: enhancement

#9026 Carbon2 serializer: sanitize metric name
  config/config.go
  plugins/outputs/sumologic/sumologic_test.go
  plugins/serializers/carbon2/README.md
  plugins/serializers/carbon2/carbon2.go
  plugins/serializers/carbon2/carbon2_test.go
  plugins/serializers/registry.go
Labels: bugfix

#9105 Allow to specify nanoseconds to timestamp in Starlark Processor
  go.mod
  go.sum
  plugins/processors/starlark/README.md
  plugins/processors/starlark/testdata/time_timestamp.star
  plugins/processors/starlark/testdata/time_timestamp_nanos.star
Labels: enhancement

#9107 Fix opcua integration test
  docker-compose.yml
  plugins/inputs/opcua/opcua_client_test.go
Labels: enhancement

#9045 Added MetricLookback setting
  plugins/inputs/vsphere/README.md
  plugins/inputs/vsphere/endpoint.go
  plugins/inputs/vsphere/vsphere.go
Labels: enhancement

#8892 change to NewStreamParser to accept larger inputs from scanner
  plugins/common/shim/processor.go
  plugins/common/shim/processor_test.go
Labels: enhancement

#8911 Support float64 in enum processor
  plugins/processors/enum/README.md
  plugins/processors/enum/enum.go
  plugins/processors/enum/enum_test.go
Labels: enhancement

#8917 Log snmpv3 auth failures
  go.mod
  go.sum
  plugins/inputs/snmp/snmp.go
Labels: area/snmp, bugfix, error handling, plugin/input, ready to merge

#9124 Add custom docker image info to nvidia plugin
  plugins/inputs/nvidia_smi/README.md
Labels: enhancement

#9128 Fix: sync nfsclient ops map in nfsclient struct
  plugins/inputs/nfsclient/nfsclient.go
Labels: bugfix

#5517 Gather all mysql channels
  plugins/inputs/mysql/README.md
  plugins/inputs/mysql/mysql.go
Labels: area/mysql, enhancement, ready to merge

#9140 Fix CI config to check if branch is master before skipping
  .circleci/config.yml
  scripts/check-file-changes.sh
Labels: bugfix

#9133 Add time.now() starlark processor example test
  plugins/processors/starlark/starlark.go
  plugins/processors/starlark/starlark_test.go
  plugins/processors/starlark/testdata/compare_metrics.star
  plugins/processors/starlark/testdata/iops.star
  plugins/processors/starlark/testdata/json_nested.star
  plugins/processors/starlark/testdata/multiple_metrics.star
  plugins/processors/starlark/testdata/multiple_metrics_with_json.star
  plugins/processors/starlark/testdata/pivot.star
  plugins/processors/starlark/testdata/rename_prometheus_remote_write.star
  plugins/processors/starlark/testdata/schema_sizing.star
  plugins/processors/starlark/testdata/time_set_timestamp.star
  plugins/processors/starlark/testdata/value_filter.star
Labels: enhancement

#9100 Add doc on supported platforms
  docs/SUPPORTED_PLATFORMS.md
Labels: documentation, enhancement

#9136 Add Glob / Wildcard support to Cloudwatch input for 'Dimensions' configuration
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
Labels: enhancement, ready to merge

#9110 Make JSON format compatible with nulls
  plugins/parsers/json/parser.go
  plugins/parsers/json/parser_test.go
Labels: enhancement

#8822 SQL Server input plugin - Enable Azure Active Directory (AAD) authentication support
  go.mod
  go.sum
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
  plugins/inputs/sqlserver/sqlserver_test.go
Labels: area/sqlserver, enhancement, ready to merge

#9096 Speed up package step by running in parallel.
  .circleci/config.yml
  Makefile
Labels: enhancement

#9167 Add time.star and math.star info to the Starlark readme lib section
  plugins/processors/starlark/README.md
Labels: documentation, enhancement

#9122 Linter fixes (unhandled errors) -- Part 2
  plugins/inputs/activemq/activemq_test.go
  plugins/inputs/apache/apache_test.go
  plugins/inputs/apcupsd/apcupsd_test.go
  plugins/inputs/aurora/aurora.go
  plugins/inputs/aurora/aurora_test.go
  plugins/inputs/bcache/bcache.go
  plugins/inputs/beanstalkd/beanstalkd.go
  plugins/inputs/beanstalkd/beanstalkd_test.go
  plugins/inputs/beat/beat_test.go
  plugins/inputs/bind/json_stats.go
  plugins/inputs/bind/xml_stats_v2.go
  plugins/inputs/bind/xml_stats_v3.go
  plugins/inputs/bond/bond_test.go
  plugins/inputs/ceph/ceph.go
  plugins/inputs/ceph/ceph_test.go
  plugins/inputs/chrony/chrony_test.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
  plugins/inputs/clickhouse/clickhouse_test.go
  plugins/inputs/cloud_pubsub_push/pubsub_push.go
  plugins/inputs/cloud_pubsub_push/pubsub_push_test.go
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
  plugins/inputs/conntrack/conntrack_test.go
  plugins/inputs/couchdb/couchdb.go
  plugins/inputs/dcos/client.go
  plugins/inputs/directory_monitor/directory_monitor.go
  plugins/inputs/directory_monitor/directory_monitor_test.go
  plugins/inputs/diskio/diskio_linux.go
  plugins/inputs/diskio/diskio_linux_test.go
  plugins/inputs/disque/disque.go
  plugins/inputs/disque/disque_test.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker_log/docker_log.go
  plugins/inputs/docker_log/docker_log_test.go
  plugins/inputs/dovecot/dovecot.go
  plugins/inputs/ecs/ecs_test.go
  plugins/inputs/elasticsearch/elasticsearch_test.go
  plugins/inputs/exec/exec.go
  plugins/inputs/exec/exec_test.go
  plugins/inputs/execd/execd_posix.go
  plugins/inputs/execd/execd_test.go
  plugins/inputs/execd/shim/goshim.go
  plugins/inputs/execd/shim/shim_posix_test.go
  plugins/inputs/execd/shim/shim_test.go
  plugins/inputs/fail2ban/fail2ban_test.go
  plugins/inputs/fibaro/fibaro_test.go
  plugins/inputs/file/file_test.go
  plugins/inputs/filecount/filecount_test.go
  plugins/inputs/filestat/filestat_test.go
  plugins/inputs/fireboard/fireboard_test.go
  plugins/inputs/fluentd/fluentd_test.go
  plugins/inputs/gnmi/gnmi.go
  plugins/inputs/gnmi/gnmi_test.go
  plugins/inputs/haproxy/haproxy_test.go
  plugins/inputs/internal/internal_test.go
Labels: bugfix, enhancement, ready to merge

#9126 Move wiki information to docs
  CONTRIBUTING.md
  docs/developers/CODE_STYLE.md
  docs/developers/DEPRECATION.md
  docs/developers/LOGGING.md
  docs/developers/METRIC_FORMAT_CHANGES.md
  docs/developers/PACKAGING.md
  docs/developers/PROFILING.md
  docs/developers/REVIEWS.md
  docs/developers/SAMPLE_CONFIG.md
  docs/maintainers/CHANGELOG.md
  docs/maintainers/LABELS.md
  docs/maintainers/PULL_REQUESTS.md
  docs/maintainers/RELEASES.md
Labels: documentation

#9138 Add OAuth2 to HTTP input
  plugins/common/http/config.go
  plugins/common/oauth/config.go
  plugins/inputs/http/README.md
  plugins/inputs/http/http.go
  plugins/inputs/http/http_test.go
  plugins/outputs/http/http.go
  plugins/outputs/http/http_test.go
Labels: enhancement, ready to merge

#9187 Add external dnsmasq input plugin
  EXTERNAL_PLUGINS.md
Labels: enhancement

#9191 Linter fixes for plugins/inputs/[ab]*
  plugins/inputs/aerospike/README.md
  plugins/inputs/aerospike/aerospike.go
  plugins/inputs/aerospike/aerospike_test.go
  plugins/inputs/aliyuncms/aliyuncms.go
  plugins/inputs/aliyuncms/aliyuncms_test.go
  plugins/inputs/aliyuncms/discovery.go
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
  plugins/inputs/apache/apache.go
  plugins/inputs/apcupsd/apcupsd.go
  plugins/inputs/apcupsd/apcupsd_test.go
  plugins/inputs/beat/README.md
  plugins/inputs/beat/beat.go
  plugins/inputs/bind/json_stats.go
  plugins/inputs/bind/xml_stats_v2.go
  plugins/inputs/bind/xml_stats_v3.go
  plugins/inputs/burrow/burrow_test.go
Labels: bugfix

#9168 Private linter for Telegraf
  .golangci.yml
  go.mod
  go.sum
  telegraflinter/README.md
  telegraflinter/telegraflinter.go
Labels: enhancement

#9196 Remote write compliance updates
  go.mod
  go.sum
  plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
  plugins/serializers/prometheusremotewrite/prometheusremotewrite_test.go
Labels: enhancement

#9194 Linter fixes for plugins/inputs/[c]*
  plugins/inputs/cassandra/README.md
  plugins/inputs/cassandra/cassandra.go
  plugins/inputs/ceph/README.md
  plugins/inputs/ceph/ceph.go
  plugins/inputs/ceph/ceph_test.go
  plugins/inputs/cgroup/README.md
  plugins/inputs/cgroup/cgroup_linux.go
  plugins/inputs/chrony/chrony_test.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt_test.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_util.go
  plugins/inputs/clickhouse/clickhouse.go
  plugins/inputs/clickhouse/clickhouse_test.go
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
  plugins/inputs/couchbase/couchbase.go
  plugins/inputs/couchbase/couchbase_test.go
  plugins/inputs/cpu/README.md
  plugins/inputs/cpu/cpu.go
  plugins/inputs/cpu/cpu_test.go
  plugins/inputs/csgo/README.md
  plugins/inputs/csgo/csgo.go
  plugins/inputs/csgo/csgo_test.go
Labels: bugfix

#9195 Fix apcupsd 'ALARMDEL' bug via forked repo
  go.mod
  go.sum
  plugins/inputs/apcupsd/apcupsd_test.go
Labels: bugfix

#8883 New DPDK input plugin
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/dpdk/README.md
  plugins/inputs/dpdk/dpdk.go
  plugins/inputs/dpdk/dpdk_connector.go
  plugins/inputs/dpdk/dpdk_connector_test.go
  plugins/inputs/dpdk/dpdk_notlinux.go
  plugins/inputs/dpdk/dpdk_test.go
  plugins/inputs/dpdk/dpdk_utils.go
  plugins/inputs/dpdk/dpdk_utils_test.go
  plugins/inputs/dpdk/mocks/conn.go
Labels: new plugin, plugin/input, ready to merge

#9213 Remove outdated milestones info from FAQ
  docs/FAQ.md
Labels: documentation

#9160 Converter processor: add support for large hexadecimal strings
  plugins/processors/converter/README.md
  plugins/processors/converter/converter.go
  plugins/processors/converter/converter_test.go
Labels: enhancement

#9156 Fix for #9135
  plugins/inputs/aliyuncms/README.md
  plugins/inputs/aliyuncms/aliyuncms.go
  plugins/inputs/aliyuncms/aliyuncms_test.go
  plugins/inputs/aliyuncms/discovery.go
Labels: area/aliyuncms, bugfix, ready to merge

#9118 Add UTF-8 sanitizer to Strings plugin
  plugins/processors/strings/README.md
  plugins/processors/strings/strings.go
  plugins/processors/strings/strings_test.go
Labels: enhancement

#9077 OpenTelemetry Input Plugin
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/all/all.go
  plugins/inputs/opentelemetry/README.md
  plugins/inputs/opentelemetry/grpc_services.go
  plugins/inputs/opentelemetry/logger.go
  plugins/inputs/opentelemetry/opentelemetry.go
  plugins/inputs/opentelemetry/writer.go
Labels: enhancement, new plugin, plugin/input
