Repository influxdata/telegraf, pull requests merged in 2021-06, with the labels that each got.

#9087 Addresses issues in PR 4928
  internal/internal.go
  internal/internal_test.go
Labels: enhancement, ready for final review

#9311 update github maintainer docs
  docs/maintainers/LABELS.md
  docs/maintainers/PULL_REQUESTS.md
Labels: documentation, enhancement

#9297 Add HTTP proxy to datadog output
  plugins/outputs/datadog/README.md
  plugins/outputs/datadog/datadog.go
Labels: enhancement, plugin/output, ready for final review

#9326 Parallel build fixes
  .circleci/config.yml
  Makefile
Labels: enhancement

#8987 Add telegraf url env var
  config/config.go
  config/config_test.go
Labels: area/configuration, enhancement, ready for final review

#9182 Fix #9134 - Update pgx to v4
  docker-compose.yml
  docs/LICENSE_OF_DEPENDENCIES.md
  etc/telegraf.conf
  go.mod
  go.sum
  plugins/inputs/pgbouncer/pgbouncer.go
  plugins/inputs/pgbouncer/pgbouncer_test.go
  plugins/inputs/postgresql/postgresql.go
  plugins/inputs/postgresql/service.go
  plugins/inputs/postgresql_extensible/postgresql_extensible.go
  plugins/outputs/cratedb/README.md
  plugins/outputs/cratedb/cratedb.go
Labels: enhancement

#9280 Add SQL output plugin
  README.md
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/outputs/all/all.go
  plugins/outputs/sql/README.md
  plugins/outputs/sql/sql.go
  plugins/outputs/sql/sql_test.go
  plugins/outputs/sql/sqlite.go
  plugins/outputs/sql/sqlite_test.go
  plugins/outputs/sql/testdata/mariadb/expected.sql
  plugins/outputs/sql/testdata/mariadb/initdb/script.sql
  plugins/outputs/sql/testdata/postgres/expected.sql
  plugins/outputs/sql/testdata/postgres/initdb/init.sql
Labels: enhancement, new plugin, plugin/output

#9188 Add WebSocket output plugin
  README.md
  go.mod
  plugins/outputs/all/all.go
  plugins/outputs/websocket/README.md
  plugins/outputs/websocket/websocket.go
  plugins/outputs/websocket/websocket_test.go
Labels: new plugin, plugin/output, ready for final review

#9331 Update Go to 1.16.5
  .circleci/config.yml
  Makefile
  scripts/alpine.docker
  scripts/buster.docker
  scripts/ci-1.16.docker
  scripts/mac_installgo.sh
Labels: ready for final review

#9335 fix: Verify checksum of Go download in mac script
  scripts/mac_installgo.sh
Labels: enhancement

#9295 Use dynatrace-metric-utils
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/outputs/dynatrace/README.md
  plugins/outputs/dynatrace/dynatrace.go
  plugins/outputs/dynatrace/dynatrace_test.go
Labels: enhancement

#9345 Fix Mac script to install go
  scripts/check-file-changes.sh
  scripts/mac_installgo.sh
Labels: bugfix

#9246 New JSON Parser
  .circleci/config.yml
  config/config.go
  go.mod
  go.sum
  plugins/parsers/json_v2/README.md
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/parser_test.go
  plugins/parsers/json_v2/testdata/fields_and_tags/expected.out
  plugins/parsers/json_v2/testdata/fields_and_tags/input.json
  plugins/parsers/json_v2/testdata/fields_and_tags/telegraf.conf
  plugins/parsers/json_v2/testdata/fields_and_tags_complex/expected.out
  plugins/parsers/json_v2/testdata/fields_and_tags_complex/input.json
  plugins/parsers/json_v2/testdata/fields_and_tags_complex/telegraf.conf
  plugins/parsers/json_v2/testdata/measurement_name_int/expected.out
  plugins/parsers/json_v2/testdata/measurement_name_int/input.json
  plugins/parsers/json_v2/testdata/measurement_name_int/telegraf.conf
  plugins/parsers/json_v2/testdata/multiple_arrays_in_object/expected.out
  plugins/parsers/json_v2/testdata/multiple_arrays_in_object/input.json
  plugins/parsers/json_v2/testdata/multiple_arrays_in_object/telegraf.conf
  plugins/parsers/json_v2/testdata/multiple_timestamps/expected.out
  plugins/parsers/json_v2/testdata/multiple_timestamps/input.json
  plugins/parsers/json_v2/testdata/multiple_timestamps/telegraf.conf
  plugins/parsers/json_v2/testdata/nested_and_nonnested_tags/expected.out
  plugins/parsers/json_v2/testdata/nested_and_nonnested_tags/input.json
  plugins/parsers/json_v2/testdata/nested_and_nonnested_tags/telegraf.conf
  plugins/parsers/json_v2/testdata/nested_array_of_objects/expected.out
  plugins/parsers/json_v2/testdata/nested_array_of_objects/input.json
  plugins/parsers/json_v2/testdata/nested_array_of_objects/telegraf.conf
  plugins/parsers/json_v2/testdata/nested_tags/expected.out
  plugins/parsers/json_v2/testdata/nested_tags/input.json
  plugins/parsers/json_v2/testdata/nested_tags/telegraf.conf
  plugins/parsers/json_v2/testdata/nested_tags_complex/expected.out
  plugins/parsers/json_v2/testdata/nested_tags_complex/input.json
  plugins/parsers/json_v2/testdata/nested_tags_complex/telegraf.conf
  plugins/parsers/json_v2/testdata/object/expected.out
  plugins/parsers/json_v2/testdata/object/input.json
  plugins/parsers/json_v2/testdata/object/telegraf.conf
  plugins/parsers/json_v2/testdata/timestamp/expected.out
  plugins/parsers/json_v2/testdata/timestamp/input.json
  plugins/parsers/json_v2/testdata/timestamp/telegraf.conf
  plugins/parsers/json_v2/testdata/types/expected.out
  plugins/parsers/json_v2/testdata/types/input.json
  plugins/parsers/json_v2/testdata/types/telegraf.conf
  plugins/parsers/registry.go
Labels: new plugin, plugin/parser

#9306 Feature powermode smartctl
  plugins/inputs/smart/smart.go
Labels: enhancement

#9296 Bugfix outputs influxdb endless retires
  plugins/outputs/influxdb/http.go
  plugins/outputs/influxdb/http_test.go
  plugins/outputs/influxdb/influxdb.go
  testutil/capturelog.go
Labels: bugfix

#9338 Support new Suricata JSON format which includes arrays and strings
  plugins/inputs/suricata/suricata.go
  plugins/inputs/suricata/suricata_test.go
  plugins/inputs/suricata/testdata/test2.json
Labels: bugfix, plugin/input, ready for final review

#9243 Closing all idle connections in docker input plugin
  plugins/inputs/docker/client.go
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
Labels: bugfix

#8735 Generic SQL input
  README.md
  docs/SQL_DRIVERS_INPUT.md
  filter/filter.go
  go.sum
  internal/internal.go
  internal/type_conversions.go
  plugins/inputs/all/all.go
  plugins/inputs/sql/README.md
  plugins/inputs/sql/drivers.go
  plugins/inputs/sql/drivers_sqlite.go
  plugins/inputs/sql/sql.go
  plugins/inputs/sql/sql_test.go
  plugins/inputs/sql/testdata/mariadb/expected.sql
  plugins/inputs/sql/testdata/postgres/expected.sql
Labels: enhancement, new plugin, plugin/input

#9283 Fix segfault in processors/parser
  plugins/processors/parser/parser.go
  plugins/processors/parser/parser_test.go
Labels: bugfix, enhancement, plugin/processor

#9358 upgrade denisenkom go-mssql to v0.10.0
  go.mod
  go.sum
Labels: bugfix, ready for final review

#9329 Fix kube_inventory not connecting to specified URL
  plugins/inputs/kube_inventory/client.go
Labels: area/k8s, bugfix, ready for final review

#9363 Update dynatrace output
  plugins/outputs/dynatrace/README.md
  plugins/outputs/dynatrace/dynatrace.go
  plugins/outputs/dynatrace/dynatrace_test.go
Labels: enhancement, plugin/output, ready for final review

#9342 Added support to override metric_url in newrelic output plugin
  plugins/outputs/newrelic/README.md
  plugins/outputs/newrelic/newrelic.go
  plugins/outputs/newrelic/newrelic_test.go
Labels: enhancement, plugin/output, ready for final review

#9360 Add s7comm external input plugin
  EXTERNAL_PLUGINS.md
Labels: enhancement, external plugin, ready for final review

#9359 Fix import of sqlite and ignore it on all platforms that require CGO.
  plugins/inputs/sql/drivers_sqlite.go
  plugins/outputs/sql/sqlite.go
  plugins/outputs/sql/sqlite_test.go
Labels: bugfix, plugin/output

#9368 Update json_v2 parser to handle null types
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/parser_test.go
  plugins/parsers/json_v2/testdata/null/expected.out
  plugins/parsers/json_v2/testdata/null/input.json
  plugins/parsers/json_v2/testdata/null/telegraf.conf
Labels: area/json_v2, bugfix

#9343 Use gosmi for SNMP traps
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/snmp_trap/README.md
  plugins/inputs/snmp_trap/snmp_trap.go
  plugins/inputs/snmp_trap/snmp_trap_test.go
  plugins/inputs/snmp_trap/testdata/test.mib
  plugins/inputs/snmp_trap/testdata/test2
Labels: area/snmp, enhancement, plugin/input

#9379 Linter fixes for plugins/inputs/[de]*
  .golangci.yml
  plugins/inputs/dcos/client.go
  plugins/inputs/dcos/dcos.go
  plugins/inputs/directory_monitor/directory_monitor.go
  plugins/inputs/directory_monitor/directory_monitor_test.go
  plugins/inputs/disk/disk.go
  plugins/inputs/disk/disk_test.go
  plugins/inputs/diskio/diskio.go
  plugins/inputs/diskio/diskio_linux_test.go
  plugins/inputs/disque/disque.go
  plugins/inputs/dns_query/dns_query.go
  plugins/inputs/docker/client.go
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker_log/docker_log.go
  plugins/inputs/ecs/ecs.go
  plugins/inputs/elasticsearch/elasticsearch.go
  plugins/inputs/elasticsearch/elasticsearch_test.go
  plugins/inputs/ethtool/ethtool_linux.go
  plugins/inputs/ethtool/ethtool_test.go
  plugins/inputs/eventhub_consumer/eventhub_consumer.go
  plugins/inputs/exec/exec.go
  plugins/inputs/execd/execd_test.go
Labels: enhancement, ready for final review

#9357 kube_inventory: expand tls key/tls certificate documentation
  plugins/inputs/kube_inventory/README.md
Labels: documentation

#9372 gjson dependancy updated to v1.8.0
  go.mod
  go.sum
Labels: dependencies

#3536 Add Elasticsearch query input plugin
  .gitignore
  plugins/inputs/all/all.go
  plugins/inputs/elasticsearch_query/README.md
  plugins/inputs/elasticsearch_query/aggregation_parser.go
  plugins/inputs/elasticsearch_query/aggregation_query.go
  plugins/inputs/elasticsearch_query/elasticsearch_query.go
  plugins/inputs/elasticsearch_query/elasticsearch_query_test.go
  plugins/inputs/elasticsearch_query/testdata/nginx_logs
Labels: area/elasticsearch, new plugin, ready for final review

#9289 Issue 8914 x509sni
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: bugfix

#9406 tags no longer required in included_keys
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/testdata/nested_and_nonnested_tags/telegraf.conf
  plugins/parsers/json_v2/testdata/object/telegraf.conf
Labels: enhancement

#9375 updated signalfx
  go.mod
  go.sum
Labels: dependencies, ready for final review

#9400 Fix schema mess-up for x509 with https
  plugins/inputs/x509_cert/x509_cert.go
Labels: bugfix

#9413 fixing insecure_skip_verify
  plugins/outputs/http/http.go
Labels: enhancement

#9366 added a check for oid and name to prevent empty metrics
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
Labels: enhancement

#9412 Update couchbase dependencies
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
Labels: dependencies, ready for final review

#9373 updated jwt to v1.2.2 and updated jwt-go to v3.2.3
  go.mod
  go.sum
Labels: enhancement

#9367 chore: readme updates
  plugins/inputs/aliyuncms/README.md
  plugins/inputs/cisco_telemetry_mdt/README.md
  plugins/inputs/dpdk/README.md
  plugins/inputs/knx_listener/README.md
Labels: documentation, enhancement, ready for final review

#9370 apimachinary updated to v0.21.1
  go.mod
  go.sum
Labels: enhancement

#9423 Don't stop parsing after statsd parsing error
  plugins/inputs/statsd/statsd.go
Labels: bugfix, ready for final review

#9429 Fix dovecot regression in #9415
  plugins/inputs/dovecot/dovecot.go
Labels: bugfix, plugin/input

#9369 nat-server now using v2.2.6
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
Labels: dependencies

#9443 Fix RabbitMQ regression in #9383
  plugins/inputs/rabbitmq/README.md
  plugins/inputs/rabbitmq/rabbitmq.go
  plugins/inputs/rabbitmq/rabbitmq_test.go
  plugins/inputs/rabbitmq/testdata/set1/exchanges.json
  plugins/inputs/rabbitmq/testdata/set1/federation-links.json
  plugins/inputs/rabbitmq/testdata/set1/memory.json
  plugins/inputs/rabbitmq/testdata/set1/nodes.json
  plugins/inputs/rabbitmq/testdata/set1/overview.json
  plugins/inputs/rabbitmq/testdata/set1/queues.json
  plugins/inputs/rabbitmq/testdata/set2/exchanges.json
  plugins/inputs/rabbitmq/testdata/set2/federation-links.json
  plugins/inputs/rabbitmq/testdata/set2/memory.json
  plugins/inputs/rabbitmq/testdata/set2/nodes.json
  plugins/inputs/rabbitmq/testdata/set2/overview.json
  plugins/inputs/rabbitmq/testdata/set2/queues.json
Labels: area/rabbitmq, bugfix, regression

#9446 updated gopsutil to use a specific commit
  go.mod
  go.sum
Labels: enhancement
