Repository influxdata/telegraf, pull requests merged in 2021-08, with the labels that each got.

#9569 docs: Adding links to net_irtt and dht_sensor external plugins
  EXTERNAL_PLUGINS.md
Labels: documentation, ready for final review

#9574 docs: Add logo
  README.md
  TelegrafTiger.png
Labels: documentation, ready for final review

#9570 feat: Modbus Rtu over tcp enhancement
  plugins/inputs/modbus/README.md
  plugins/inputs/modbus/modbus.go
Labels: area/modbus, enhancement, ready for final review

#9567 docs: Update Processors/awsec2 readme
  plugins/processors/aws/ec2/README.md
Labels: bugfix, ready for final review

#9554 fix: Normalize PostgreSQL unix socket path
  plugins/inputs/postgresql/service.go
Labels: bugfix, ready for final review

#9577 fix: upgraded sensu/go to v2.9.0
  go.mod
  go.sum
Labels: bugfix

#9411 feat: Support AWS Web Identity Provider
  config/aws/credentials.go
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
  plugins/inputs/kinesis_consumer/README.md
  plugins/inputs/kinesis_consumer/kinesis_consumer.go
  plugins/outputs/cloudwatch/README.md
  plugins/outputs/cloudwatch/cloudwatch.go
  plugins/outputs/cloudwatch_logs/README.md
  plugins/outputs/cloudwatch_logs/cloudwatch_logs.go
  plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go
  plugins/outputs/kinesis/README.md
  plugins/outputs/kinesis/kinesis.go
  plugins/outputs/timestream/README.md
  plugins/outputs/timestream/timestream.go
Labels: area/aws, enhancement, ready for final review

#9228 OpenTelemetry output plugin
  README.md
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/opentelemetry/README.md
  plugins/inputs/opentelemetry/grpc_services.go
  plugins/inputs/opentelemetry/opentelemetry.go
  plugins/inputs/opentelemetry/writer.go
  plugins/outputs/all/all.go
  plugins/outputs/opentelemetry/README.md
  plugins/outputs/opentelemetry/logger.go
  plugins/outputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry_test.go
Labels: enhancement, new plugin, plugin/output

#9581 fix: Fixing k8s nodes and pods parsing error
  plugins/inputs/kube_inventory/node.go
  plugins/inputs/kube_inventory/node_test.go
  plugins/inputs/kube_inventory/pod.go
  plugins/inputs/kube_inventory/pod_test.go
Labels: bugfix

#9524 fix: Do not return on disconnect to avoid breaking reconnect
  plugins/inputs/opcua/opcua_client.go
  plugins/inputs/opcua/opcua_client_test.go
Labels: regression, bugfix, ready for final review

#9578 fix: muting tests for udp_listener
  plugins/inputs/udp_listener/udp_listener_test.go
Labels: bugfix

#9571 fix: sort logs by timestamp before writing to Loki
  plugins/outputs/loki/README.md
  plugins/outputs/loki/loki.go
  plugins/outputs/loki/loki_test.go
Labels: enhancement

#9576 fix: Refactor ec2 init for config-api
  plugins/processors/aws/ec2/ec2.go
  plugins/processors/aws/ec2/ec2_test.go
Labels: bugfix, ready for final review

#9583 fix(opcua): clean client on disconnect so that connect works cleanly
  plugins/inputs/opcua/opcua_client.go
Labels: bugfix, area/opcua, ready for final review

#9401 fix #9398, improve corner cases when aggregation functions return empty result set
  plugins/inputs/clickhouse/clickhouse.go
  plugins/inputs/clickhouse/clickhouse_test.go
  plugins/inputs/clickhouse/dev/docker-compose.yml
  plugins/inputs/clickhouse/dev/init_schema.sql
  plugins/inputs/clickhouse/dev/mysql_port.xml
  plugins/inputs/clickhouse/dev/test_dictionary.xml
Labels: bugfix

#9386 feat: Pull metrics from multiple AWS CloudWatch namespaces
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
Labels: enhancement, area/aws, ready for final review

#9566 fix: CrateDB replace dots in tag keys with underscores
  plugins/outputs/cratedb/README.md
  plugins/outputs/cratedb/cratedb.go
  plugins/outputs/cratedb/cratedb_test.go
Labels: bugfix, area/cratedb

#9606 docs: improve redis commands documentation
  plugins/inputs/redis/README.md
  plugins/inputs/redis/redis.go
Labels: documentation, ready for final review

#9620 fix: wireguard unknown revision when using GOPROXY=direct
  go.mod
  go.sum
Labels: bugfix, ready for final review

#9598 feat: add bool datatype for sql output plugin
  plugins/outputs/sql/README.md
  plugins/outputs/sql/sql.go
  plugins/outputs/sql/sql_test.go
  plugins/outputs/sql/testdata/mariadb/expected.sql
  plugins/outputs/sql/testdata/postgres/expected.sql
Labels: enhancement, ready for final review, area/sql

#9608 fix: flaky cookie test and failing to close fake server between tests
  plugins/common/cookie/cookie.go
  plugins/common/cookie/cookie_test.go
  plugins/common/http/config.go
Labels: bugfix, ready for final review

#9605 fix: issues with prometheus kubernetes pod discovery
  plugins/inputs/prometheus/kubernetes.go
Labels: bugfix, ready for final review

#9641 fix: prefix dependabot commits with "fix:"
  .github/dependabot.yml
Labels: bugfix, ready for final review

#9632 docs: update links
  README.md
  docs/DATA_FORMATS_INPUT.md
Labels: documentation, bugfix, ready for final review

#9625 fix: Output timestamp with fractional seconds
  plugins/outputs/graylog/graylog.go
Labels: enhancement

#9101 feat: /proc/mdstat collection
  README.md
  plugins/inputs/all/all.go
  plugins/inputs/mdstat/README.md
  plugins/inputs/mdstat/mdstat.go
  plugins/inputs/mdstat/mdstat_notlinux.go
  plugins/inputs/mdstat/mdstat_test.go
Labels: enhancement, new plugin, plugin/input
