Repository influxdata/telegraf, pull requests merged in 2021-10, with the labels that each got.

#9803 fix: add keep alive config option for identifier rejected error
  plugins/outputs/mqtt/README.md
  plugins/outputs/mqtt/mqtt.go
  plugins/outputs/mqtt/mqtt_test.go
Labels: bugfix

#9818 fix: gitignore should ignore .toml & .conf files
  .gitignore
Labels: enhancement, ready for final review

#9808 fix: procstat missing tags in procstat_lookup metric
  plugins/inputs/procstat/procstat.go
Labels: bugfix, ready for final review

#9848 fix: update toml tag to match sample config / readme
  plugins/outputs/loki/loki.go
Labels: bugfix, ready for final review

#9850 fix: logging in intel_rdt.go caused service stop timeout even as root (#9844)
  plugins/inputs/intel_rdt/intel_rdt.go
Labels: bugfix, ready for final review

#9846 fix: mongodb input plugin issue #9845
  plugins/inputs/mongodb/mongostat.go
Labels: enhancement, ready for final review

#9449 feat (parser.json_v2): Support defining field/tag tables within an object table
  config/config.go
  go.mod
  go.sum
  plugins/parsers/json_v2/README.md
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/parser_test.go
  plugins/parsers/json_v2/testdata/multiple_arrays_in_object/expected.out
  plugins/parsers/json_v2/testdata/multiple_json_input/expected.out
  plugins/parsers/json_v2/testdata/multiple_json_input/input_1.json
  plugins/parsers/json_v2/testdata/multiple_json_input/input_2.json
  plugins/parsers/json_v2/testdata/multiple_json_input/telegraf.conf
  plugins/parsers/json_v2/testdata/subfieldtag_in_object/expected.out
  plugins/parsers/json_v2/testdata/subfieldtag_in_object/input.json
  plugins/parsers/json_v2/testdata/subfieldtag_in_object/telegraf.conf
  plugins/parsers/json_v2/testdata/subfieldtag_in_object_2/expected.out
  plugins/parsers/json_v2/testdata/subfieldtag_in_object_2/input.json
  plugins/parsers/json_v2/testdata/subfieldtag_in_object_2/telegraf.conf
Labels: ready for final review

#9859 fix: remove line which breaks label bot functionality
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bugfix

#9513 feat: Starlark processor example for processing sparkplug_b messages
  plugins/processors/starlark/testdata/sparkplug.star
Labels: enhancement, ready for final review

#9740 feat(prometheus): add ignore_timestamp option
  config/config.go
  etc/telegraf.conf
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/parser.go
  plugins/inputs/prometheus/parser_test.go
  plugins/inputs/prometheus/prometheus.go
  plugins/inputs/prometheus/prometheus_test.go
  plugins/parsers/prometheus/parser.go
  plugins/parsers/prometheus/parser_test.go
  plugins/parsers/registry.go
Labels: enhancement, new plugin, plugin/parser

#9816 docs: updated azure data explorer plugin documentation
  plugins/outputs/azure_data_explorer/README.md
Labels: documentation, area/azure, ready for final review

#9863 chore: update consul to v1.11.0
  go.mod
  go.sum
Labels: bugfix
