Repository influxdata/telegraf, pull requests merged in 2022-10, with the labels that each got.

#11866 fix(inputs.influxdb_listener): error on invalid precision
  plugins/inputs/influxdb_listener/influxdb_listener.go
  plugins/parsers/influx/influx_upstream/parser.go
Labels: fix, plugin/input

#11923 chore: update github.com/shirou/gopsutil from v3.22.8 to v3.22.9
  go.mod
  go.sum
Labels: chore

#11875 fix(parser.xpath): Handle floating-point times correctly
  internal/internal.go
  internal/internal_test.go
  plugins/parsers/xpath/parser.go
  plugins/parsers/xpath/testcases/time_float_exponential/expected.out
  plugins/parsers/xpath/testcases/time_float_exponential/telegraf.conf
  plugins/parsers/xpath/testcases/time_float_exponential/test.json
Labels: fix, ready for final review, plugin/parser

#11904 build(rpm): Allow building RPMs cross-OS
  Makefile
Labels: ready for final review

#11828 Add libvirt plugin to external input plugins list
  EXTERNAL_PLUGINS.md
Labels: docs, external plugin

#11929 chore: Resolve linter issues in config.go and config_test.go
  config/config.go
  config/config_test.go
Labels: ready for final review, chore

#11912 fix(inputs.modbus): Improve duplicate field checks
  plugins/inputs/modbus/configuration_request.go
  plugins/inputs/modbus/modbus_test.go
  plugins/inputs/modbus/testcases/duplicate_fields_different_slave/expected.out
  plugins/inputs/modbus/testcases/duplicate_fields_different_slave/telegraf.conf
  plugins/inputs/modbus/testcases/duplicate_fields_different_tags/expected.out
  plugins/inputs/modbus/testcases/duplicate_fields_different_tags/telegraf.conf
  plugins/inputs/modbus/testcases/duplicate_fields_same_slave_and_request/init.err
  plugins/inputs/modbus/testcases/duplicate_fields_same_slave_and_request/telegraf.conf
  plugins/inputs/modbus/testcases/duplicate_fields_same_tags/init.err
  plugins/inputs/modbus/testcases/duplicate_fields_same_tags/telegraf.conf
Labels: fix, area/modbus, ready for final review, plugin/input

#11940 chore: update to go1.19.2
  .circleci/config.yml
  Makefile
  scripts/ci.docker
  scripts/installgo_linux.sh
  scripts/installgo_mac.sh
  scripts/installgo_windows.sh
Labels: chore

#11941 fix: enable_tls has incorrect default value (true) in sample.conf and README.md
  plugins/inputs/gnmi/README.md
  plugins/inputs/gnmi/sample.conf
  plugins/inputs/jti_openconfig_telemetry/README.md
  plugins/inputs/jti_openconfig_telemetry/sample.conf
  plugins/inputs/kafka_consumer/README.md
  plugins/inputs/kafka_consumer/sample.conf
  plugins/inputs/memcached/README.md
  plugins/inputs/memcached/sample.conf
  plugins/inputs/zookeeper/README.md
  plugins/inputs/zookeeper/sample.conf
  plugins/outputs/kafka/README.md
  plugins/outputs/kafka/sample.conf
Labels: fix, ready for final review

#11943 chore: update OpenTelemetry plugins to latest release
  go.mod
  go.sum
  plugins/inputs/opentelemetry/grpc_services.go
  plugins/inputs/opentelemetry/opentelemetry_test.go
  plugins/inputs/opentelemetry/writer.go
  plugins/outputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry_test.go
Labels: area/telemetry, ready for final review, dependencies, chore

#11957 chore: Bump golangci-lint to 1.50.0
  .github/workflows/golangci-lint.yml
  Makefile
Labels: chore

#11970 chore(inputs.socket_listener): Reorganize test to be table-based.
  plugins/inputs/socket_listener/socket_listener_test.go
Labels: ready for final review, plugin/input, chore

#11964 chore: Resolve linter issues for plugins/common package
  .golangci.yml
  cmd/telegraf/telegraf.go
  plugins/aggregators/starlark/starlark.go
  plugins/aggregators/starlark/starlark_test.go
  plugins/common/shim/example/cmd/main.go
  plugins/common/shim/output.go
  plugins/common/starlark/builtins.go
  plugins/common/starlark/field_dict.go
  plugins/common/starlark/starlark.go
  plugins/inputs/chrony/chrony_test.go
  plugins/inputs/execd/execd_test.go
  plugins/inputs/execd/shim/goshim.go
  plugins/inputs/fail2ban/fail2ban_test.go
  plugins/inputs/http_response/http_response_test.go
  plugins/inputs/ipmi_sensor/ipmi_sensor_test.go
  plugins/inputs/jolokia2_agent/jolokia2_agent_test.go
  plugins/inputs/jolokia2_proxy/jolokia2_proxy_test.go
  plugins/inputs/lvm/lvm_test.go
  plugins/inputs/phpfpm/child.go
  plugins/inputs/phpfpm/phpfpm_test.go
  plugins/inputs/sensors/sensors_test.go
  plugins/inputs/snmp/snmp_mocks_test.go
  plugins/inputs/solr/solr_test.go
  plugins/inputs/statsd/statsd_test.go
  plugins/inputs/system/system.go
  plugins/inputs/tcp_listener/tcp_listener.go
  plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go
  plugins/outputs/execd/execd_test.go
  plugins/outputs/groundwork/groundwork.go
  plugins/outputs/opentsdb/opentsdb_test.go
  plugins/processors/execd/execd_test.go
  plugins/processors/starlark/starlark.go
  plugins/processors/starlark/starlark_test.go
  tools/custom_builder/main.go
  tools/license_checker/main.go
Labels: ready for final review, chore

#11981 chore(ci): Migrate to scheduled pipeline
  .circleci/config.yml
Labels: chore

#11984 chore(inputs.cloud_pubsub_push): Don't run flaky test on Windows
  plugins/inputs/cloud_pubsub_push/cloud_pubsub_push_test.go
Labels: plugin/input, chore

#11982 chore(inputs.powerdns): Don't run flaky test on Windows
  plugins/inputs/powerdns/powerdns_linux_test.go
  plugins/inputs/powerdns/powerdns_test.go
Labels: plugin/input, chore

#11991 feat(outputs.event_hubs): Expose max message size batch option
  plugins/outputs/event_hubs/README.md
  plugins/outputs/event_hubs/event_hubs.go
  plugins/outputs/event_hubs/event_hubs_test.go
  plugins/outputs/event_hubs/sample.conf
Labels: feat, ready for final review, plugin/output

#11993 fix(inputs.opcua): Add metric tags to node
  plugins/inputs/opcua/opcua.go
  plugins/inputs/opcua/opcua_test.go
Labels: fix, area/opcua, ready for final review, plugin/input

#8958 feat(inputs.conntrack): Parse conntrack stats
  plugins/inputs/conntrack/README.md
  plugins/inputs/conntrack/conntrack.go
  plugins/inputs/conntrack/conntrack_test.go
  plugins/inputs/conntrack/sample.conf
  plugins/inputs/system/mock_PS.go
  plugins/inputs/system/ps.go
Labels: feat, ready for final review

#11997 fix(inputs.syslog): print error when no error or message given
  plugins/inputs/syslog/syslog.go
Labels: fix, area/syslog, ready for final review, plugin/input

#11994 test: add integration test for recovering after invalid data
  plugins/inputs/statsd/statsd_test.go
Labels: ready for final review, test

#11969 chore: Resolve linter issues for unhandled-error
  cmd/telegraf/main.go
  cmd/telegraf/main_test.go
  cmd/telegraf/telegraf.go
  cmd/telegraf/telegraf_windows.go
  internal/process/process.go
  internal/process/process_posix.go
  internal/process/process_windows.go
  internal/syslog/framing_test.go
  logger/event_logger_test.go
  logger/logger.go
  logger/logger_test.go
  metric/metric.go
  metric/series_grouper.go
  models/running_output_test.go
  plugins/outputs/postgresql/sqltemplate/template.go
  plugins/outputs/postgresql/table_source.go
  plugins/outputs/postgresql/utils/utils.go
  selfstat/selfstat.go
  testutil/testutil_test.go
Labels: ready for final review, chore

#12002 chore: Fix installgo_mac.sh using correct hash
  scripts/installgo_mac.sh
Labels: chore

#11996 test: add dovecot integration test
  plugins/inputs/dovecot/dovecot_test.go
  plugins/inputs/dovecot/testdata/dovecot.conf
Labels: ready for final review, test

#11814 feat: New input plugin for libvirt
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/all/libvirt.go
  plugins/inputs/libvirt/README.md
  plugins/inputs/libvirt/libvirt.go
  plugins/inputs/libvirt/libvirt_metric_format.go
  plugins/inputs/libvirt/libvirt_test.go
  plugins/inputs/libvirt/libvirt_utils.go
  plugins/inputs/libvirt/libvirt_utils_mock.go
  plugins/inputs/libvirt/sample.conf
Labels: feat, new plugin, ready for final review, plugin/input

#12004 refactor: Prevent import from going the wrong way
  plugins/outputs/wavefront/wavefront.go
  plugins/outputs/wavefront/wavefront_test.go
  plugins/serializers/wavefront/wavefront.go
  plugins/serializers/wavefront/wavefront_test.go
Labels: ready for final review, refactor

#12016 fix(regression): Fixes problem with metrics not exposed by plugins.
  agent/agent.go
Labels: fix, ready for final review

#11824 feat: New Intel DLB input plugin
  plugins/inputs/all/intel_dlb.go
  plugins/inputs/intel_dlb/README.md
  plugins/inputs/intel_dlb/intel_dlb.go
  plugins/inputs/intel_dlb/intel_dlb_notlinux.go
  plugins/inputs/intel_dlb/intel_dlb_test.go
  plugins/inputs/intel_dlb/mock_ras_reader.go
  plugins/inputs/intel_dlb/ras_reader.go
  plugins/inputs/intel_dlb/sample.conf
Labels: feat, new plugin, ready for final review, plugin/input

#11977 feat: run govulncheck nightly on master branch
  .circleci/config.yml
Labels: feat, ready for final review

#12039 chore(deps): bump testcontainers-go from 0.13.0 to 0.14.0 and address breaking change
  go.mod
  go.sum
  plugins/outputs/sql/sql_test.go
  testutil/container.go
Labels: chore

#11983 feat(inputs.modbus): add pause after connect config parameter
  etc/telegraf.conf
  etc/telegraf_windows.conf
  plugins/inputs/modbus/README.md
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/sample.conf
  plugins/inputs/modbus/sample_general_end.conf
Labels: feat, ready for final review

#12049 fix: mongodb input incorrect type int64 for ServerStatus
  plugins/inputs/mongodb/mongostat.go
Labels: fix, ready for final review

#12048 docs(inputs.mongodb): update supported versions
  plugins/inputs/mongodb/README.md
Labels: docs, area/mongodb, plugin/input

#12055 chore: Update golangci-lint Go version
  .github/workflows/golangci-lint.yml
Labels: chore

#12056 test: add additional checks, waits in integration tests
  plugins/inputs/mysql/mysql_test.go
  plugins/outputs/sql/sql_test.go
Labels: test

#12023 fix(inputs.zookeeper): add the ability to parse floats as floats
  plugins/inputs/zookeeper/README.md
  plugins/inputs/zookeeper/sample.conf
  plugins/inputs/zookeeper/zookeeper.go
  plugins/inputs/zookeeper/zookeeper_test.go
Labels: fix, plugin/input

#12051 chore: Resolve deprecated linter issues
  plugins/common/tls/config.go
  plugins/inputs/gnmi/gnmi.go
  plugins/inputs/gnmi/gnmi_test.go
  plugins/outputs/amqp/client.go
  plugins/outputs/socket_writer/socket_writer.go
  plugins/outputs/syslog/syslog.go
  plugins/processors/strings/strings.go
Labels: chore

#12062 fix(inputs.conntrack): Skip gather tests if conntrack module not loaded
  plugins/inputs/conntrack/conntrack_test.go
Labels: fix, plugin/input

#12066 docs: corrected typo mentioning wrong func name
  plugins/aggregators/starlark/README.md
Labels: docs

#12038 fix(inputs.modbus): add slave id to failing connection
  plugins/inputs/modbus/modbus.go
Labels: fix, area/modbus, ready for final review, plugin/input

#12069 docs(inputs.http): add use system proxy config option
  plugins/inputs/http/README.md
  plugins/inputs/http/sample.conf
Labels: docs, plugin/input

#12064 fix: switch to sarama's new consumer group rebalance strategy setting
  plugins/inputs/kafka_consumer/kafka_consumer.go
Labels: fix, ready for final review

#12063 fix: Restore warning on unused config option(s)
  config/config.go
  config/config_test.go
  config/testdata/invalid_field_in_parser_table.toml
  config/testdata/invalid_field_in_parserfunc_table.toml
  config/testdata/invalid_field_processor.toml
  config/testdata/invalid_field_processor_in_parser.toml
  config/testdata/invalid_field_processor_in_parser_table.toml
  config/testdata/invalid_field_processor_in_parserfunc.toml
  config/testdata/invalid_field_processor_in_parserfunc_table.toml
  config/testdata/invalid_field_processor_with_parser.toml
  config/testdata/invalid_field_processor_with_parserfunc.toml
  config/testdata/invalid_field_with_parser.toml
  config/testdata/invalid_field_with_parserfunc.toml
Labels: fix, ready for final review

#12074 test(inputs.mcrouter): add eventually to pause for metrics
  plugins/inputs/mcrouter/mcrouter_test.go
Labels: ready for final review, plugin/input, test

#12077 fix(agent): panic as tickers slice was off-by-one in size
  agent/agent.go
Labels: fix, ready for final review

#12085 test: update integration test occurrences
  plugins/inputs/pgbouncer/pgbouncer_test.go
  plugins/inputs/sql/sql_test.go
  plugins/inputs/supervisor/supervisor_test.go
  plugins/outputs/mongodb/mongodb_test.go
Labels: test

#12086 test(outputs.sql): further wait for clickhouse writes
  plugins/outputs/sql/sql_test.go
Labels: ready for final review, plugin/output, area/sql, test

#12081 fix(processors): Correctly setup processors
  config/config.go
Labels: regression, fix, plugin/processor

#12076 fix(config): set default parser
  config/config.go
  config/config_test.go
  config/testdata/default_parser.toml
  config/testdata/default_parser_exec.toml
Labels: fix, ready for final review

#12075 feat(tools): Allow to markdown includes for sections
  .markdownlintignore
  docs/includes/plugin_config.md
  plugins/inputs/activemq/README.md
  tools/readme_config_includer/generator.go
Labels: feat, ready for final review

#12087 feat(ethtool): Possibility to skip gathering metrics for downed interfaces
  plugins/inputs/ethtool/README.md
  plugins/inputs/ethtool/ethtool.go
  plugins/inputs/ethtool/ethtool_linux.go
  plugins/inputs/ethtool/ethtool_test.go
  plugins/inputs/ethtool/sample.conf
Labels: feat

#12100 chore: skip integration test with race
  plugins/inputs/kafka_consumer/kafka_consumer_test.go
Labels: chore

#12088 chore: Review of //nolint comments
  .github/workflows/golangci-lint.yml
  .golangci.yml
  agent/agent.go
  cmd/telegraf/main.go
  cmd/telegraf/pprof.go
  cmd/telegraf/telegraf.go
  config/config_test.go
  config/deprecation.go
  internal/process/process_test.go
  internal/snmp/translate.go
  metric/series_grouper.go
  models/running_output_test.go
  models/running_processor_test.go
  plugins/common/shim/processor.go
  plugins/common/starlark/field_dict.go
  plugins/inputs/dovecot/dovecot_test.go
  plugins/inputs/fail2ban/fail2ban_test.go
  plugins/inputs/gnmi/gnmi.go
  plugins/inputs/jolokia2_proxy/jolokia2_proxy_test.go
  plugins/inputs/phpfpm/phpfpm_test.go
  plugins/inputs/procstat/procstat_test.go
  plugins/inputs/snmp/gosmi.go
  plugins/inputs/solr/solr_test.go
  plugins/inputs/sql/sql.go
  plugins/inputs/system/system.go
  plugins/outputs/amqp/amqp.go
  plugins/outputs/influxdb/http_test.go
  plugins/outputs/influxdb/influxdb.go
  plugins/outputs/postgresql/datatype_uint8.go
  plugins/outputs/postgresql/postgresql.go
  plugins/outputs/sql/sqlite_test.go
  plugins/outputs/syslog/syslog_mapper.go
  plugins/processors/aws/ec2/ec2.go
  plugins/processors/execd/execd.go
  plugins/processors/execd/execd_test.go
  plugins/processors/ifname/ifname.go
  plugins/processors/reverse_dns/reverse_dns.go
  plugins/processors/reverse_dns/reverse_dns_test.go
  plugins/processors/starlark/starlark.go
  plugins/processors/starlark/starlark_test.go
  plugins/processors/streamingprocessor.go
  processor.go
  scripts/generate_versioninfo/main.go
  testutil/capturelog.go
  tools/license_checker/main.go
  tools/license_checker/whitelist.go
  tools/readme_config_includer/generator.go
  tools/update_goversion/main.go
Labels: ready for final review, chore

#12102 chore: shut down plugins gracefully to prevent race
  plugins/inputs/kafka_consumer/kafka_consumer_test.go
Labels: chore

#12106 chore: Increase golangci-lint timeout
  .github/workflows/golangci-lint.yml
Labels: ready for final review, chore

#12103 chore(common.shim): check err of s.writeProcessedMetrics for the linter
  plugins/common/shim/input.go
  plugins/common/shim/processor.go
Labels: ready for final review, chore

#12110 test(outputs.graylog): skip tcp/udp tests on windows & darwin
  plugins/outputs/graylog/graylog_test.go
  plugins/outputs/graylog/graylog_test_linux.go
Labels: plugin/output, test

#12109 fix(inputs.modbus): Handle field-measurement definitions correctly on duplicate field check
  plugins/inputs/modbus/configuration_request.go
  plugins/inputs/modbus/modbus_test.go
  plugins/inputs/modbus/testcases/duplicate_fields_issue_12091/expected.out
  plugins/inputs/modbus/testcases/duplicate_fields_issue_12091/telegraf.conf
Labels: fix, area/modbus, plugin/input

#12116 fix(processors.parser): Keep name of original metric if parser doesn't return one
  plugins/processors/parser/parser.go
  plugins/processors/parser/parser_test.go
Labels: fix, plugin/processor

#12117 docs(serializers.json): specify version of jsonata used
  plugins/serializers/json/README.md
Labels: docs, area/json, plugin/serializer

#12026 docs(aggregators.derivative): Remove incorrect comment
  plugins/aggregators/derivative/README.md
Labels: docs, plugin/aggregator

#12120 docs: ran make docs
  plugins/aggregators/derivative/README.md
Labels: docs

#12119 chore(deps): update OpenTelemetry v0.2.30 / v0.63.0
  go.mod
  go.sum
  plugins/inputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry_test.go
Labels: chore

#11552 feat: Add binary parser
  docs/DATA_FORMATS_INPUT.md
  plugins/parsers/all/binary.go
  plugins/parsers/binary/README.md
  plugins/parsers/binary/config.go
  plugins/parsers/binary/entry.go
  plugins/parsers/binary/entry_test.go
  plugins/parsers/binary/host_endianess_be.go
  plugins/parsers/binary/host_endianess_le.go
  plugins/parsers/binary/parser.go
  plugins/parsers/binary/parser_test.go
  plugins/parsers/binary/testcases/multiple_messages/expected.out
  plugins/parsers/binary/testcases/multiple_messages/messageA.bin
  plugins/parsers/binary/testcases/multiple_messages/messageB.bin
  plugins/parsers/binary/testcases/multiple_messages/messageC.bin
  plugins/parsers/binary/testcases/multiple_messages/telegraf.conf
  plugins/parsers/registry_test.go
Labels: feat, ready for final review, plugin/parser

#11986 chore(parsers.xpath): Add correct deprecation tags
  plugins/parsers/xpath/parser.go
Labels: area/xml, ready for final review, plugin/parser, chore
