Repository influxdata/telegraf, pull requests merged in 2022-04, with the labels that each got.

#10935 chore: add actions/setup-go@v2 to linter config
  .github/workflows/golangci-lint.yml
  Makefile
Labels: chore

#7896 feat(inputs.mongodb): Add metrics about files currently open and currently active data handles
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongostat.go
Labels: feat, area/mongodb, ready for final review

#10886 feat: generate the plugins sample config
  .circleci/config.yml
  Makefile
  config/config.go
  config/config_test.go
  docs/AGGREGATORS.md
  docs/INPUTS.md
  docs/OUTPUTS.md
  docs/PROCESSORS.md
  docs/developers/SAMPLE_CONFIG.md
  go.mod
  go.sum
  plugin.go
  plugins/common/shim/config_test.go
  plugins/common/shim/goshim_test.go
  plugins/processors/streamingprocessor.go
  tools/generate_plugindata/main.go
  tools/generate_plugindata/main_test.go
Labels: ready for final review

#10912 feat: migrate aggregator plugins to new sample config format
  plugins/aggregators/basicstats/basicstats.go
  plugins/aggregators/basicstats/basicstats_sample_config.go
  plugins/aggregators/derivative/README.md
  plugins/aggregators/derivative/derivative.go
  plugins/aggregators/derivative/derivative_sample_config.go
  plugins/aggregators/final/README.md
  plugins/aggregators/final/final.go
  plugins/aggregators/final/final_sample_config.go
  plugins/aggregators/histogram/histogram.go
  plugins/aggregators/histogram/histogram_sample_config.go
  plugins/aggregators/merge/README.md
  plugins/aggregators/merge/merge.go
  plugins/aggregators/merge/merge_sample_config.go
  plugins/aggregators/merge/merge_test.go
  plugins/aggregators/minmax/minmax.go
  plugins/aggregators/minmax/minmax_sample_config.go
  plugins/aggregators/quantile/README.md
  plugins/aggregators/quantile/quantile.go
  plugins/aggregators/quantile/quantile_sample_config.go
  plugins/aggregators/starlark/README.md
  plugins/aggregators/starlark/starlark.go
  plugins/aggregators/starlark/starlark_sample_config.go
  plugins/aggregators/valuecounter/README.md
  plugins/aggregators/valuecounter/valuecounter.go
  plugins/aggregators/valuecounter/valuecounter_sample_config.go
Labels: feat, ready for final review

#10932 fix(inputs.prometheus): moved from watcher to informer
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/kubernetes.go
  plugins/inputs/prometheus/prometheus.go
Labels: fix

#10958 fix: update influxdb_v2 error message
  plugins/outputs/influxdb_v2/influxdb_v2.go
Labels: fix, ready for final review

#10962 chore(inputs): add descriptions to config in README.md
  plugins/inputs/conntrack/README.md
  plugins/inputs/example/README.md
  plugins/inputs/httpjson/README.md
  plugins/inputs/influxdb_listener/README.md
  plugins/inputs/mqtt_consumer/README.md
  plugins/inputs/nats_consumer/README.md
  plugins/inputs/postgresql/README.md
  plugins/inputs/ras/README.md
  plugins/inputs/sflow/README.md
  plugins/inputs/snmp_legacy/README.md
  plugins/inputs/snmp_trap/README.md
  plugins/inputs/sql/README.md
  plugins/inputs/sqlserver/README.md
  plugins/inputs/suricata/README.md
  plugins/inputs/tail/README.md
  plugins/inputs/webhooks/README.md
  plugins/inputs/win_eventlog/README.md
  plugins/inputs/win_services/README.md
Labels: ready for final review, chore

#10750 fix: metadata readme description csv parser
  plugins/parsers/csv/README.md
  plugins/parsers/csv/parser.go
Labels: docs, fix, ready for final review, plugin/parser, area/csv

#10940 fix: update starlark 7a1108eaa012->d1966c6b9fcd
  go.mod
  go.sum
  plugins/aggregators/starlark/README.md
  plugins/processors/starlark/README.md
Labels: docs, fix, ready for final review, dependencies

#10959 fix: remove overly verbose info message from cisco mdt
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
Labels: fix, ready for final review

#10963 chore: update opentelemetry plugins
  go.mod
  go.sum
  plugins/inputs/opentelemetry/opentelemetry_test.go
  plugins/outputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry_test.go
Labels: chore

#10947 fix: align the default value for msg size
  plugins/inputs/cisco_telemetry_mdt/README.md
Labels: fix

#10977 chore: remove go generate from CI tests
  .circleci/config.yml
  plugins/inputs/vsphere/vsphere_test.go
Labels: chore

#10896 chore: add logging to graylog output tests
  plugins/outputs/graylog/graylog_test.go
Labels: chore

#10966 fix: bump github.com/Azure/azure-kusto-go from 0.5.0 to 0.60 and make timing more granular
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/outputs/azure_data_explorer/azure_data_explorer.go
Labels: fix, ready for final review

#10930 fix(inputs/aerospike): Statistics query bug
  plugins/inputs/aerospike/aerospike.go
  plugins/inputs/aerospike/aerospike_test.go
Labels: fix, area/aerospike, ready for final review, plugin/input

#10850 fix: ensure aliyuncms metrics accept array, fix discovery
  go.mod
  go.sum
  plugins/inputs/aliyuncms/aliyuncms.go
  plugins/inputs/aliyuncms/aliyuncms_test.go
  plugins/inputs/aliyuncms/discovery.go
Labels: fix, ready for final review

#10567 feat(inputs/sqlserver): add RecentBackups query
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserver.go
  plugins/inputs/sqlserver/sqlserverqueries.go
Labels: feat, area/sqlserver, ready for final review, plugin/input

#10961 chore: Update Go to 1.18.1
  .circleci/config.yml
  Makefile
  README.md
  docs/developers/PACKAGING.md
  go.mod
  go.sum
  scripts/ci.docker
  scripts/installgo_mac.sh
  scripts/installgo_windows.sh
Labels: ready for final review, chore

#10983 chore: go mod tidy
  go.sum
Labels: ready for final review

#10988 test: use `T.TempDir` to create temporary test directory
  internal/rotate/file_writer_test.go
  logger/logger_test.go
  plugins/inputs/ceph/ceph_test.go
  plugins/inputs/conntrack/conntrack_test.go
  plugins/inputs/directory_monitor/directory_monitor_test.go
  plugins/inputs/linux_sysctl_fs/linux_sysctl_fs_test.go
  plugins/inputs/logparser/logparser_test.go
  plugins/inputs/postfix/postfix_test.go
  plugins/inputs/procstat/procstat_test.go
  plugins/inputs/socket_listener/socket_listener_test.go
  plugins/inputs/suricata/suricata_test.go
  plugins/inputs/syslog/nontransparent_test.go
  plugins/inputs/syslog/octetcounting_test.go
  plugins/inputs/syslog/rfc5426_test.go
  plugins/inputs/syslog/syslog_test.go
  plugins/outputs/file/file_test.go
  plugins/outputs/influxdb/http_test.go
  plugins/outputs/socket_writer/socket_writer_test.go
  plugins/outputs/sql/sql_test.go
  plugins/outputs/sql/sqlite_test.go
  testutil/socket.go
Labels: ready for final review, test

#10982 docs: regex processor only works on strings
  plugins/processors/regex/README.md
Labels: docs

#10984 chore: update opentelemetry plugins
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/opentelemetry/grpc_services.go
  plugins/inputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry_test.go
Labels: ready for final review, chore

#10993 chore: update pull request with master when running CI
  .circleci/config.yml
Labels: chore

#10916 chore: add readme linter
  tools/readme_linter/README.md
  tools/readme_linter/assert.go
  tools/readme_linter/main.go
  tools/readme_linter/plugin.go
  tools/readme_linter/rules.go
  tools/readme_linter/set.go
Labels: chore

#10923 fix: correctly parse various numeric forms
  plugins/inputs/smart/smart.go
  plugins/inputs/smart/smart_test.go
Labels: fix, ready for final review

#10486 fix: Add mariadb_dialect to address the MariaDB differences in INNODB_METRICS
  plugins/inputs/mysql/README.md
  plugins/inputs/mysql/mysql.go
Labels: fix, ready for final review

#11004 fix: typo in influx line protocol parser docs
  plugins/parsers/influx/README.md
Labels: fix

#11001 fix: Update Consul Header Token
  plugins/inputs/consul_agent/consul_agent.go
Labels: fix

#10999 docs: Add openstack metadata external plugin
  EXTERNAL_PLUGINS.md
Labels: docs

#11010 fix: use Sprint to cast to strings (#11007)
  plugins/inputs/gnmi/gnmi.go
Labels: fix

#10951 chore: Fix readme linter errors for output plugins
  plugins/outputs/amon/README.md
  plugins/outputs/amqp/README.md
  plugins/outputs/application_insights/README.md
  plugins/outputs/azure_data_explorer/README.md
  plugins/outputs/azure_monitor/README.md
  plugins/outputs/bigquery/README.md
  plugins/outputs/cloud_pubsub/README.md
  plugins/outputs/cloudwatch/README.md
  plugins/outputs/cloudwatch_logs/README.md
  plugins/outputs/cratedb/README.md
  plugins/outputs/datadog/README.md
  plugins/outputs/dynatrace/README.md
  plugins/outputs/elasticsearch/README.md
  plugins/outputs/event_hubs/README.md
  plugins/outputs/execd/README.md
  plugins/outputs/graphite/README.md
  plugins/outputs/graylog/README.md
  plugins/outputs/groundwork/README.md
  plugins/outputs/http/README.md
  plugins/outputs/influxdb/README.md
  plugins/outputs/instrumental/README.md
  plugins/outputs/kafka/README.md
  plugins/outputs/kinesis/README.md
  plugins/outputs/librato/README.md
  plugins/outputs/loki/README.md
  plugins/outputs/mongodb/README.md
  plugins/outputs/mqtt/README.md
  plugins/outputs/newrelic/README.md
  plugins/outputs/nsq/README.md
  plugins/outputs/opentelemetry/README.md
  plugins/outputs/opentsdb/README.md
  plugins/outputs/prometheus_client/README.md
  plugins/outputs/riemann/README.md
  plugins/outputs/riemann_legacy/README.md
  plugins/outputs/signalfx/README.md
  plugins/outputs/socket_writer/README.md
  plugins/outputs/sql/README.md
  plugins/outputs/stackdriver/README.md
  plugins/outputs/sumologic/README.md
  plugins/outputs/syslog/README.md
  plugins/outputs/timestream/README.md
  plugins/outputs/wavefront/README.md
  plugins/outputs/websocket/README.md
  plugins/outputs/yandex_cloud_monitoring/README.md
Labels: ready for final review, chore

#11015 fix: allow Makefile to work on Windows
  Makefile
Labels: fix, ready for final review

#11013 fix(cmd): Also allow 0 outputs when using test-wait parameter
  cmd/telegraf/telegraf.go
Labels: fix, area/agent, ready for final review

#11008 fix: add mutex to gnmi lookup map (#11006)
  plugins/inputs/gnmi/gnmi.go
Labels: fix

#10976 fix: duplicate influxdb listener writes
  plugins/inputs/influxdb_listener/influxdb_listener.go
Labels: fix

#11024 refactor(gnmi): use external xpath parser
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/gnmi/gnmi.go
  plugins/inputs/gnmi/gnmi_test.go
Labels: ready for final review, refactor

#11009 chore: Adding influx's semantic commit and PR message checker, so we …
  .github/workflows/semantic.yml
Labels: security, ready for final review

#10925 fix: add tracefs to ignore, reduce log level
  plugins/inputs/system/ps.go
Labels: fix

#11041 chore: increase timeout for darwin packaging
  .circleci/config.yml
Labels: chore

#11031 chore: enable linting of shell scripts
  .github/workflows/linter.yml
  scripts/check-dynamic-glibc-versions.sh
Labels: chore

#10954 feat(outputs.http): Support configuration of `MaxIdleConns` and `MaxIdleConnsPerHost`
  plugins/common/http/config.go
  plugins/outputs/http/README.md
  plugins/outputs/http/http_test.go
Labels: feat

#10979 fix: datadog count metrics
  plugins/outputs/datadog/README.md
  plugins/outputs/datadog/datadog.go
Labels: fix
