Repository influxdata/telegraf, pull requests merged in 2022-06, with the labels that each got.

#11212 chore: update github.com/opencontainers/runc from v1.0.2 to v1.1.2
  go.mod
  go.sum
Labels: ready for final review, chore

#11211 test: enable logging with testcontainers
  plugins/inputs/aerospike/aerospike_test.go
  plugins/outputs/cratedb/cratedb_test.go
  testutil/container.go
Labels: ready for final review, test

#11217 fix: Update sample.conf for prometheus
  plugins/inputs/prometheus/sample.conf
  plugins/outputs/prometheus_client/sample.conf
Labels: docs, area/prometheus, fix

#11202 fix(inputs/modbus): #11105 fix requests starting with an omitted field
  plugins/inputs/modbus/modbus_test.go
  plugins/inputs/modbus/request.go
Labels: fix, area/modbus, ready for final review

#11241 fix: Upgrade xpath and fix code
  go.mod
  go.sum
  plugins/parsers/xpath/parser_test.go
Labels: fix

#11236 chore: Bump riemann-go-client and remove replacement
  go.mod
  go.sum
Labels: chore

#11210 docs: initial update of integration test docs
  docs/INTEGRATION_TESTS.md
Labels: docs, ready for final review

#11206 test: migrate kafka to testcontainers
  plugins/outputs/kafka/kafka_test.go
Labels: ready for final review, test

#11208 test: migrate mcrouter to testcontainers
  plugins/inputs/mcrouter/mcrouter_test.go
Labels: ready for final review, test

#11209 test: migrate postgres to testcontainers
  plugins/inputs/postgresql/postgresql_test.go
  plugins/inputs/postgresql_extensible/postgresql_extensible_test.go
Labels: ready for final review, test

#11239 chore: Bump apcupds and remove the replacement
  go.mod
  go.sum
Labels: chore

#11207 test: migrate elasticsearch to testcontainers
  plugins/inputs/elasticsearch_query/elasticsearch_query_test.go
  plugins/outputs/elasticsearch/elasticsearch_test.go
Labels: ready for final review, test

#11216 feat: update query store and latch performance counters
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sqlserverqueries.go
Labels: ready for final review

#11243 test: remove docker-compose.yml test file
  CONTRIBUTING.md
  Makefile
  docker-compose.yml
Labels: test

#11237 fix: re-add event to splunk serializer
  plugins/serializers/splunkmetric/splunkmetric.go
  plugins/serializers/splunkmetric/splunkmetric_test.go
Labels: fix, ready for final review

#11247 chore: rename circleci executor
  .circleci/config.yml
Labels: chore

#11248 chore: update go from v1.18.1 to v1.18.3
  .circleci/config.yml
  Makefile
  docs/developers/PACKAGING.md
  scripts/ci.docker
  scripts/installgo_mac.sh
  scripts/installgo_windows.sh
Labels: chore

#11245 test: testcontainer hardening
  plugins/inputs/elasticsearch_query/elasticsearch_query_test.go
  plugins/inputs/mysql/mysql_test.go
  plugins/inputs/openldap/openldap_test.go
  plugins/inputs/pgbouncer/pgbouncer_test.go
  plugins/inputs/sql/sql_test.go
  plugins/inputs/zookeeper/zookeeper_test.go
  plugins/outputs/mongodb/mongodb_test.go
  plugins/outputs/sql/sql_test.go
  testutil/container.go
Labels: test

#11255 test: remove restore integration test cache
  .circleci/config.yml
Labels: test

#11254 feat(intel_powerstat): Add uncore frequency metrics
  plugins/inputs/intel_powerstat/README.md
  plugins/inputs/intel_powerstat/file_mock_test.go
  plugins/inputs/intel_powerstat/intel_powerstat.go
  plugins/inputs/intel_powerstat/intel_powerstat_test.go
  plugins/inputs/intel_powerstat/msr.go
  plugins/inputs/intel_powerstat/msr_mock_test.go
  plugins/inputs/intel_powerstat/msr_test.go
  plugins/inputs/intel_powerstat/rapl_mock_test.go
  plugins/inputs/intel_powerstat/sample.conf
Labels: feat, ready for final review

#11262 docs: add the missing word love :heart:
  CONTRIBUTING.md
Labels: docs, ready for final review

#11260 fix: update modernc.org/sqlite from v1.10.8 to v1.17.3
  go.mod
  go.sum
  plugins/inputs/sql/drivers_sqlite.go
  plugins/inputs/sql/drivers_sqlite_other.go
Labels: fix

#10960 chore: Fix readme linter errors for processor, aggregator, and parser plugins
  plugins/aggregators/basicstats/README.md
  plugins/aggregators/derivative/README.md
  plugins/aggregators/histogram/README.md
  plugins/aggregators/merge/README.md
  plugins/aggregators/quantile/README.md
  plugins/aggregators/starlark/README.md
  plugins/parsers/collectd/README.md
  plugins/parsers/csv/README.md
  plugins/parsers/dropwizard/README.md
  plugins/parsers/form_urlencoded/README.md
  plugins/parsers/graphite/README.md
  plugins/parsers/grok/README.md
  plugins/parsers/influx/README.md
  plugins/parsers/json/README.md
  plugins/parsers/json_v2/README.md
  plugins/parsers/logfmt/README.md
  plugins/parsers/nagios/README.md
  plugins/parsers/prometheus/README.md
  plugins/parsers/prometheusremotewrite/README.md
  plugins/parsers/value/README.md
  plugins/parsers/wavefront/README.md
  plugins/parsers/xpath/README.md
  plugins/processors/clone/README.md
  plugins/processors/converter/README.md
  plugins/processors/defaults/README.md
  plugins/processors/enum/README.md
  plugins/processors/execd/README.md
  plugins/processors/filepath/README.md
  plugins/processors/noise/README.md
  plugins/processors/override/README.md
  plugins/processors/pivot/README.md
  plugins/processors/port_name/README.md
  plugins/processors/regex/README.md
  plugins/processors/s2geo/README.md
  plugins/processors/starlark/README.md
  plugins/processors/strings/README.md
  plugins/processors/template/README.md
  plugins/processors/topk/README.md
  plugins/processors/unpivot/README.md
Labels: chore

#11264 fix: bump github.com/tidwall/gjson from 1.10.2 to 1.14.1
  go.mod
  go.sum
  plugins/parsers/json_v2/parser.go
Labels: fix, dependencies

#11266 fix: update github.com/containerd/containerd from v1.5.11 to v1.5.13
  go.mod
  go.sum
Labels: fix

#10964 chore: Fix readme linter errors for input plugins A-D
  plugins/inputs/activemq/README.md
  plugins/inputs/aerospike/README.md
  plugins/inputs/aliyuncms/README.md
  plugins/inputs/amd_rocm_smi/README.md
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/apache/README.md
  plugins/inputs/apcupsd/README.md
  plugins/inputs/aurora/README.md
  plugins/inputs/bcache/README.md
  plugins/inputs/beanstalkd/README.md
  plugins/inputs/beat/README.md
  plugins/inputs/bind/README.md
  plugins/inputs/bond/README.md
  plugins/inputs/burrow/README.md
  plugins/inputs/cassandra/README.md
  plugins/inputs/ceph/README.md
  plugins/inputs/cgroup/README.md
  plugins/inputs/chrony/README.md
  plugins/inputs/cisco_telemetry_mdt/README.md
  plugins/inputs/clickhouse/README.md
  plugins/inputs/cloud_pubsub/README.md
  plugins/inputs/cloud_pubsub_push/README.md
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/conntrack/README.md
  plugins/inputs/consul/README.md
  plugins/inputs/consul_agent/README.md
  plugins/inputs/couchbase/README.md
  plugins/inputs/couchdb/README.md
  plugins/inputs/csgo/README.md
  plugins/inputs/dcos/README.md
  plugins/inputs/directory_monitor/README.md
  plugins/inputs/disk/README.md
  plugins/inputs/diskio/README.md
  plugins/inputs/disque/README.md
  plugins/inputs/dmcache/README.md
  plugins/inputs/dns_query/README.md
  plugins/inputs/docker/README.md
  plugins/inputs/docker_log/README.md
  plugins/inputs/dovecot/README.md
  plugins/inputs/dpdk/README.md
Labels: chore

#11214 chore: Fix readme linter errors for input plugins E-L
  plugins/inputs/ecs/README.md
  plugins/inputs/elasticsearch/README.md
  plugins/inputs/elasticsearch_query/README.md
  plugins/inputs/ethtool/README.md
  plugins/inputs/eventhub_consumer/README.md
  plugins/inputs/example/README.md
  plugins/inputs/exec/README.md
  plugins/inputs/execd/README.md
  plugins/inputs/fail2ban/README.md
  plugins/inputs/fibaro/README.md
  plugins/inputs/file/README.md
  plugins/inputs/filestat/README.md
  plugins/inputs/fluentd/README.md
  plugins/inputs/github/README.md
  plugins/inputs/gnmi/README.md
  plugins/inputs/graylog/README.md
  plugins/inputs/haproxy/README.md
  plugins/inputs/http/README.md
  plugins/inputs/http_listener_v2/README.md
  plugins/inputs/http_response/README.md
  plugins/inputs/httpjson/README.md
  plugins/inputs/hugepages/README.md
  plugins/inputs/icinga2/README.md
  plugins/inputs/influxdb/README.md
  plugins/inputs/influxdb_v2_listener/README.md
  plugins/inputs/intel_pmu/README.md
  plugins/inputs/intel_rdt/README.md
  plugins/inputs/internal/README.md
  plugins/inputs/internet_speed/README.md
  plugins/inputs/interrupts/README.md
  plugins/inputs/ipmi_sensor/README.md
  plugins/inputs/iptables/README.md
  plugins/inputs/ipvs/README.md
  plugins/inputs/jenkins/README.md
  plugins/inputs/jolokia/README.md
  plugins/inputs/jolokia2/README.md
  plugins/inputs/jti_openconfig_telemetry/README.md
  plugins/inputs/kafka_consumer/README.md
  plugins/inputs/kafka_consumer_legacy/README.md
  plugins/inputs/kapacitor/README.md
  plugins/inputs/kernel/README.md
  plugins/inputs/kernel_vmstat/README.md
  plugins/inputs/kibana/README.md
  plugins/inputs/kinesis_consumer/README.md
  plugins/inputs/knx_listener/README.md
  plugins/inputs/kube_inventory/README.md
  plugins/inputs/kubernetes/README.md
  plugins/inputs/lanz/README.md
  plugins/inputs/leofs/README.md
  plugins/inputs/linux_sysctl_fs/README.md
  plugins/inputs/logparser/README.md
  plugins/inputs/logstash/README.md
  plugins/inputs/lustre2/README.md
  plugins/inputs/lvm/README.md
Labels: docs

#11261 fix: remove full access permissions
  plugins/inputs/ceph/ceph_test.go
  plugins/inputs/directory_monitor/directory_monitor.go
Labels: fix, security, ready for final review

#11272 fix: add missing build constraints for sqlite
  plugins/inputs/sql/drivers_sqlite.go
  plugins/inputs/sql/drivers_sqlite_other.go
  scripts/check-deps.sh
Labels: fix

#11218 feat: Migrate xpath parser to new style
  config/config.go
  config/config_test.go
  plugins/parsers/all/all.go
  plugins/parsers/registry.go
  plugins/parsers/registry_test.go
  plugins/parsers/xpath/parser.go
  plugins/parsers/xpath/parser_test.go
Labels: feat, area/xml, ready for final review, plugin/parser

#11253 fix: Always build README-embedder for host-architecture
  Makefile
Labels: fix, ready for final review

#11234 fix(inputs/directory_monitor): Add support for multiline file parsing
  plugins/inputs/directory_monitor/README.md
  plugins/inputs/directory_monitor/directory_monitor.go
  plugins/inputs/directory_monitor/directory_monitor_test.go
  plugins/inputs/directory_monitor/sample.conf
Labels: fix, area/json, area/xml, ready for final review, plugin/input

#11281 test: add install go for linux, use in integration tests
  .circleci/config.yml
  docs/developers/PACKAGING.md
  scripts/installgo_linux.sh
Labels: ready for final review, test

#11291 fix: Don't rebase on master when building packages
  .circleci/config.yml
Labels: fix

#11271 feat(inputs.x509_cert): add smtp protocol
  plugins/inputs/x509_cert/README.md
  plugins/inputs/x509_cert/sample.conf
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
Labels: feat, ready for final review

#11302 fix(parsers/xpath): Reduce debug messages when empty selection is allowed
  plugins/parsers/xpath/parser.go
Labels: fix, area/logging, area/xml, ready for final review, plugin/parser

#11300 feat(outputs.groundwork): Add default appType as config option
  plugins/outputs/groundwork/README.md
  plugins/outputs/groundwork/groundwork.go
  plugins/outputs/groundwork/groundwork_test.go
Labels: feat, ready for final review, plugin/output

#11311 fix: Prevent concurrent map writes to c.UnusedFields
  config/config.go
Labels: fix, ready for final review

#11314 docs: explain directly connecting to mongo node
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/sample.conf
Labels: ready for final review

#11315 chore: Remove prefix to use the default `chore(deps)`
  .github/dependabot.yml
Labels: chore

#11309 test: update wait for statement for postgres
  plugins/inputs/postgresql/postgresql_test.go
Labels: ready for final review, test

#11317 test: mark integration tests correctly
  plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_integration_test.go
  plugins/inputs/leofs/leofs_test.go
  plugins/inputs/sqlserver/azuresqldbqueries_test.go
  plugins/inputs/sqlserver/azuresqlmanagedqueries_test.go
  plugins/inputs/sqlserver/azuresqlpoolqueries_test.go
  plugins/inputs/sqlserver/sqlserver_test.go
  plugins/inputs/x509_cert/x509_cert_test.go
  plugins/outputs/event_hubs/event_hubs_test.go
  plugins/outputs/opentsdb/opentsdb_test.go
  plugins/outputs/riemann_legacy/riemann_legacy_test.go
  plugins/processors/ifname/ifname_test.go
Labels: ready for final review, test

#11326 chore: make apt-get instructions consistent and add GPG fingerprint
  README.md
Labels: chore

#11256 test: add coveralls coverage
  .circleci/config.yml
Labels: ready for final review, test

#11280 fix: filter out views in mongodb lookup
  plugins/inputs/mongodb/mongodb_server.go
Labels: fix, ready for final review

#9333 feat(redis): add Redis 6 ACL auth support
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/redis/README.md
  plugins/inputs/redis/redis.go
  plugins/inputs/redis/redis_test.go
Labels: feat, area/redis, ready for final review

#9319 feat(x509_cert): add proxy support
  plugins/common/proxy/connect.go
  plugins/common/proxy/dialer.go
  plugins/common/proxy/proxy.go
  plugins/inputs/cloudwatch/README.md
  plugins/inputs/cloudwatch/cloudwatch_test.go
  plugins/inputs/x509_cert/README.md
  plugins/inputs/x509_cert/x509_cert.go
  plugins/inputs/x509_cert/x509_cert_test.go
  plugins/outputs/datadog/README.md
  plugins/outputs/websocket/README.md
Labels: feat, ready for final review

#11348 docs: Sync sample.conf for recent features
  plugins/inputs/cloudwatch/sample.conf
  plugins/inputs/redis/sample.conf
  plugins/inputs/x509_cert/sample.conf
  plugins/outputs/datadog/sample.conf
  plugins/outputs/websocket/sample.conf
Labels: docs, ready for final review

#11337 chore: move agent config into seperate file
  config/agent.conf
  config/config.go
Labels: ready for final review, chore

#11307 feat: Add CSV serializer
  config/config.go
  docs/DATA_FORMATS_OUTPUT.md
  plugins/serializers/csv/README.md
  plugins/serializers/csv/csv.go
  plugins/serializers/csv/csv_test.go
  plugins/serializers/csv/testcases/basic.conf
  plugins/serializers/csv/testcases/basic.csv
  plugins/serializers/csv/testcases/header.conf
  plugins/serializers/csv/testcases/header.csv
  plugins/serializers/csv/testcases/nanoseconds.conf
  plugins/serializers/csv/testcases/nanoseconds.csv
  plugins/serializers/csv/testcases/prefix.conf
  plugins/serializers/csv/testcases/prefix.csv
  plugins/serializers/csv/testcases/rfc3339.conf
  plugins/serializers/csv/testcases/rfc3339.csv
  plugins/serializers/csv/testcases/semicolon.conf
  plugins/serializers/csv/testcases/semicolon.csv
  plugins/serializers/registry.go
Labels: feat, ready for final review, plugin/serializer, area/csv

#11276 fix: Restore sample configurations broken during initial migration
  plugins/aggregators/derivative/README.md
  plugins/aggregators/derivative/sample.conf
  plugins/inputs/cassandra/README.md
  plugins/inputs/cassandra/sample.conf
  plugins/inputs/kafka_consumer_legacy/README.md
  plugins/inputs/kafka_consumer_legacy/sample.conf
  plugins/inputs/logparser/README.md
  plugins/inputs/logparser/sample.conf
  plugins/inputs/riemann_listener/README.md
  plugins/inputs/riemann_listener/sample.conf
  plugins/inputs/snmp_legacy/README.md
  plugins/inputs/snmp_legacy/sample.conf
  plugins/inputs/vsphere/README.md
  plugins/inputs/vsphere/sample.conf
  plugins/outputs/logzio/README.md
  plugins/outputs/logzio/sample.conf
  tools/readme_config_includer/generator.go
Labels: docs, fix, ready for final review

#11376 docs: swap bytes sent/recv descriptions in nfsclient
  plugins/inputs/nfsclient/README.md
Labels: docs

#11374 feat: Migrate wavefront parser to new style
  plugins/parsers/all/all.go
  plugins/parsers/registry.go
  plugins/parsers/wavefront/parser.go
  plugins/parsers/wavefront/parser_test.go
Labels: feat, area/wavefront, ready for final review, plugin/parser

#9717 feat: allow collecting node-level metrics for Couchbase buckets
  plugins/inputs/couchbase/README.md
  plugins/inputs/couchbase/couchbase.go
  plugins/inputs/couchbase/couchbase_test.go
Labels: feat, area/couchbase, ready for final review

#11240 chore: Remove 'github.com/satori/go.uuid' replacement
  go.mod
  go.sum
  scripts/check-deps.sh
Labels: chore

#11401 chore: Remove 'github.com/cisco-ie/nx-telemetry-proto' replacement
  go.mod
  go.sum
Labels: dependencies, chore

#11397 fix: remove jolokia2 panic info
  plugins/inputs/jolokia2/common/gatherer.go
  plugins/inputs/jolokia2/common/point_builder.go
Labels: fix, area/jolokia, ready for final review

#11413 fix: Sync back sample.confs for inputs.couchbase and outputs.groundwork.
  plugins/inputs/couchbase/README.md
  plugins/inputs/couchbase/sample.conf
  plugins/outputs/groundwork/README.md
  plugins/outputs/groundwork/sample.conf
Labels: docs, fix, ready for final review

#11409 chore: move generation of sample toml out of config.go
  cmd/telegraf/telegraf.go
  config/config.go
  config/printer/agent.conf
  config/printer/printer.go
Labels: ready for final review, chore

#11381 feat: Migrate form_urlencoded parser to new style
  config/config.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
  plugins/parsers/all/all.go
  plugins/parsers/form_urlencoded/parser.go
  plugins/parsers/registry.go
Labels: feat, ready for final review, plugin/parser

#11201 feat(outputs/wavefront): make maximum http batch size configurable
  plugins/outputs/wavefront/README.md
  plugins/outputs/wavefront/sample.conf
  plugins/outputs/wavefront/wavefront.go
  plugins/outputs/wavefront/wavefront_test.go
Labels: feat, area/wavefront, ready for final review, plugin/output

#11407 feat: migrate value parser to new style
  plugins/inputs/exec/exec_test.go
  plugins/inputs/http/http_test.go
  plugins/inputs/kafka_consumer/kafka_consumer_test.go
  plugins/parsers/all/all.go
  plugins/parsers/registry.go
  plugins/parsers/value/parser.go
  plugins/parsers/value/parser_test.go
Labels: feat, ready for final review, plugin/parser

#11405 feat: Migrate graphite parser to new style
  config/config_test.go
  plugins/inputs/kafka_consumer_legacy/kafka_consumer_legacy_test.go
  plugins/inputs/statsd/statsd.go
  plugins/inputs/tcp_listener/tcp_listener_test.go
  plugins/parsers/all/all.go
  plugins/parsers/graphite/parser.go
  plugins/parsers/graphite/parser_test.go
  plugins/parsers/registry.go
Labels: feat, plugin/parser

#11335 fix: Bring back old xpath section names
  config/deprecation.go
  models/log.go
  plugin.go
  plugins/parsers/xpath/parser.go
Labels: regression, fix, area/xml, ready for final review, plugin/parser

#11422 test: exchange confused parameters (expected vs actual)
  plugins/outputs/http/http_test.go
Labels: test

#11371 feat: Migrate dropwizard parser to new style
  config/config.go
  plugins/parsers/all/all.go
  plugins/parsers/dropwizard/parser.go
  plugins/parsers/dropwizard/parser_test.go
  plugins/parsers/registry.go
  plugins/parsers/registry_test.go
Labels: feat, ready for final review, plugin/parser

#11408 feat: migrate grok to new parser style
  plugins/inputs/file/file_test.go
  plugins/inputs/logparser/logparser.go
  plugins/inputs/logparser/logparser_test.go
  plugins/inputs/tail/tail_test.go
  plugins/parsers/all/all.go
  plugins/parsers/grok/parser.go
  plugins/parsers/registry.go
Labels: feat, ready for final review, plugin/parser

#11430 test: run check-update on dnf/yum
  tools/package_lxd_test/container.go
Labels: test

#11233 feat: adding aws metric streams input plugin
  plugins/inputs/all/all.go
  plugins/inputs/cloudwatch_metric_streams/README.md
  plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams.go
  plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams_test.go
  plugins/inputs/cloudwatch_metric_streams/sample.conf
  plugins/inputs/cloudwatch_metric_streams/testdata/records.gz
Labels: feat, new plugin, ready for final review, plugin/input

#11288 fix: Add reset-mode flag for CSV parser
  config/config_test.go
  plugins/parsers/csv/README.md
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
Labels: fix, ready for final review

#11402 feat: Migrate nagios parser to new style
  plugins/inputs/exec/exec.go
  plugins/parsers/all/all.go
  plugins/parsers/nagios/parser.go
  plugins/parsers/nagios/parser_test.go
  plugins/parsers/registry.go
Labels: feat, ready for final review, plugin/parser
