Repository influxdata/telegraf, pull requests merged in 2022-02, with the labels that each got.

#10179 fix(outputs/azure_data_explorer): Added azureBlob controls to lower RAM usage
  go.mod
  go.sum
  plugins/outputs/azure_data_explorer/azure_data_explorer.go
  plugins/outputs/azure_monitor/azure_monitor_test.go
Labels: fix, area/azure, ready for final review, plugin/output

#9697 feat: Xtremio input
  plugins/inputs/all/all.go
  plugins/inputs/xtremio/README.md
  plugins/inputs/xtremio/testdata/sample_bbu_response.json
  plugins/inputs/xtremio/testdata/sample_get_bbu_response.json
  plugins/inputs/xtremio/xtremio.go
  plugins/inputs/xtremio/xtremio_test.go
  plugins/inputs/xtremio/xtremio_types.go
Labels: new plugin, ready for final review, plugin/input

#10530 feat: Add caching to internet_speed
  plugins/inputs/internet_speed/README.md
  plugins/inputs/internet_speed/internet_speed.go
Labels: feat, ready for final review, plugin/input

#10541 docs: updates readme to add service SID auth and cleans up AAD auth d…
  plugins/inputs/sqlserver/README.md
Labels: docs, area/sqlserver, ready for final review, plugin/input

#10560 fix: remove dotfile artifacts
  .circleci/config.yml
Labels: fix

#10575 fix: Statefull parser handling
  plugins/inputs/file/file.go
  plugins/inputs/file/file_test.go
  plugins/inputs/http/http.go
  plugins/inputs/http/http_test.go
Labels: fix

#10559 feat: Add autorestart and restartdelay flags to Windows service
  cmd/telegraf/telegraf.go
  cmd/telegraf/telegraf_windows.go
  docs/WINDOWS_SERVICE.md
  internal/usage_windows.go
Labels: feat, ready for final review

#10579 style: Add deprecated warning and version to win_perf_counters option
  plugins/inputs/win_perf_counters/README.md
  plugins/inputs/win_perf_counters/win_perf_counters.go
Labels: area/windows, ready for final review, style

#10582 chore: fix typo in bug report template
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Labels: chore

#10513 fix[elasticsearch output]: add scheme to fix error in sniffing option
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/outputs/elasticsearch/elasticsearch.go
Labels: area/elasticsearch, fix, ready for final review, plugin/output

#10520 feat: Histogram aggregator metric expiration
  plugins/aggregators/histogram/histogram.go
  plugins/aggregators/histogram/histogram_test.go
Labels: feat, ready for final review, plugin/aggregator

#10583 docs: add expriation_interval to histogram README
  plugins/aggregators/histogram/README.md
Labels: docs

#10468 fix(parsers.json_v2): allow optional paths and handle wrong paths correctly
  config/config.go
  plugins/parsers/json_v2/README.md
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/parser_test.go
  plugins/parsers/json_v2/testdata/optional/expected.out
  plugins/parsers/json_v2/testdata/optional/input.json
  plugins/parsers/json_v2/testdata/optional/telegraf.conf
  plugins/parsers/json_v2/testdata/wrong_path/expected.out
  plugins/parsers/json_v2/testdata/wrong_path/input.json
  plugins/parsers/json_v2/testdata/wrong_path/telegraf.conf
Labels: fix, ready for final review

#10598 fix: bump github.com/Azure/azure-kusto-go from 0.5.0 to 0.5.2
  go.mod
  go.sum
Labels: fix

#7484 feat: Add dynamic tagging to gnmi plugin
  plugins/inputs/gnmi/README.md
  plugins/inputs/gnmi/gnmi.go
  plugins/inputs/gnmi/gnmi_test.go
Labels: feat, area/gnmi, ready for final review

#10465 fix(inputs.opcua): add more data to error log
  plugins/inputs/opcua/opcua_client.go
  plugins/inputs/opcua/opcua_client_test.go
Labels: fix

#10611 chore: update CI go to 1.17.6
  .circleci/config.yml
  Makefile
  scripts/ci-1.17.docker
  scripts/installgo_mac.sh
  scripts/installgo_windows.sh
Labels: chore

#10614 chore: allow downgrade of go version in windows script
  scripts/installgo_windows.sh
Labels: chore

#10612 docs: update quay docs for auth
  docs/developers/PACKAGING.md
Labels: docs

#10625 feat(mongodb): add FsTotalSize and FsUsedSize informations
  plugins/inputs/mongodb/README.md
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongostat.go
Labels: feat, ready for final review

#10497 fix: Improve parser tests by using go-cmp/cmp
  config/config_test.go
Labels: fix, ready for final review

#6501 feat(win_perf_counters): Added support for reading raw values
  plugins/inputs/win_perf_counters/README.md
  plugins/inputs/win_perf_counters/pdh.go
  plugins/inputs/win_perf_counters/pdh_386.go
  plugins/inputs/win_perf_counters/pdh_amd64.go
  plugins/inputs/win_perf_counters/performance_query.go
  plugins/inputs/win_perf_counters/win_perf_counters.go
  plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
Labels: feat, area/windows, ready for final review

#10630 fix: license doc outdated causing CI failure
  docs/LICENSE_OF_DEPENDENCIES.md
Labels: fix

#10629 chore: add -race flag to go tests
  .circleci/config.yml
Labels: ready for final review, chore

#10648 fix: Revert deprecation of http_listener_v2
  plugins/inputs/deprecations.go
Labels: fix

#10641 feat(inputs/memcached): Additional stats from memcached 1.6.14
  plugins/inputs/memcached/README.md
  plugins/inputs/memcached/memcached.go
  plugins/inputs/memcached/memcached_test.go
Labels: feat, ready for final review

#10657 fix: timestamp change during execution of json_v2 parser.
  plugins/parsers/json_v2/parser.go
Labels: fix, ready for final review

#10635 fix: check for nil client before closing
  plugins/outputs/amqp/amqp.go
Labels: fix

#10545 feat: Collection offset implementation
  agent/agent.go
  agent/tick.go
  agent/tick_test.go
  config/config.go
  docs/CONFIGURATION.md
  models/running_input.go
Labels: feat, area/agent, ready for final review

#10586 docs: override reported OpenSearch version
  plugins/outputs/elasticsearch/README.md
Labels: area/elasticsearch, fix, ready for final review, plugin/output

#8192 feat: add socks5 proxy support to kafka
  go.mod
  go.sum
  plugins/common/proxy/socks5.go
  plugins/common/proxy/socks5_test.go
  plugins/outputs/kafka/README.md
  plugins/outputs/kafka/kafka.go
Labels: feat, area/kafka, ready for final review

#10547 fix(prometheusremotewrite): use wrong timestamp unit
  plugins/serializers/prometheusremotewrite/prometheusremotewrite.go
Labels: area/prometheus, fix, ready for final review, plugin/serializer

#10663 docs: update VMWare doc links
  plugins/inputs/vsphere/METRICS.md
Labels: docs

#10551 fix: ensure folders do not get loaded more than once
  internal/snmp/testdata/loadMibsFromPath/linkTarget/emptyFile
  internal/snmp/testdata/loadMibsFromPath/root/dirOne/dirTwo/empty
  internal/snmp/testdata/loadMibsFromPath/root/symlink
  internal/snmp/translate.go
  internal/snmp/translate_test.go
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
  plugins/inputs/snmp_trap/snmp_trap.go
Labels: area/snmp, fix

#10686 chore: Update gosmi
  go.mod
  go.sum
Labels: area/snmp, dependencies, chore

#10689 fix: Linter fixes for "import-shadowing: The name '...' shadows an import name"
  agent/accumulator.go
  agent/agent.go
  internal/http.go
  logger/logger.go
  logger/logger_test.go
  models/log.go
  models/running_aggregator.go
  plugins/common/shim/example/cmd/main.go
  testutil/metric.go
  testutil/tls.go
Labels: fix, ready for final review

#10684 fix(dedup): Modifying slice while iterating is dangerous
  plugins/processors/dedup/dedup.go
  plugins/processors/dedup/dedup_test.go
Labels: fix, ready for final review, plugin/processor

#10623 fix(outputs.groundwork): Set NextCheckTime to LastCheckTime
  plugins/outputs/groundwork/groundwork.go
Labels: fix, ready for final review, plugin/output

#10705 fix: openweathermap add feels_like field
  plugins/inputs/openweathermap/README.md
  plugins/inputs/openweathermap/openweathermap.go
  plugins/inputs/openweathermap/openweathermap_test.go
Labels: fix, ready for final review

#10706 fix: include influxdb bucket name in error messages
  plugins/outputs/influxdb_v2/http.go
Labels: fix

#10681 fix: error msg for missing env variables in config
  config/config.go
  config/config_test.go
Labels: fix, ready for final review

#10672 feat: socks5 proxy support for websocket
  plugins/outputs/websocket/README.md
  plugins/outputs/websocket/websocket.go
Labels: feat, ready for final review

#10642 feat(inputs/memcached): Support client TLS origination to memcached
  plugins/inputs/memcached/README.md
  plugins/inputs/memcached/memcached.go
Labels: feat, ready for final review, plugin/input

#10604 feat: Bump github.com/aerospike/aerospike-client-go from 1.27.0 to 5.7.0
  go.mod
  go.sum
  plugins/inputs/aerospike/README.md
  plugins/inputs/aerospike/aerospike.go
  plugins/inputs/aerospike/aerospike_test.go
Labels: fix, ready for final review

#10527 fix: Remove verbose logging from disk input plugin
  plugins/inputs/system/ps.go
Labels: fix, area/system, ready for final review

#10701 fix: mdstat when sync is less than 10%
  plugins/inputs/mdstat/mdstat.go
  plugins/inputs/mdstat/mdstat_test.go
Labels: ready for final review

#10710 fix: Linter fixes for config/config.go
  .golangci.yml
  config/config.go
Labels: fix, ready for final review

#10727 fix: Revert "fix: error msg for missing env variables in config (#10681)"
  config/config.go
  config/config_test.go
  config/testdata/single_plugin_env_vars.toml
Labels: fix, area/configuration

#10083 feat(parsers/csv): Add metadata support to CSV parser plugin
  plugins/inputs/http/http_test.go
  plugins/parsers/csv/README.md
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
  plugins/parsers/registry.go
Labels: feat, ready for final review, plugin/parser, area/csv

#10515 fix: Histogram Aggregator break metric expiration inside Prometheus client output
  plugins/aggregators/histogram/README.md
  plugins/aggregators/histogram/histogram.go
  plugins/aggregators/histogram/histogram_test.go
Labels: fix, ready for final review, plugin/aggregator

#10585 feat: Add tag batch-processing to XPath parser
  config/config.go
  plugins/parsers/xpath/README.md
  plugins/parsers/xpath/parser.go
  plugins/parsers/xpath/parser_test.go
  plugins/parsers/xpath/testcases/field_tag_batch.conf
  plugins/parsers/xpath/testcases/field_tag_batch.json
Labels: feat, ready for final review, plugin/parser

#10742 fix: typo metadata support to csv parser
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
Labels: fix, plugin/parser, area/csv

#10735 fix: log err when loading mibs
  internal/snmp/translate.go
Labels: area/snmp, fix
