Repository influxdata/telegraf, pull requests merged in 2022-05, with the labels that each got.

#10948 style(inputs/disk): Add deprecation notice to legacy mountpoints setting
  plugins/inputs/disk/disk.go
Labels: area/system, area/configuration, ready for final review, style

#11042 fix: have telegraf service wait for network up
  scripts/telegraf.service
Labels: fix

#11037 feat: add influx semantic commits checker, checks only last commit.
  .github/workflows/semantic.yml
Labels: feat, ready for final review

#11030 fix: re-init azure monitor http client on context deadline error
  plugins/outputs/azure_monitor/azure_monitor.go
Labels: fix

#11043 fix: do not error when closing statsd network connection
  plugins/inputs/statsd/statsd.go
Labels: fix

#11044 fix: deprecate useless database config option
  plugins/inputs/http/http.go
  plugins/inputs/postgresql_extensible/README.md
  plugins/inputs/postgresql_extensible/postgresql_extensible.go
Labels: fix

#11045 fix(inputs.couchbase): Don't assume metrics will all be of the same length
  plugins/inputs/couchbase/couchbase.go
Labels: fix, ready for final review

#11049 feat(exec, execd): add an option to pass a custom environment to their child process
  internal/process/process.go
  internal/process/process_test.go
  plugins/inputs/exec/README.md
  plugins/inputs/exec/exec.go
  plugins/inputs/exec/exec_test.go
  plugins/inputs/execd/README.md
  plugins/inputs/execd/execd.go
  plugins/inputs/execd/execd_test.go
  plugins/outputs/exec/README.md
  plugins/outputs/exec/exec.go
  plugins/outputs/execd/README.md
  plugins/outputs/execd/execd.go
  plugins/outputs/execd/execd_test.go
  plugins/processors/execd/README.md
  plugins/processors/execd/execd.go
  plugins/processors/execd/execd_test.go
Labels: feat, ready for final review

#11080 docs: correct copy-and-paste of udp to tcp in comment
  plugins/inputs/statsd/statsd.go
Labels: docs

#11085 chore: update opentelemetry plugins
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
Labels: area/opentelemetry, ready for final review, dependencies, chore

#10574 feat(inputs.vsphere): Collect resource pools metrics and add resource pool tag in VM metrics
  plugins/inputs/vsphere/METRICS.md
  plugins/inputs/vsphere/README.md
  plugins/inputs/vsphere/endpoint.go
  plugins/inputs/vsphere/finder.go
  plugins/inputs/vsphere/vsphere.go
  plugins/inputs/vsphere/vsphere_test.go
Labels: feat, ready for final review

#11039 feat: add mount option filtering to disk plugin
  plugins/inputs/disk/README.md
  plugins/inputs/disk/disk.go
  plugins/inputs/disk/disk_test.go
  plugins/inputs/system/mock_PS.go
  plugins/inputs/system/ps.go
Labels: feat, ready for final review

#11069 fix: Output erroneous namespace and continue instead of error out
  plugins/inputs/cloudwatch/cloudwatch.go
Labels: fix, cloud, ready for final review, plugin/input

#11093 fix: check net.Listen() error in tests
  plugins/inputs/fluentd/fluentd_test.go
  plugins/inputs/logstash/logstash_test.go
  plugins/inputs/net_response/net_response_test.go
  plugins/inputs/snmp/snmp_test.go
  plugins/outputs/graphite/graphite_test.go
  plugins/outputs/instrumental/instrumental_test.go
Labels: fix, ready for final review

#11101 docs: socket_writer format link
  plugins/outputs/socket_writer/README.md
Labels: docs, fix, ready for final review

#10918 feat: Artifactory Webhook Receiver
  plugins/inputs/webhooks/README.md
  plugins/inputs/webhooks/artifactory/README.md
  plugins/inputs/webhooks/artifactory/artifactory_webhook.go
  plugins/inputs/webhooks/artifactory/artifactory_webhook_mock_json.go
  plugins/inputs/webhooks/artifactory/artifactory_webhook_models.go
  plugins/inputs/webhooks/artifactory/artifactory_webhook_test.go
  plugins/inputs/webhooks/webhooks.go
  plugins/inputs/webhooks/webhooks_test.go
Labels: feat, ready for final review

#10987 test: add test for mysql gatherGlobalVariables using sql-mock
  CHANGELOG.md
  go.mod
  go.sum
  plugins/inputs/mysql/mysql.go
  plugins/inputs/mysql/mysql_test.go
  plugins/inputs/mysql/v2/convert.go
  plugins/inputs/mysql/v2/convert_test.go
  plugins/outputs/azure_monitor/README.md
Labels: ready for final review, test

#11104 chore(inputs/file): More clear error messages
  plugins/inputs/file/file.go
Labels: chore

#10995 fix: log instance name in skip warnings
  plugins/inputs/win_perf_counters/win_perf_counters.go
Labels: platform/windows, area/windows, fix, ready for final review

#11060 feat(parsers/logfmt): Add tag support
  plugins/parsers/logfmt/README.md
  plugins/parsers/logfmt/parser.go
  plugins/parsers/logfmt/parser_test.go
  plugins/parsers/registry.go
Labels: feat, plugin/parser

#11056 feat: allow other fluentd metrics apart from retry_count, buffer_queu…
  plugins/inputs/fluentd/README.md
  plugins/inputs/fluentd/fluentd.go
  plugins/inputs/fluentd/fluentd_test.go
Labels: feat

#11062 fix(parsers/nagios): metrics will always return a supported status co…
  plugins/inputs/exec/exec.go
  plugins/parsers/nagios/parser.go
  plugins/parsers/nagios/parser_test.go
Labels: fix, ready for final review

#11118 test: remove unused riemann from docker-compose
  docker-compose.yml
  plugins/outputs/riemann_legacy/riemann_legacy_test.go
Labels: test

#11120 fix: elasticsearch output float handling test
  plugins/outputs/elasticsearch/elasticsearch_test.go
Labels: fix

#11115 test: remove unecessary flag in sql input
  plugins/inputs/sql/sql_test.go
  plugins/outputs/sql/sql_test.go
Labels: test

#11125 chore(processors): migrate sample configs into separate files
  plugins/processors/aws/ec2/sample.conf
  plugins/processors/clone/sample.conf
  plugins/processors/converter/sample.conf
  plugins/processors/date/sample.conf
  plugins/processors/dedup/sample.conf
  plugins/processors/defaults/sample.conf
  plugins/processors/enum/sample.conf
  plugins/processors/execd/sample.conf
  plugins/processors/filepath/sample.conf
  plugins/processors/ifname/sample.conf
  plugins/processors/noise/sample.conf
  plugins/processors/override/sample.conf
  plugins/processors/parser/sample.conf
  plugins/processors/pivot/sample.conf
  plugins/processors/port_name/sample.conf
  plugins/processors/printer/sample.conf
  plugins/processors/regex/sample.conf
  plugins/processors/rename/sample.conf
  plugins/processors/reverse_dns/sample.conf
  plugins/processors/s2geo/sample.conf
  plugins/processors/starlark/sample.conf
  plugins/processors/strings/sample.conf
  plugins/processors/tag_limit/sample.conf
  plugins/processors/template/sample.conf
  plugins/processors/topk/sample.conf
  plugins/processors/unpivot/sample.conf
Labels: ready for final review, chore

#11130 chore(aggregators): migrate sample configs into separate files
  plugins/aggregators/basicstats/sample.conf
  plugins/aggregators/derivative/sample.conf
  plugins/aggregators/final/sample.conf
  plugins/aggregators/histogram/sample.conf
  plugins/aggregators/merge/sample.conf
  plugins/aggregators/minmax/sample.conf
  plugins/aggregators/quantile/sample.conf
  plugins/aggregators/starlark/sample.conf
  plugins/aggregators/valuecounter/sample.conf
Labels: ready for final review, chore

#11131 chore(outputs): migrate sample configs into separate files
  plugins/outputs/amon/sample.conf
  plugins/outputs/amqp/sample.conf
  plugins/outputs/application_insights/sample.conf
  plugins/outputs/azure_data_explorer/sample.conf
  plugins/outputs/azure_monitor/sample.conf
  plugins/outputs/bigquery/sample.conf
  plugins/outputs/cloud_pubsub/sample.conf
  plugins/outputs/cloudwatch/sample.conf
  plugins/outputs/cloudwatch_logs/sample.conf
  plugins/outputs/cratedb/sample.conf
  plugins/outputs/datadog/sample.conf
  plugins/outputs/discard/sample.conf
  plugins/outputs/dynatrace/sample.conf
  plugins/outputs/elasticsearch/sample.conf
  plugins/outputs/event_hubs/sample.conf
  plugins/outputs/exec/sample.conf
  plugins/outputs/execd/sample.conf
  plugins/outputs/file/sample.conf
  plugins/outputs/graphite/sample.conf
  plugins/outputs/graylog/sample.conf
  plugins/outputs/groundwork/sample.conf
  plugins/outputs/health/sample.conf
  plugins/outputs/http/sample.conf
  plugins/outputs/influxdb/sample.conf
  plugins/outputs/influxdb_v2/sample.conf
  plugins/outputs/instrumental/sample.conf
  plugins/outputs/kafka/sample.conf
  plugins/outputs/kinesis/sample.conf
  plugins/outputs/librato/sample.conf
  plugins/outputs/logzio/sample.conf
  plugins/outputs/loki/sample.conf
  plugins/outputs/mongodb/sample.conf
  plugins/outputs/mqtt/sample.conf
  plugins/outputs/nats/sample.conf
  plugins/outputs/newrelic/sample.conf
  plugins/outputs/nsq/sample.conf
  plugins/outputs/opentelemetry/sample.conf
  plugins/outputs/opentsdb/sample.conf
  plugins/outputs/prometheus_client/sample.conf
  plugins/outputs/riemann/sample.conf
  plugins/outputs/riemann_legacy/sample.conf
  plugins/outputs/sensu/sample.conf
  plugins/outputs/signalfx/sample.conf
  plugins/outputs/socket_writer/sample.conf
  plugins/outputs/sql/sample.conf
  plugins/outputs/stackdriver/sample.conf
  plugins/outputs/sumologic/sample.conf
  plugins/outputs/syslog/sample.conf
  plugins/outputs/timestream/sample.conf
  plugins/outputs/warp10/sample.conf
  plugins/outputs/wavefront/sample.conf
  plugins/outputs/websocket/sample.conf
  plugins/outputs/yandex_cloud_monitoring/sample.conf
Labels: ready for final review, chore

#11083 fix: use readers over closers in http input
  plugins/inputs/http/http.go
  plugins/inputs/http/http_test.go
Labels: fix, ready for final review, plugin/input

#11075 feat: add slab metrics input plugin
  etc/telegraf.conf
  plugins/inputs/all/all.go
  plugins/inputs/slab/README.md
  plugins/inputs/slab/slab.go
  plugins/inputs/slab/slab_notlinux.go
  plugins/inputs/slab/slab_sample_config.go
  plugins/inputs/slab/slab_test.go
Labels: feat, ready for final review

#6948 feat: [inputs/burrow] fill more http transport parameters
  plugins/inputs/burrow/burrow.go
Labels: feat, ready for final review, plugin/input

#11140 fix: avoid calling sadc with invalid 0 interval
  plugins/inputs/sysstat/sysstat.go
Labels: fix, ready for final review

#11149 fix(inputs.burrow): Move Dialer to variable and run `make fmt`
  plugins/inputs/burrow/burrow.go
Labels: fix, ready for final review

#11150 fix: doc interval setting for internet speed plugin
  plugins/inputs/internet_speed/README.md
  plugins/inputs/internet_speed/sample.conf
Labels: fix

#11146 test: switch internet speed to enable file download
  plugins/inputs/internet_speed/internet_speed_test.go
Labels: test

#11137 test: update mongodb output to use test containers
  plugins/inputs/x509_cert/x509_cert_test.go
  plugins/outputs/mongodb/dev/Dockerfile
  plugins/outputs/mongodb/dev/mongodb.sh
  plugins/outputs/mongodb/mongodb_test.go
  plugins/outputs/mongodb/testdata/auth_scram/setup.js
  plugins/outputs/mongodb/testdata/auth_x509/setup.js
  testutil/pki/cacert.pem
  testutil/pki/cakey.pem
  testutil/pki/client.pem
  testutil/pki/clientcert.pem
  testutil/pki/clientenc.pem
  testutil/pki/clientenckey.pem
  testutil/pki/clientkey.pem
  testutil/pki/server.pem
  testutil/pki/servercert.pem
  testutil/pki/serverkey.pem
  testutil/pki/tls-certs.sh
Labels: ready for final review

#11153 test: force elasticsearch to index batch data
  plugins/inputs/elasticsearch_query/elasticsearch_query_test.go
Labels: ready for final review, test

#11147 docs: Update review docs
  docs/developers/REVIEWS.md
Labels: docs, ready for final review

#11151 fix: Improve slab testing without sudo.
  plugins/inputs/slab/slab.go
  plugins/inputs/slab/slab_test.go
  plugins/inputs/slab/testdata/slabinfo
Labels: fix

#11159 feat: Add huebridge plugin
  EXTERNAL_PLUGINS.md
Labels: feat

#11157 test: add generic test-container code for re-use, migrate mysql
  docker-compose.yml
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  plugins/inputs/mysql/mysql_test.go
  testutil/container.go
  testutil/container_test.go
Labels: test

#11144 fix: avoid data race in tcp-listener test.
  plugins/inputs/tcp_listener/tcp_listener_test.go
Labels: fix, area/network, ready for final review, test

#11035 feat(intel_powerstat): Add Max Turbo Frequency and introduce improvements
  plugins/inputs/intel_powerstat/README.md
  plugins/inputs/intel_powerstat/dto.go
  plugins/inputs/intel_powerstat/file.go
  plugins/inputs/intel_powerstat/file_mock_test.go
  plugins/inputs/intel_powerstat/intel_powerstat.go
  plugins/inputs/intel_powerstat/intel_powerstat_test.go
  plugins/inputs/intel_powerstat/msr.go
  plugins/inputs/intel_powerstat/msr_mock_test.go
  plugins/inputs/intel_powerstat/msr_test.go
  plugins/inputs/intel_powerstat/rapl.go
  plugins/inputs/intel_powerstat/rapl_mock_test.go
Labels: feat, ready for final review

#11020 chore: add readme linter to CI
  .github/workflows/readme-linter.yml
  tools/readme_linter/assert.go
  tools/readme_linter/main.go
Labels: ready for final review, chore

#11141 feat(inputs/cpu): add tags with core id or physical id to cpus
  plugins/inputs/cpu/README.md
  plugins/inputs/cpu/cpu.go
Labels: feat, area/system, ready for final review, plugin/input

#11170 test: move nats to test-containers
  docker-compose.yml
  plugins/outputs/nats/nats_test.go
Labels: feat, ready for final review, test

#11172 test: migrate mqtt to test containers
  docker-compose.yml
  plugins/outputs/mqtt/mqtt_test.go
Labels: feat, area/mqtt, ready for final review, test

#11174 test: move redis to test-containers
  docker-compose.yml
  plugins/inputs/redis/redis_test.go
  plugins/inputs/redis_sentinel/redis_sentinel_test.go
Labels: feat, area/redis, ready for final review, test

#11176 test: migrate memcached to test-containers
  docker-compose.yml
  plugins/inputs/memcached/memcached_test.go
Labels: feat, ready for final review, test

#11181 fix: Convert slab plugin to new sample.conf.
  plugins/inputs/slab/README.md
  plugins/inputs/slab/sample.conf
  plugins/inputs/slab/slab.go
  plugins/inputs/slab/slab_sample_config.go
Labels: fix

#11177 test: migrate aerospike to test-containers
  docker-compose.yml
  plugins/inputs/aerospike/aerospike_test.go
Labels: feat, area/aerospike, ready for final review, test

#11076 feat: add field key option to set event partition key
  plugins/outputs/event_hubs/README.md
  plugins/outputs/event_hubs/event_hubs.go
Labels: feat, ready for final review

#11171 test: move opcua to test-containers
  docker-compose.yml
  plugins/inputs/opcua/opcua_test.go
Labels: feat, area/opcua, ready for final review, test

#11173 test: migrate nsq to test containers
  docker-compose.yml
  plugins/outputs/nsq/nsq_test.go
  testutil/container.go
Labels: feat, ready for final review, test

#11084 feat: Google API Auth
  plugins/common/http/config.go
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
  plugins/outputs/http/http_test.go
Labels: feat, ready for final review

#11190 chore: Embed sample configurations into README for aggregators
  Makefile
  docs/AGGREGATORS.md
  docs/INPUTS.md
  docs/OUTPUTS.md
  docs/PROCESSORS.md
  plugins/aggregators/basicstats/README.md
  plugins/aggregators/basicstats/basicstats.go
  plugins/aggregators/basicstats/basicstats_sample_config.go
  plugins/aggregators/derivative/README.md
  plugins/aggregators/derivative/derivative.go
  plugins/aggregators/derivative/derivative_sample_config.go
  plugins/aggregators/final/README.md
  plugins/aggregators/final/final.go
  plugins/aggregators/final/final_sample_config.go
  plugins/aggregators/histogram/README.md
  plugins/aggregators/histogram/histogram.go
  plugins/aggregators/histogram/histogram_sample_config.go
  plugins/aggregators/merge/README.md
  plugins/aggregators/merge/merge.go
  plugins/aggregators/merge/merge_sample_config.go
  plugins/aggregators/minmax/README.md
  plugins/aggregators/minmax/minmax.go
  plugins/aggregators/minmax/minmax_sample_config.go
  plugins/aggregators/quantile/README.md
  plugins/aggregators/quantile/quantile.go
  plugins/aggregators/quantile/quantile_sample_config.go
  plugins/aggregators/starlark/README.md
  plugins/aggregators/starlark/starlark.go
  plugins/aggregators/starlark/starlark_sample_config.go
  plugins/aggregators/valuecounter/README.md
  plugins/aggregators/valuecounter/valuecounter.go
  plugins/aggregators/valuecounter/valuecounter_sample_config.go
  tools/generate_plugindata/main.go
  tools/generate_plugindata/main_test.go
Labels: chore

#11191 fix: Bump golangci-lint from 1.45.2 to 1.46.2
  .github/workflows/golangci-lint.yml
  Makefile
Labels: fix, dependencies

#11143 fix: redis plugin goroutine leak triggered by auto reload config mech…
  plugins/inputs/redis/redis.go
  plugins/inputs/redis/redis_test.go
Labels: area/redis, fix, ready for final review

#11188 feat: Add constant 'algorithm' to the mock plugin
  plugins/inputs/mock/README.md
  plugins/inputs/mock/mock.go
  plugins/inputs/mock/mock_test.go
  plugins/inputs/mock/sample.conf
Labels: feat, ready for final review

#11158 docs: remove recommendation for prometheus metric_version=2
  plugins/inputs/prometheus/README.md
  plugins/outputs/prometheus_client/README.md
Labels: docs, area/prometheus, ready for final review

#11194 chore: update OpenTelmetry plugins
  go.mod
  go.sum
  plugins/inputs/opentelemetry/opentelemetry.go
  plugins/outputs/opentelemetry/opentelemetry.go
Labels: ready for final review, chore

#11199 test: actually skip flaky snmp test
  plugins/inputs/snmp/snmp_test.go
Labels: test

#11198 test: refactor testcontainer port lookup
  plugins/inputs/aerospike/aerospike_test.go
  plugins/inputs/memcached/memcached_test.go
  plugins/inputs/mysql/mysql_test.go
  plugins/inputs/opcua/opcua_test.go
  plugins/inputs/openldap/openldap_test.go
  plugins/inputs/pgbouncer/pgbouncer_test.go
  plugins/inputs/redis/redis_test.go
  plugins/inputs/redis_sentinel/redis_sentinel_test.go
  plugins/inputs/zookeeper/zookeeper_test.go
  plugins/outputs/cratedb/cratedb_test.go
  plugins/outputs/mqtt/mqtt_test.go
  plugins/outputs/nats/nats_test.go
  plugins/outputs/nsq/nsq_test.go
  testutil/container.go
  testutil/container_test.go
Labels: ready for final review, test

#11197 fix(inputs/snmp): switch new Reconnect method to be a value receiver
  internal/snmp/wrapper.go
  plugins/inputs/snmp/snmp.go
  plugins/inputs/snmp/snmp_test.go
  plugins/processors/ifname/ifname.go
  plugins/processors/ifname/ifname_test.go
Labels: fix

#11213 chore: update gopkg.in/yaml.v3 from v3.0.0 to v3.0.1
  go.mod
  go.sum
Labels: ready for final review, chore
