Repository influxdata/telegraf, pull requests merged in 2022-01, with the labels that each got.

#10373 chore: document deprecation of timeout
  plugins/inputs/snmp_trap/README.md
  plugins/inputs/snmp_trap/snmp_trap.go
Labels: area/snmp, chore

#10377 fix: empty import tzdata for Windows binaries
  plugins/parsers/csv/parser.go
Labels: fix

#10378 chore: sql readme with more details on data types
  plugins/outputs/sql/README.md
  plugins/outputs/sql/sql.go
Labels: chore

#10361 fix: multiple typos throughout project
  accumulator.go
  internal/choice/choice.go
  internal/globpath/globpath.go
  internal/internal.go
  metric/tracking.go
  models/buffer.go
  models/makemetric.go
  models/running_processor.go
  plugins/common/encoding/decoder_reader.go
  plugins/inputs/mysql/mysql.go
  plugins/parsers/registry.go
  plugins/serializers/json/json.go
  plugins/serializers/registry.go
Labels: fix, new plugin, plugin/parser, plugin/serializer

#10340 feat: add systemd notify support
  cmd/telegraf/telegraf.go
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  scripts/telegraf.service
Labels: feat, ready for final review

#10382 feat: update docker client API version
  go.mod
  go.sum
  plugins/inputs/docker/client.go
Labels: fix

#10360 fix(outputs/amqp): Close the last connection when writing error to avoid connection leaks
  plugins/outputs/amqp/amqp.go
Labels: fix, ready for final review

#10137 feat: Add additional stats to bond collector
  plugins/inputs/bond/README.md
  plugins/inputs/bond/bond.go
  plugins/inputs/bond/bond_test.go
Labels: feat, area/network, ready for final review, plugin/input

#8947 fix: Fix batching logic with write records, introduce concurrent requests
  plugins/outputs/timestream/timestream.go
  plugins/outputs/timestream/timestream_test.go
Labels: fix, area/aws, ready for final review

#10385 fix: Reenable OpenBSD modbus support
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/inputs/modbus/configuration.go
  plugins/inputs/modbus/configuration_register.go
  plugins/inputs/modbus/configuration_request.go
  plugins/inputs/modbus/modbus.go
  plugins/inputs/modbus/modbus_openbsd.go
  plugins/inputs/modbus/modbus_test.go
  plugins/inputs/modbus/request.go
  plugins/inputs/modbus/type_conversions.go
  plugins/inputs/modbus/type_conversions16.go
  plugins/inputs/modbus/type_conversions32.go
  plugins/inputs/modbus/type_conversions64.go
Labels: area/modbus, ready for final review, plugin/input

#10402 fix: update github.com/containerd/containerd from v1.5.7 to v1.5.9
  go.mod
  go.sum
Labels: fix

#10339 feat: deprecate unused snmp_trap timeout configuration option
  plugins/inputs/snmp_trap/snmp_trap.go
Labels: feat, area/snmp, ready for final review, plugin/input

#10413 fix(json_v2): use raw values for timestamps
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/parser_test.go
  plugins/parsers/json_v2/testdata/timestamp_ns/expected.out
  plugins/parsers/json_v2/testdata/timestamp_ns/input.json
  plugins/parsers/json_v2/testdata/timestamp_ns/telegraf.conf
Labels: fix, ready for final review

#10399 feat: add bearer token support to elasticsearch output
  go.mod
  go.sum
  plugins/outputs/elasticsearch/README.md
  plugins/outputs/elasticsearch/elasticsearch.go
  plugins/outputs/elasticsearch/elasticsearch_test.go
Labels: feat, ready for final review

#10396 fix: send actual empty http body when no body is set
  plugins/inputs/http/http.go
  plugins/inputs/http/http_test.go
Labels: fix, ready for final review

#10423 chore: go mod tidy
  go.sum
Labels: chore

#10393 fix: correctly set ASCII trailer for syslog output
  plugins/outputs/syslog/syslog.go
  plugins/outputs/syslog/syslog_test.go
Labels: fix, area/syslog, ready for final review

#10354 fix: snmp input plugin errors if mibs folder doesn't exist (#10346)
  internal/snmp/translate.go
  plugins/inputs/snmp/snmp_test.go
Labels: fix, ready for final review

#10404 feat: support headers for http plugin with cookie auth
  plugins/common/cookie/cookie.go
  plugins/common/cookie/cookie_test.go
  plugins/inputs/http/README.md
  plugins/inputs/http/http.go
  plugins/outputs/http/README.md
  plugins/outputs/http/http.go
Labels: feat, ready for final review

#10384 fix: Accept non-standard OPC UA OK status by implementing a configurable workaround
  plugins/inputs/opcua/README.md
  plugins/inputs/opcua/opcua_client.go
  plugins/inputs/opcua/opcua_client_test.go
Labels: fix, area/opcua, ready for final review

#10057 feat: Add noise plugin
  docs/LICENSE_OF_DEPENDENCIES.md
  go.mod
  go.sum
  plugins/processors/all/all.go
  plugins/processors/noise/README.md
  plugins/processors/noise/noise.go
  plugins/processors/noise/noise_test.go
Labels: new plugin, ready for final review, plugin/processor

#8791 feat: Parser plugin restructuring
  agent/agent.go
  cmd/telegraf/telegraf.go
  config/config.go
  config/config_test.go
  config/testdata/addressbook.proto
  config/testdata/parsers_new.toml
  config/testdata/parsers_old.toml
  models/running_parsers.go
  parser.go
  plugins/inputs/directory_monitor/directory_monitor_test.go
  plugins/inputs/file/file_test.go
  plugins/inputs/mqtt_consumer/mqtt_consumer.go
  plugins/inputs/tail/tail_test.go
  plugins/parsers/all/all.go
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
  plugins/parsers/registry.go
  plugins/parsers/registry_test.go
  plugins/processors/parser/parser.go
Labels: feat, ready for final review, plugin/parser

#10457 fix: ensure CI tests runs against i386
  .circleci/config.yml
  plugins/inputs/phpfpm/phpfpm_test.go
  plugins/processors/noise/noise_test.go
Labels: fix

#10341 feat: check TLSConfig early to catch missing certificates
  config/config.go
  config/config_test.go
  config/testdata/special_types.key
  config/testdata/special_types.pem
  config/testdata/special_types.toml
  config/testdata/wrong_cert_path.toml
Labels: feat, ready for final review

#10326 fix: address flaky tests in cookie_test.go and graylog_test.go
  go.mod
  go.sum
  plugins/common/cookie/cookie_test.go
  plugins/outputs/graylog/graylog_test.go
Labels: fix, ready for final review

#10464 fix: do not save cache on i386 builds
  .circleci/config.yml
Labels: fix

#10463 fix: add newline in execd for prometheus parsing
  plugins/inputs/execd/execd.go
Labels: fix

#10473 fix(persers.nagios): nagios parser now uses real error for logging
  plugins/parsers/nagios/parser.go
  plugins/parsers/nagios/parser_test.go
Labels: ready for final review

#10478 fix: remove duplicate addition of fields
  plugins/inputs/opcua/opcua_client.go
Labels: fix, ready for final review

#10483 Update Enterprise cluster metrics
  plugins/inputs/influxdb/README.md
Labels: ready for final review

#10479 fix: add comment to logparser
  plugins/inputs/logparser/README.md
Labels: fix

#10480 fix: add RFC3164 to RFC5424 translation to docs
  plugins/inputs/syslog/README.md
Labels: fix

#10481 fix: graylog readme to use graylog 3 URLs
  plugins/inputs/graylog/README.md
  plugins/inputs/graylog/graylog.go
Labels: fix

#10498 docs: Fixes for input/sql readme
  plugins/inputs/sql/README.md
Labels: docs

#10501 fix: Update modbus readme
  plugins/inputs/modbus/README.md
Labels: fix

#10474 fix: check for ipset command during init
  plugins/inputs/ipset/ipset.go
Labels: fix

#10441 fix: typo in docs
  plugins/parsers/xpath/README.md
Labels: fix

#10525 chore: update grpc to v1.44.0
  go.mod
  go.sum
Labels: chore

#10487 feat: add FileVersion and icon to Win exe
  .circleci/config.yml
  .gitignore
  Makefile
  assets/tiger.ico
  cmd/telegraf/telegraf_windows.go
  scripts/generate_versioninfo/main.go
Labels: feat, ready for final review

#10529 docs: Update deprecation readme
  config/config.go
  docs/developers/DEPRECATION.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
Labels: docs, ready for final review

#10430 fix: collapsed fields by calling more indepth function
  internal/snmp/testdata/mibs/testmib
  internal/snmp/translate.go
  internal/snmp/translate_test.go
  plugins/inputs/snmp_trap/snmp_trap_test.go
  plugins/inputs/snmp_trap/testdata/test.mib
  plugins/inputs/snmp_trap/testdata/test2
Labels: area/snmp, fix, ready for final review

#9671 feat: Add ClickHouse driver to sql inputs/outputs plugins
  docs/LICENSE_OF_DEPENDENCIES.md
  docs/SQL_DRIVERS_INPUT.md
  go.mod
  go.sum
  plugins/inputs/sql/drivers.go
  plugins/inputs/sql/sql_test.go
  plugins/inputs/sql/testdata/clickhouse/expected.sql
  plugins/outputs/sql/README.md
  plugins/outputs/sql/sql.go
  plugins/outputs/sql/sql_test.go
  plugins/outputs/sql/testdata/clickhouse/expected.txt
  plugins/outputs/sql/testdata/clickhouse/initdb/init.sql
Labels: feat, ready for final review, plugin/input, area/sql

#10491 fix: update docker mem usage to match latest docker CLI
  plugins/inputs/docker/docker_test.go
  plugins/inputs/docker/stats_helpers.go
Labels: fix, ready for final review

#10528 fix: move "Starting Telegraf" log
  cmd/telegraf/telegraf.go
Labels: fix, ready for final review
