Repository influxdata/telegraf, pull requests merged in 2024-09, with the labels that each got.

#15815 fix(logger): Handle trace level for standard log
  logger/stdlog_redirector.go
Labels: fix, area/logging, ready for final review

#15797 test(linters): Enable `testifylint`: `formatter`, `suite-broken-parallel` and `suite-subtest-run`
  .golangci.yml
  plugins/inputs/kube_inventory/client_test.go
  plugins/secretstores/docker/docker_test.go
Labels: ready for final review, test, linter

#15839 chore(linters): Enable `optimize-operands-order` rule for revive
  .golangci.yml
Labels: ready for final review, chore, linter

#15837 chore(inputs.mqtt): Increase log-level to warning if no message is created by parser
  plugins/inputs/mqtt_consumer/mqtt_consumer.go
Labels: area/mqtt, ready for final review, plugin/input, chore

#15835 chore(linters): Enable G405, G406, G506 and G507 rules for gosec
  .golangci.yml
Labels: ready for final review, chore, linter

#15764 feat(inputs.http_listener_v2): Add unix socket mode
  plugins/inputs/http_listener_v2/README.md
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
  plugins/inputs/http_listener_v2/sample.conf
Labels: feat, ready for final review, plugin/input

#15842 chore(deps): Bump github.com/showwin/speedtest-go from 1.7.7 to 1.7.9
  go.mod
  go.sum
Labels: ready for final review, dependencies, chore

#15743 fix(inputs.snmp): Avoid sending a nil to gosmi's GetEnumBitsFormatted
  internal/snmp/translator_gosmi.go
Labels: area/snmp, fix, ready for final review, plugin/input

#15795 feat(processors.aws_ec2): Allow to use instance metadata
  plugins/processors/aws_ec2/README.md
  plugins/processors/aws_ec2/ec2.go
  plugins/processors/aws_ec2/ec2_test.go
  plugins/processors/aws_ec2/sample.conf
Labels: feat, area/aws, ready for final review, plugin/processor

#15791 fix(inputs.mysql): Enforce float for all known floating-point information
  plugins/inputs/mysql/v2/convert.go
Labels: area/mysql, fix, ready for final review, plugin/input

#15844 chore(parser.json_v2): Error out if no config is provided
  CHANGELOG.md
  config/config_test.go
  config/testdata/parsers_new.toml
  config/testdata/processors_with_parsers.toml
  plugins/parsers/json_v2/parser.go
  plugins/parsers/json_v2/parser_test.go
Labels: area/json, ready for final review, plugin/parser, chore

#15834 feat(inputs.execd): Allow to provide logging prefixes on stderr
  plugins/inputs/execd/README.md
  plugins/inputs/execd/execd.go
  plugins/inputs/execd/execd_test.go
  testutil/capturelog.go
Labels: feat, area/logging, area/execd, ready for final review, plugin/input

#15856 chore(deps): Bump golangci-lint from v1.60.3 to v1.61.0
  .circleci/config.yml
  .golangci.yml
  Makefile
Labels: ready for final review, dependencies, chore, linter

#15847 chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/outputs` and `plugins/parsers`
  plugins/outputs/application_insights/application_insights_test.go
  plugins/outputs/application_insights/transmitter.go
  plugins/outputs/azure_data_explorer/azure_data_explorer.go
  plugins/outputs/azure_monitor/azure_monitor.go
  plugins/outputs/cloud_pubsub/cloud_pubsub_test.go
  plugins/outputs/cloudwatch/cloudwatch.go
  plugins/outputs/cratedb/cratedb.go
  plugins/outputs/datadog/datadog.go
  plugins/outputs/exec/exec.go
  plugins/outputs/exec/exec_test.go
  plugins/outputs/graylog/graylog.go
  plugins/outputs/librato/librato.go
  plugins/outputs/mqtt/topic_name_generator.go
  plugins/outputs/parquet/parquet.go
  plugins/outputs/postgresql/sqltemplate/template.go
  plugins/outputs/postgresql/table_manager.go
  plugins/outputs/prometheus_client/v1/collector.go
  plugins/outputs/prometheus_client/v2/collector.go
  plugins/outputs/riemann/riemann.go
  plugins/outputs/signalfx/signalfx.go
  plugins/outputs/stackdriver/stackdriver.go
  plugins/outputs/syslog/syslog_mapper.go
  plugins/outputs/timestream/timestream_test.go
  plugins/outputs/zabbix/autoregister_test.go
  plugins/outputs/zabbix/zabbix_test.go
  plugins/parsers/avro/schema_registry.go
  plugins/parsers/influx/escape.go
  plugins/parsers/influx/handler.go
  plugins/parsers/json/json_flattener.go
Labels: ready for final review, chore, linter

#15867 chore(cmd): Align plugin deprecation messages
  cmd/telegraf/printer.go
Labels: area/agent, ready for final review, chore

#15858 chore: Fix linter findings for `revive:max-public-structs` in `plugins/inputs/[a-n]*`
  plugins/inputs/activemq/activemq.go
  plugins/inputs/activemq/activemq_test.go
  plugins/inputs/ctrlx_datalayer/ctrlx_datalayer.go
  plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_subscription.go
  plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_subscription_test.go
  plugins/inputs/ctrlx_datalayer/ctrlx_datalayer_test.go
  plugins/inputs/dcos/client.go
  plugins/inputs/dcos/client_test.go
  plugins/inputs/dcos/creds.go
  plugins/inputs/dcos/dcos.go
  plugins/inputs/dcos/dcos_test.go
  plugins/inputs/graylog/graylog.go
  plugins/inputs/kafka_consumer/kafka_consumer.go
  plugins/inputs/kubernetes/kubernetes.go
  plugins/inputs/kubernetes/kubernetes_metrics.go
  plugins/inputs/logstash/logstash.go
  plugins/inputs/logstash/logstash_test.go
  plugins/inputs/mailchimp/chimp_api.go
  plugins/inputs/mailchimp/mailchimp.go
  plugins/inputs/mailchimp/mailchimp_test.go
  plugins/inputs/mongodb/mongodb_data.go
  plugins/inputs/mongodb/mongodb_data_test.go
  plugins/inputs/mongodb/mongodb_server.go
  plugins/inputs/mongodb/mongostat.go
  plugins/inputs/mongodb/mongostat_test.go
  plugins/inputs/monit/monit.go
Labels: ready for final review, chore, linter

#15857 chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/inputs/[o-z]*`
  plugins/inputs/openweathermap/openweathermap.go
  plugins/inputs/phpfpm/fcgi.go
  plugins/inputs/phpfpm/fcgi_client.go
  plugins/inputs/phpfpm/phpfpm.go
  plugins/inputs/ping/ping_notwindows.go
  plugins/inputs/proxmox/proxmox.go
  plugins/inputs/proxmox/proxmox_test.go
  plugins/inputs/redis/redis.go
  plugins/inputs/redis_sentinel/redis_sentinel.go
  plugins/inputs/redis_sentinel/redis_sentinel_test.go
  plugins/inputs/sflow/sflow.go
  plugins/inputs/smart/smart.go
  plugins/inputs/smartctl/smartctl_device.go
  plugins/inputs/snmp_trap/snmp_trap_test.go
  plugins/inputs/socketstat/socketstat.go
  plugins/inputs/sqlserver/connectionstring.go
  plugins/inputs/stackdriver/stackdriver.go
  plugins/inputs/statsd/datadog.go
  plugins/inputs/statsd/statsd.go
  plugins/inputs/sysstat/sysstat.go
  plugins/inputs/system/mock_PS.go
  plugins/inputs/system/ps.go
  plugins/inputs/vsphere/client.go
  plugins/inputs/vsphere/endpoint.go
  plugins/inputs/vsphere/tscache.go
  plugins/inputs/vsphere/vsan.go
  plugins/inputs/webhooks/artifactory/artifactory_webhook.go
  plugins/inputs/webhooks/artifactory/artifactory_webhook_test.go
  plugins/inputs/webhooks/github/github_webhooks_test.go
  plugins/inputs/webhooks/papertrail/papertrail_test.go
Labels: ready for final review, chore, linter

#15864 chore(aggregators): Comment out default values in sample configs
  plugins/aggregators/basicstats/README.md
  plugins/aggregators/basicstats/sample.conf
  plugins/aggregators/derivative/README.md
  plugins/aggregators/derivative/sample.conf
  plugins/aggregators/final/README.md
  plugins/aggregators/final/sample.conf
  plugins/aggregators/histogram/README.md
  plugins/aggregators/histogram/sample.conf
  plugins/aggregators/minmax/README.md
  plugins/aggregators/minmax/sample.conf
  plugins/aggregators/quantile/README.md
  plugins/aggregators/quantile/sample.conf
  plugins/aggregators/valuecounter/README.md
  plugins/aggregators/valuecounter/sample.conf
Labels: ready for final review, plugin/aggregator, chore

#15841 chore(linters): Enable `get-return` rule for revive
  .golangci.yml
  config/config.go
  plugins/aggregators/basicstats/basicstats.go
  plugins/aggregators/basicstats/basicstats_test.go
  plugins/inputs/smart/smart.go
Labels: ready for final review, chore, linter

#15865 feat(inputs.prometheus): Allow to use secrets for credentials
  plugins/inputs/prometheus/README.md
  plugins/inputs/prometheus/prometheus.go
Labels: feat, area/prometheus, ready for final review, plugin/input

#15850 chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/inputs/[h-n]*`
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
  plugins/inputs/http_response/http_response_test.go
  plugins/inputs/hugepages/hugepages.go
  plugins/inputs/infiniband/infiniband_linux.go
  plugins/inputs/influxdb_listener/influxdb_listener_test.go
  plugins/inputs/influxdb_v2_listener/influxdb_v2_listener_test.go
  plugins/inputs/intel_pmt/intel_pmt.go
  plugins/inputs/intel_pmt/intel_pmt_test.go
  plugins/inputs/intel_pmt/xml_parser.go
  plugins/inputs/intel_pmu/config.go
  plugins/inputs/intel_pmu/intel_pmu.go
  plugins/inputs/intel_pmu/intel_pmu_test.go
  plugins/inputs/intel_pmu/resolver.go
  plugins/inputs/intel_powerstat/intel_powerstat.go
  plugins/inputs/intel_rdt/intel_rdt.go
  plugins/inputs/ipmi_sensor/ipmi_sensor.go
  plugins/inputs/jenkins/client.go
  plugins/inputs/knx_listener/knx_listener_test.go
  plugins/inputs/kube_inventory/client.go
  plugins/inputs/leofs/leofs_test.go
  plugins/inputs/mcrouter/mcrouter.go
  plugins/inputs/mongodb/mongodb_server.go
  plugins/inputs/mongodb/mongostat.go
  plugins/inputs/mqtt_consumer/topic_parser.go
  plugins/inputs/mysql/mysql.go
  plugins/inputs/nfsclient/nfsclient.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics_test.go
  plugins/inputs/nsd/nsd.go
Labels: ready for final review, chore, linter

#15849 chore: Fix linter findings for `revive:enforce-repeated-arg-type-style` in `plugins/inputs/[a-g]*`
  plugins/inputs/aerospike/aerospike.go
  plugins/inputs/aerospike/aerospike_test.go
  plugins/inputs/aliyuncms/aliyuncms.go
  plugins/inputs/azure_monitor/azure_monitor.go
  plugins/inputs/azure_monitor/azure_monitor_test.go
  plugins/inputs/beanstalkd/beanstalkd_test.go
  plugins/inputs/bond/bond.go
  plugins/inputs/cisco_telemetry_mdt/cisco_telemetry_mdt.go
  plugins/inputs/cloudwatch_metric_streams/cloudwatch_metric_streams_test.go
  plugins/inputs/couchbase/couchbase.go
  plugins/inputs/cpu/cpu_test.go
  plugins/inputs/dcos/client.go
  plugins/inputs/directory_monitor/directory_monitor.go
  plugins/inputs/dns_query/dns_query.go
  plugins/inputs/docker/docker.go
  plugins/inputs/docker/stats_helpers.go
  plugins/inputs/dovecot/dovecot.go
  plugins/inputs/dpdk/dpdk_utils.go
  plugins/inputs/ecs/ecs.go
  plugins/inputs/elasticsearch_query/aggregation_parser.go
  plugins/inputs/elasticsearch_query/aggregation_query.go
  plugins/inputs/exec/exec_test.go
  plugins/inputs/execd/shim/shim_test.go
  plugins/inputs/fibaro/hc2/parser.go
  plugins/inputs/fibaro/hc3/parser.go
  plugins/inputs/filecount/filecount_test.go
  plugins/inputs/github/github.go
  plugins/inputs/gnmi/gnmi.go
  plugins/inputs/google_cloud_storage/google_cloud_storage_test.go
  plugins/inputs/graylog/graylog.go
Labels: ready for final review, chore, linter

#15889 perf(agent): Reduce complexity of creating new metrics to 'O(N_fields)'
  metric/metric.go
Labels: performance, fix, area/agent, ready for final review

#15886 test(testutil): Fix value comparison
  testutil/metric.go
Labels: fix, ready for final review, test

#15878 chore: Fix linter findings for revive:max-public-structs in plugins/inputs/[n-s]*
  plugins/inputs/nginx_plus/nginx_plus.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_metrics.go
  plugins/inputs/nginx_plus_api/nginx_plus_api_types.go
  plugins/inputs/nomad/nomad.go
  plugins/inputs/nomad/nomad_metrics.go
  plugins/inputs/nsq/nsq.go
  plugins/inputs/nvidia_smi/schema_v11/types.go
  plugins/inputs/opensearch_query/aggregation.response.go
  plugins/inputs/opensearch_query/opensearch_query.go
  plugins/inputs/proxmox/proxmox.go
  plugins/inputs/proxmox/structs.go
  plugins/inputs/rabbitmq/rabbitmq.go
  plugins/inputs/redfish/redfish.go
  plugins/inputs/rethinkdb/rethinkdb_data.go
  plugins/inputs/rethinkdb/rethinkdb_data_test.go
  plugins/inputs/sflow/decoder_test.go
  plugins/inputs/sflow/metricencoder.go
  plugins/inputs/sflow/packetdecoder.go
  plugins/inputs/sflow/packetdecoder_test.go
  plugins/inputs/sflow/sflow.go
  plugins/inputs/sflow/types.go
  plugins/inputs/sflow/types_test.go
  plugins/inputs/solr/api.go
  plugins/inputs/solr/solr.go
  plugins/inputs/solr/types.go
  plugins/inputs/stackdriver/stackdriver.go
  plugins/inputs/stackdriver/stackdriver_test.go
Labels: ready for final review, chore, linter

#15879 chore: Fix linter findings for revive:max-public-structs in plugins/inputs/[t-z]* and rest
  plugins/inputs/tomcat/tomcat.go
  plugins/inputs/webhooks/artifactory/artifactory_webhook.go
  plugins/inputs/webhooks/artifactory/artifactory_webhook_models.go
  plugins/inputs/webhooks/github/github_webhooks.go
  plugins/inputs/webhooks/github/github_webhooks_models.go
  plugins/inputs/webhooks/rollbar/rollbar_webhooks.go
  plugins/inputs/webhooks/rollbar/rollbar_webhooks_events.go
  plugins/inputs/win_eventlog/event.go
  plugins/inputs/win_perf_counters/pdh.go
  plugins/inputs/win_perf_counters/pdh_386.go
  plugins/inputs/win_perf_counters/pdh_amd64.go
  plugins/inputs/win_perf_counters/pdh_arm64.go
  plugins/inputs/win_perf_counters/performance_query.go
  plugins/inputs/win_perf_counters/win_perf_counters.go
  plugins/inputs/win_perf_counters/win_perf_counters_integration_test.go
  plugins/inputs/win_perf_counters/win_perf_counters_test.go
  plugins/inputs/win_services/win_services.go
  plugins/inputs/win_services/win_services_integration_test.go
  plugins/inputs/xtremio/xtremio.go
  plugins/inputs/xtremio/xtremio_types.go
  plugins/inputs/zipkin/codec/codec.go
  plugins/inputs/zipkin/codec/codec_test.go
  plugins/outputs/influxdb/http.go
  plugins/outputs/prometheus_client/v1/collector.go
  plugins/outputs/sensu/sensu.go
  plugins/outputs/sensu/sensu_test.go
  plugins/parsers/json_v2/parser.go
  plugins/parsers/wavefront/element.go
  plugins/parsers/wavefront/parser.go
  plugins/serializers/prometheus/collection.go
Labels: ready for final review, chore, linter

#15894 chore: Update go to v1.23.1
  .circleci/config.yml
  .github/workflows/readme-linter.yml
  Makefile
  scripts/ci.docker
  scripts/installgo_linux.sh
  scripts/installgo_mac.sh
  scripts/installgo_windows.sh
Labels: ready for final review, chore, go

#15843 chore(output.kinesis): Log kinesis consumer events
  plugins/inputs/kinesis_consumer/kinesis_consumer.go
Labels: ready for final review, plugin/output, chore

#15895 chore(linters): Enable `max-public-structs` rule for revive
  .golangci.yml
Labels: ready for final review, chore, linter

#15887 chore(linters): Fix findings found by `testifylint`: `go-require` for`instrumental` and parsers/processors
  plugins/outputs/instrumental/instrumental_test.go
  plugins/parsers/influx/influx_upstream/parser_test.go
  plugins/parsers/influx/parser_test.go
  plugins/processors/ifname/ifname_test.go
  plugins/processors/reverse_dns/rdnscache_test.go
Labels: ready for final review, chore, linter

#15896 chore: Fix linter findings for `revive:comment-spacings` (part 1)
  cmd/telegraf/telegraf.go
  config/config_test.go
  config/secret_test.go
  config/types_test.go
  internal/content_coding.go
  internal/globpath/globpath_test.go
  internal/rotate/file_writer.go
  internal/snmp/field.go
  internal/snmp/mib_loader.go
  internal/snmp/table.go
  internal/snmp/table_test.go
  internal/snmp/translator_gosmi_test.go
  internal/snmp/wrapper.go
  logger/event_logger_test.go
  models/running_output_test.go
  plugins/aggregators/basicstats/basicstats.go
  plugins/aggregators/basicstats/basicstats_test.go
  plugins/common/jolokia2/client.go
  plugins/parsers/collectd/parser.go
  plugins/parsers/csv/parser.go
  plugins/parsers/csv/parser_test.go
  plugins/parsers/grok/parser.go
  plugins/parsers/influx/handler.go
  plugins/parsers/logfmt/parser.go
  plugins/parsers/wavefront/element.go
  plugins/processors/ifname/ifname.go
  plugins/processors/topk/topk_test.go
  plugins/serializers/graphite/graphite.go
  tools/readme_linter/assert.go
  tools/readme_linter/rules.go
  tools/update_goversion/main.go
Labels: ready for final review, chore, linter

#15898 chore: Fix linter findings for `revive:comment-spacings` (part 3)
  plugins/outputs/azure_data_explorer/azure_data_explorer.go
  plugins/outputs/cloud_pubsub/cloud_pubsub_test.go
  plugins/outputs/cloudwatch_logs/cloudwatch_logs.go
  plugins/outputs/cloudwatch_logs/cloudwatch_logs_test.go
  plugins/outputs/cratedb/cratedb.go
  plugins/outputs/elasticsearch/elasticsearch.go
  plugins/outputs/graphite/graphite_test.go
  plugins/outputs/influxdb/http.go
  plugins/outputs/iotdb/iotdb_test.go
  plugins/outputs/mongodb/mongodb.go
  plugins/outputs/newrelic/newrelic.go
  plugins/outputs/postgresql/postgresql.go
  plugins/outputs/socket_writer/socket_writer.go
  plugins/outputs/sql/sql.go
  plugins/outputs/sql/sql_test.go
  plugins/outputs/sql/sqlite_test.go
  plugins/outputs/syslog/syslog_mapper.go
  plugins/outputs/timestream/timestream_test.go
Labels: ready for final review, chore, linter

#15900 fix(common.http): Keep timeout after creating oauth client
  plugins/common/http/config.go
Labels: fix, ready for final review

#15890 chore(deps): Bump github.com/harlow/kinesis-consumer from v0.3.6-0.20240606153816-553e2392fdf3 to v0.3.6-0.20240916192723-43900507c911
  go.mod
  go.sum
Labels: ready for final review, dependencies, chore

#15796 fix(inputs.amqp_consumer): NACKing messages on non-delivery related errors
  CHANGELOG.md
  plugins/inputs/amqp_consumer/README.md
  plugins/inputs/amqp_consumer/amqp_consumer.go
Labels: fix, ready for final review, plugin/input

#15914 chore(linters): Enable `comment-spacings` rule for revive
  .golangci.yml
Labels: ready for final review, chore, linter

#15907 fix(inputs.consul): Move config checking to Init method
  plugins/inputs/consul/consul.go
Labels: fix, area/consul, ready for final review, plugin/input

#15872 chore(inputs): Remove deprecated options from sample config
  plugins/inputs/activemq/README.md
  plugins/inputs/activemq/sample.conf
  plugins/inputs/consul/consul.go
  plugins/inputs/docker/README.md
  plugins/inputs/docker/sample.conf
  plugins/inputs/elasticsearch/README.md
  plugins/inputs/elasticsearch/sample.conf
  plugins/inputs/influxdb_listener/README.md
  plugins/inputs/influxdb_listener/sample.conf
  plugins/inputs/kube_inventory/README.md
  plugins/inputs/kube_inventory/sample.conf
  plugins/inputs/modbus/README.md
  plugins/inputs/modbus/configuration_register.go
  plugins/inputs/modbus/sample_register.conf
  plugins/inputs/net/README.md
  plugins/inputs/net/sample.conf
  plugins/inputs/nsq_consumer/README.md
  plugins/inputs/nsq_consumer/nsq_consumer.go
  plugins/inputs/nsq_consumer/nsq_consumer_test.go
  plugins/inputs/nsq_consumer/sample.conf
  plugins/inputs/opcua/README.md
  plugins/inputs/opcua/sample.conf
  plugins/inputs/postgresql_extensible/README.md
  plugins/inputs/postgresql_extensible/sample.conf
  plugins/inputs/rabbitmq/README.md
  plugins/inputs/rabbitmq/sample.conf
  plugins/inputs/sqlserver/README.md
  plugins/inputs/sqlserver/sample.conf
  plugins/inputs/statsd/README.md
  plugins/inputs/statsd/sample.conf
Labels: area/configuration, ready for final review, plugin/input, chore

#15921 fix(parsers.avro): Add mutex to cache access
  plugins/parsers/avro/schema_registry.go
Labels: fix, ready for final review, plugin/parser

#15869 feat(processors.batch): Add batch processor
  plugins/processors/all/batch.go
  plugins/processors/batch/README.md
  plugins/processors/batch/batch.go
  plugins/processors/batch/batch_test.go
  plugins/processors/batch/sample.conf
Labels: feat, new plugin, ready for final review, plugin/processor

#15937 fix(config): Correctly print removal version info
  config/deprecation.go
  config/deprecation_test.go
Labels: fix, area/configuration, ready for final review
