Repository influxdata/telegraf, pull requests merged in 2025-06, with the labels that each got.

#17011 test(testutil): Performance and code quality improvements on metric
  testutil/metric.go
Labels: ready for final review, test

#17101 feat(migrations): Add migration for inputs.cisco_telemetry_gnmi
  migrations/all/inputs_cisco_telemetry_gnmi.go
  migrations/inputs_cisco_telemetry_gnmi/migration.go
  migrations/inputs_cisco_telemetry_gnmi/migration_test.go
  migrations/inputs_cisco_telemetry_gnmi/testcases/deprecated_alias/expected.conf
  migrations/inputs_cisco_telemetry_gnmi/testcases/deprecated_alias/telegraf.conf
  plugins/inputs/gnmi/gnmi.go
Labels: feat, area/configuration, ready for final review

#16950 feat(migrations): Add migration for outputs.amqp
  migrations/all/outputs_amqp.go
  migrations/outputs_amqp/migration.go
  migrations/outputs_amqp/migration_test.go
  migrations/outputs_amqp/testcases/minimal/expected.conf
  migrations/outputs_amqp/testcases/minimal/telegraf.conf
  plugins/outputs/amqp/amqp.go
  plugins/outputs/amqp/amqp_test.go
Labels: feat, area/configuration, ready for final review

#17121 feat(inputs.amqp_consumer): Allow string values in queue arguments
  plugins/inputs/amqp_consumer/amqp_consumer.go
Labels: feat, area/rabbitmq, ready for final review, plugin/input

#17118 fix(migrations): Update table content for general plugin migrations
  config/migration.go
Labels: fix, area/configuration, ready for final review

#17082 docs(inputs): Add plugin metadata and update description for s* to z*
  plugins/inputs/salesforce/README.md
  plugins/inputs/sensors/README.md
  plugins/inputs/sflow/README.md
  plugins/inputs/slab/README.md
  plugins/inputs/slurm/README.md
  plugins/inputs/smart/README.md
  plugins/inputs/smartctl/README.md
  plugins/inputs/snmp/README.md
  plugins/inputs/snmp_trap/README.md
  plugins/inputs/socket_listener/README.md
  plugins/inputs/socketstat/README.md
  plugins/inputs/solr/README.md
  plugins/inputs/sql/README.md
  plugins/inputs/sqlserver/README.md
  plugins/inputs/stackdriver/README.md
  plugins/inputs/statsd/README.md
  plugins/inputs/supervisor/README.md
  plugins/inputs/suricata/README.md
  plugins/inputs/swap/README.md
  plugins/inputs/synproxy/README.md
  plugins/inputs/syslog/README.md
  plugins/inputs/sysstat/README.md
  plugins/inputs/system/README.md
  plugins/inputs/systemd_units/README.md
  plugins/inputs/tacacs/README.md
  plugins/inputs/tail/README.md
  plugins/inputs/teamspeak/README.md
  plugins/inputs/temp/README.md
  plugins/inputs/tengine/README.md
  plugins/inputs/tomcat/README.md
  plugins/inputs/trig/README.md
  plugins/inputs/twemproxy/README.md
  plugins/inputs/unbound/README.md
  plugins/inputs/upsd/README.md
  plugins/inputs/uwsgi/README.md
  plugins/inputs/varnish/README.md
  plugins/inputs/vault/README.md
  plugins/inputs/vsphere/METRICS.md
  plugins/inputs/vsphere/README.md
  plugins/inputs/webhooks/README.md
  plugins/inputs/whois/README.md
  plugins/inputs/win_eventlog/README.md
  plugins/inputs/win_perf_counters/README.md
  plugins/inputs/win_services/README.md
  plugins/inputs/win_wmi/README.md
  plugins/inputs/wireguard/README.md
  plugins/inputs/wireless/README.md
  plugins/inputs/x509_cert/README.md
  plugins/inputs/xtremio/README.md
  plugins/inputs/zfs/README.md
  plugins/inputs/zipkin/README.md
  plugins/inputs/zookeeper/README.md
Labels: docs, ready for final review, plugin/input

#17007 chore(agent): Add "disk_write_through" alias to disk buffer strategy config
  config/config.go
  docs/specs/tsd-005-output-buffer-strategy.md
  models/buffer.go
  models/buffer_disk_test.go
  models/buffer_suite_test.go
  models/running_output.go
Labels: area/aws, ready for final review, chore

#17150 feat(migrations): Add option migration for inputs.consul
  migrations/all/inputs_consul.go
  migrations/inputs_consul/migration.go
  migrations/inputs_consul/migration_test.go
  migrations/inputs_consul/testcases/deprecated_centre_existing/expected.conf
  migrations/inputs_consul/testcases/deprecated_centre_existing/telegraf.conf
  migrations/inputs_consul/testcases/deprecated_datacentre/expected.conf
  migrations/inputs_consul/testcases/deprecated_datacentre/telegraf.conf
  plugins/inputs/consul/consul.go
Labels: feat, area/configuration, ready for final review

#17152 feat(migrations): Add option migration for inputs.filecount
  migrations/all/inputs_filecount.go
  migrations/inputs_filecount/migration.go
  migrations/inputs_filecount/migration_test.go
  migrations/inputs_filecount/testcases/deprecated_directory/expected.conf
  migrations/inputs_filecount/testcases/deprecated_directory/telegraf.conf
  migrations/inputs_filecount/testcases/deprecated_directory_duplicate/expected.conf
  migrations/inputs_filecount/testcases/deprecated_directory_duplicate/telegraf.conf
  migrations/inputs_filecount/testcases/deprecated_directory_existing/expected.conf
  migrations/inputs_filecount/testcases/deprecated_directory_existing/telegraf.conf
  plugins/inputs/filecount/filecount.go
Labels: feat, area/configuration, ready for final review

#17153 feat(migrations): Add option migration for inputs.http
  migrations/all/inputs_http.go
  migrations/inputs_http/migration.go
  migrations/inputs_http/migration_test.go
  migrations/inputs_http/testcases/deprecated_bearer_token/expected.conf
  migrations/inputs_http/testcases/deprecated_bearer_token/telegraf.conf
  migrations/inputs_http/testcases/deprecated_bearer_token_existing/expected.conf
  migrations/inputs_http/testcases/deprecated_bearer_token_existing/telegraf.conf
  plugins/inputs/http/http.go
Labels: feat, area/configuration, ready for final review

#17157 feat(migrations): Add option migration for inputs.http_response
  migrations/all/inputs_http_response.go
  migrations/inputs_http_response/migration.go
  migrations/inputs_http_response/migration_test.go
  migrations/inputs_http_response/testcases/deprecated_address/expected.conf
  migrations/inputs_http_response/testcases/deprecated_address/telegraf.conf
  migrations/inputs_http_response/testcases/deprecated_address_duplicate/expected.conf
  migrations/inputs_http_response/testcases/deprecated_address_duplicate/telegraf.conf
  migrations/inputs_http_response/testcases/deprecated_address_existing/expected.conf
  migrations/inputs_http_response/testcases/deprecated_address_existing/telegraf.conf
  plugins/inputs/http_response/http_response.go
Labels: feat, area/configuration, ready for final review

#17167 feat(migrations): Add option migration for outputs.kinesis
  migrations/all/outputs_kinesis.go
  migrations/outputs_kinesis/migration.go
  migrations/outputs_kinesis/migration_test.go
  migrations/outputs_kinesis/testcases/only_randomkey_set/expected.conf
  migrations/outputs_kinesis/testcases/only_randomkey_set/telegraf.conf
  migrations/outputs_kinesis/testcases/randomkey_not_set/expected.conf
  migrations/outputs_kinesis/testcases/randomkey_not_set/telegraf.conf
  migrations/outputs_kinesis/testcases/randomkey_set/expected.conf
  migrations/outputs_kinesis/testcases/randomkey_set/telegraf.conf
  plugins/outputs/kinesis/kinesis.go
  plugins/outputs/kinesis/kinesis_test.go
Labels: feat, area/configuration, ready for final review

#17165 feat(migrations): Add option migration for inputs.internet_speed
  migrations/all/inputs_internet_speed.go
  migrations/inputs_internet_speed/migration.go
  migrations/inputs_internet_speed/migration_test.go
  migrations/inputs_internet_speed/testcases/deprecated_enable_file_download/expected.conf
  migrations/inputs_internet_speed/testcases/deprecated_enable_file_download/telegraf.conf
  migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_existing/expected.conf
  migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_existing/telegraf.conf
  migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_false/expected.conf
  migrations/inputs_internet_speed/testcases/deprecated_enable_file_download_false/telegraf.conf
  plugins/inputs/internet_speed/internet_speed.go
Labels: feat, area/configuration, ready for final review

#17162 feat(migrations): Add migration for inputs.influxdb_listener
  migrations/all/inputs_influxdb_listener.go
  migrations/inputs_influxdb_listener/migration.go
  migrations/inputs_influxdb_listener/migration_test.go
  migrations/inputs_influxdb_listener/testcases/deprecated_max_line_size/expected.conf
  migrations/inputs_influxdb_listener/testcases/deprecated_max_line_size/telegraf.conf
  plugins/inputs/influxdb_listener/influxdb_listener.go
Labels: feat, area/configuration, ready for final review

#17123 feat(migrations): Add migration for inputs.cloudwatch
  migrations/all/inputs_cloudwatch.go
  migrations/inputs_cloudwatch/migration.go
  migrations/inputs_cloudwatch/migration_test.go
  migrations/inputs_cloudwatch/testcases/multiple_cloudwatch_instances/expected.conf
  migrations/inputs_cloudwatch/testcases/multiple_cloudwatch_instances/telegraf.conf
  migrations/inputs_cloudwatch/testcases/namespace_duplicate_in_namespaces/expected.conf
  migrations/inputs_cloudwatch/testcases/namespace_duplicate_in_namespaces/telegraf.conf
  migrations/inputs_cloudwatch/testcases/namespace_merge_with_namespaces/expected.conf
  migrations/inputs_cloudwatch/testcases/namespace_merge_with_namespaces/telegraf.conf
  migrations/inputs_cloudwatch/testcases/namespace_to_namespaces/expected.conf
  migrations/inputs_cloudwatch/testcases/namespace_to_namespaces/telegraf.conf
  plugins/inputs/cloudwatch/cloudwatch.go
  plugins/inputs/cloudwatch/cloudwatch_test.go
Labels: feat, area/configuration, ready for final review

#17175 chore: Update go to 1.24.4
  .circleci/config.yml
  .github/workflows/readme-linter.yml
  Makefile
  scripts/ci.docker
  scripts/installgo_linux.sh
  scripts/installgo_mac.sh
  scripts/installgo_windows.sh
Labels: ready for final review, chore, go

#17169 feat(migrations): Add option migration for inputs.vsphere
  migrations/all/inputs_vsphere.go
  migrations/inputs_vsphere/migration.go
  migrations/inputs_vsphere/migration_test.go
  migrations/inputs_vsphere/testcases/deprecated_force_discover_on_init/expected.conf
  migrations/inputs_vsphere/testcases/deprecated_force_discover_on_init/telegraf.conf
  plugins/inputs/vsphere/vsphere.go
  plugins/inputs/vsphere/vsphere_test.go
Labels: feat, area/configuration, ready for final review

#17163 feat(migrations): Add option migration for inputs.icinga2
  migrations/all/inputs_icinga2.go
  migrations/inputs_icinga2/migration.go
  migrations/inputs_icinga2/migration_test.go
  migrations/inputs_icinga2/testcases/deprecated_object_type/expected.conf
  migrations/inputs_icinga2/testcases/deprecated_object_type/telegraf.conf
  migrations/inputs_icinga2/testcases/deprecated_object_type_duplicate/expected.conf
  migrations/inputs_icinga2/testcases/deprecated_object_type_duplicate/telegraf.conf
  migrations/inputs_icinga2/testcases/deprecated_object_type_existing/expected.conf
  migrations/inputs_icinga2/testcases/deprecated_object_type_existing/telegraf.conf
  plugins/inputs/icinga2/icinga2.go
  plugins/inputs/icinga2/icinga2_test.go
Labels: feat, area/configuration, ready for final review

#17119 feat(migrations): Add migration for common.tls ssl options
  migrations/all/general_common_tls.go
  migrations/general_common_tls/migration.go
  migrations/general_common_tls/migration_test.go
  migrations/general_common_tls/testcases/deprecated_ssl/dummy
  migrations/general_common_tls/testcases/deprecated_ssl/expected.conf
  migrations/general_common_tls/testcases/deprecated_ssl/telegraf.conf
  migrations/inputs_openldap/testcases/mixed_config/expected.conf
  migrations/inputs_openldap/testcases/mixed_config/telegraf.conf
  plugins/common/tls/config.go
  plugins/common/tls/config_test.go
Labels: feat, area/configuration, ready for final review

#17159 feat(migrations): Add option migration for inputs.ntpq
  migrations/all/inputs_ntpq.go
  migrations/inputs_ntpq/migration.go
  migrations/inputs_ntpq/migration_test.go
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup/expected.conf
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup/telegraf.conf
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup_duplicate/expected.conf
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup_duplicate/telegraf.conf
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup_existing/expected.conf
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup_existing/telegraf.conf
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup_true/expected.conf
  migrations/inputs_ntpq/testcases/deprecated_dns_lookup_true/telegraf.conf
  plugins/inputs/ntpq/ntpq.go
Labels: feat, area/configuration, ready for final review

#17158 feat(migrations): Add option migration for inputs.http_listener_v2
  migrations/all/inputs_http_listener_v2.go
  migrations/inputs_http_listener_v2/migration.go
  migrations/inputs_http_listener_v2/migration_test.go
  migrations/inputs_http_listener_v2/testcases/deprecated_path/expected.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_path/telegraf.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_path_duplicate/expected.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_path_duplicate/telegraf.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_path_existing/expected.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_path_existing/telegraf.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_port/expected.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_port/telegraf.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_port_existing/expected.conf
  migrations/inputs_http_listener_v2/testcases/deprecated_port_existing/telegraf.conf
  plugins/inputs/http_listener_v2/http_listener_v2.go
  plugins/inputs/http_listener_v2/http_listener_v2_test.go
Labels: feat, area/configuration, ready for final review

#17105 feat(migrations): Add migration for inputs.rabbitmq
  migrations/all/inputs_rabbitmq.go
  migrations/inputs_rabbitmq/migration.go
  migrations/inputs_rabbitmq/migration_test.go
  migrations/inputs_rabbitmq/testcases/name/expected.conf
  migrations/inputs_rabbitmq/testcases/name/telegraf.conf
  migrations/inputs_rabbitmq/testcases/name_duplicate/expected.conf
  migrations/inputs_rabbitmq/testcases/name_duplicate/telegraf.conf
  migrations/inputs_rabbitmq/testcases/queues/expected.conf
  migrations/inputs_rabbitmq/testcases/queues/telegraf.conf
  migrations/inputs_rabbitmq/testcases/queues_duplicate/expected.conf
  migrations/inputs_rabbitmq/testcases/queues_duplicate/telegraf.conf
  migrations/inputs_rabbitmq/testcases/queues_existing/expected.conf
  migrations/inputs_rabbitmq/testcases/queues_existing/telegraf.conf
  plugins/inputs/rabbitmq/rabbitmq.go
Labels: feat, area/configuration, ready for final review

#17176 feat(migrations): Add option migration for outputs.mqtt
  migrations/all/outputs_mqtt.go
  migrations/outputs_mqtt/migration.go
  migrations/outputs_mqtt/migration_test.go
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix/expected.conf
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix/telegraf.conf
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix_duplicate/expected.conf
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix_duplicate/telegraf.conf
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix_duplicate_slash/expected.conf
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix_duplicate_slash/telegraf.conf
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix_existing/expected.conf
  migrations/outputs_mqtt/testcases/deprecated_topic_prefix_existing/telegraf.conf
  plugins/outputs/mqtt/mqtt.go
  plugins/outputs/mqtt/mqtt_test.go
  plugins/outputs/mqtt/topic_name_generator.go
Labels: feat, area/configuration

#17110 feat(migrations): Add migration for inputs.kube_inventory
  migrations/all/inputs_kube_inventory.go
  migrations/inputs_kube_inventory/migration.go
  migrations/inputs_kube_inventory/migration_test.go
  migrations/inputs_kube_inventory/testcases/bearer_token_string_only/expected.conf
  migrations/inputs_kube_inventory/testcases/bearer_token_string_only/telegraf.conf
  migrations/inputs_kube_inventory/testcases/mixed_tokens/expected.conf
  migrations/inputs_kube_inventory/testcases/mixed_tokens/telegraf.conf
  plugins/inputs/kube_inventory/client.go
  plugins/inputs/kube_inventory/client_test.go
  plugins/inputs/kube_inventory/kube_inventory.go
Labels: feat, area/configuration, ready for final review

#17171 feat(migrations): Add option migration for inputs.statsd
  migrations/all/inputs_statsd.go
  migrations/inputs_statsd/migration.go
  migrations/inputs_statsd/migration_test.go
  migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags/expected.conf
  migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags/telegraf.conf
  migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags_false/expected.conf
  migrations/inputs_statsd/testcases/deprecated_parse_data_dog_tags_false/telegraf.conf
  migrations/inputs_statsd/testcases/deprecated_udp_packet_size/expected.conf
  migrations/inputs_statsd/testcases/deprecated_udp_packet_size/telegraf.conf
  plugins/inputs/statsd/statsd.go
Labels: feat, area/configuration, ready for final review

#17109 feat(migrations): Add migration for inputs.kubernetes
  migrations/all/inputs_kubernetes.go
  migrations/inputs_kubernetes/migration.go
  migrations/inputs_kubernetes/migration_test.go
  migrations/inputs_kubernetes/testcases/bearer_token_string_only/expected.conf
  migrations/inputs_kubernetes/testcases/bearer_token_string_only/telegraf.conf
  migrations/inputs_kubernetes/testcases/default_case/expected.conf
  migrations/inputs_kubernetes/testcases/default_case/telegraf.conf
  migrations/inputs_kubernetes/testcases/mixed_tokens/expected.conf
  migrations/inputs_kubernetes/testcases/mixed_tokens/telegraf.conf
  plugins/inputs/kubernetes/kubernetes.go
Labels: feat, area/configuration, ready for final review

#17051 feat(inputs.opcua): Allow forcing reconnection on every gather cycle
  plugins/inputs/opcua/opcua.go
  plugins/inputs/opcua/opcua_test.go
  plugins/inputs/opcua/read_client.go
Labels: feat, area/opcua, ready for final review, plugin/input

#17048 feat(agent): Add debounce for watch events
  cmd/telegraf/main.go
  cmd/telegraf/telegraf.go
Labels: feat, area/agent, ready for final review

#17124 feat(migrations): Add migration for inputs.elasticsearch
  migrations/all/inputs_elasticsearch.go
  migrations/inputs_elasticsearch/migration.go
  migrations/inputs_elasticsearch/migration_test.go
  migrations/inputs_elasticsearch/testcases/http_timeout_to_timeout/expected.conf
  migrations/inputs_elasticsearch/testcases/http_timeout_to_timeout/telegraf.conf
  migrations/inputs_elasticsearch/testcases/http_timeout_with_auth/expected.conf
  migrations/inputs_elasticsearch/testcases/http_timeout_with_auth/telegraf.conf
  migrations/inputs_elasticsearch/testcases/http_timeout_with_existing_timeout/expected.conf
  migrations/inputs_elasticsearch/testcases/http_timeout_with_existing_timeout/telegraf.conf
  migrations/inputs_elasticsearch/testcases/http_timeout_with_tls/expected.conf
  migrations/inputs_elasticsearch/testcases/http_timeout_with_tls/telegraf.conf
  migrations/inputs_elasticsearch/testcases/multiple_elasticsearch_instances/expected.conf
  migrations/inputs_elasticsearch/testcases/multiple_elasticsearch_instances/telegraf.conf
  plugins/inputs/elasticsearch/elasticsearch.go
Labels: feat, area/configuration, ready for final review

#17173 feat(migrations): Add option migration for outputs.remotefile
  migrations/all/outputs_remotefile.go
  migrations/outputs_remotefile/migration.go
  migrations/outputs_remotefile/migration_test.go
  migrations/outputs_remotefile/testcases/simple/expected.conf
  migrations/outputs_remotefile/testcases/simple/telegraf.conf
  plugins/outputs/remotefile/remotefile.go
Labels: feat, area/configuration, ready for final review

#16699 fix(inputs.win_wmi): Free resources to avoid leaks
  plugins/inputs/win_wmi/method.go
Labels: area/windows, fix, ready for final review, plugin/input

#17024 feat(inputs.lvm): Add sync_percent for lvm_logical_vol
  plugins/inputs/lvm/README.md
  plugins/inputs/lvm/lvm.go
  plugins/inputs/lvm/lvm_test.go
Labels: feat, ready for final review, plugin/input

#17201 fix(inputs.opcua): Fix integration test for consecutive session error
  plugins/inputs/opcua/opcua_test.go
Labels: fix, area/opcua, ready for final review, plugin/input

#17239 test(inputs.snmp_trap): Fix flaky test by waiting for the log message to appear
  plugins/inputs/snmp_trap/snmp_trap_test.go
Labels: ready for final review, plugin/input, test

#17241 test(common.socket): Fix flaky test
  plugins/common/socket/socket_test.go
Labels: ready for final review, test

#17240 fix(disk-buffer): Correctly reset the mask after adding to an empty buffer
  models/buffer_disk.go
  models/buffer_disk_test.go
Labels: fix, area/agent, ready for final review, plugin/output

#17214 fix(inputs.ntpq): Fix ntpq field misalignment parsing errors
  plugins/inputs/ntpq/ntpq.go
  plugins/inputs/ntpq/testcases/pool_when_headers_as_data/expected.err
  plugins/inputs/ntpq/testcases/pool_when_headers_as_data/expected.out
  plugins/inputs/ntpq/testcases/pool_when_headers_as_data/input.txt
  plugins/inputs/ntpq/testcases/pool_when_headers_as_data/telegraf.conf
Labels: fix, ready for final review, plugin/input
